/**
 * This class is generated by jOOQ
 */
package org.jooq.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.udt.records.BrochureLineArrayRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignBlSetAndean extends AbstractRoutine<BigDecimal> {

	private static final long serialVersionUID = 1601783549;

	/**
	 * The parameter <code>WETRN.ASSIGN_BL_SET_ANDEAN.RETURN_VALUE</code>.
	 */
	public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.ASSIGN_BL_SET_ANDEAN.BL_LINE_ARRAY</code>.
	 */
	public static final Parameter<BrochureLineArrayRecord> BL_LINE_ARRAY = createParameter("BL_LINE_ARRAY", org.jooq.udt.BrochureLine.BROCHURE_LINE.getDataType().asArrayDataType(org.jooq.udt.records.BrochureLineArrayRecord.class), false);

	/**
	 * The parameter <code>WETRN.ASSIGN_BL_SET_ANDEAN.BL_TABLE_CASE</code>.
	 */
	public static final Parameter<BigDecimal> BL_TABLE_CASE = createParameter("BL_TABLE_CASE", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public AssignBlSetAndean() {
		super("ASSIGN_BL_SET_ANDEAN", Wetrn.WETRN, org.jooq.impl.SQLDataType.NUMERIC);

		setReturnParameter(RETURN_VALUE);
		addInParameter(BL_LINE_ARRAY);
		addInParameter(BL_TABLE_CASE);
	}

	/**
	 * Set the <code>BL_LINE_ARRAY</code> parameter IN value to the routine
	 */
	public void setBlLineArray(BrochureLineArrayRecord value) {
		setValue(BL_LINE_ARRAY, value);
	}

	/**
	 * Set the <code>BL_LINE_ARRAY</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setBlLineArray(Field<BrochureLineArrayRecord> field) {
		setField(BL_LINE_ARRAY, field);
	}

	/**
	 * Set the <code>BL_TABLE_CASE</code> parameter IN value to the routine
	 */
	public void setBlTableCase(Number value) {
		setNumber(BL_TABLE_CASE, value);
	}

	/**
	 * Set the <code>BL_TABLE_CASE</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setBlTableCase(Field<? extends Number> field) {
		setNumber(BL_TABLE_CASE, field);
	}
}
