/**
 * This class is generated by jOOQ
 */
package org.jooq.packages;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Wetrn;
import org.jooq.impl.PackageImpl;
import org.jooq.packages.app_lnm_cena_bl.AssignBl;


/**
 * Convenience access to all stored procedures and functions in APP_LNM_CENA_BL
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppLnmCenaBl extends PackageImpl {

	private static final long serialVersionUID = -1793749361;

	/**
	 * The reference instance of <code>WETRN.APP_LNM_CENA_BL</code>
	 */
	public static final AppLnmCenaBl APP_LNM_CENA_BL = new AppLnmCenaBl();

	/**
	 * Call <code>WETRN.APP_LNM_CENA_BL.ASSIGN_BL</code>
	 */
	public static void assignBl(Configuration configuration, Number pRunId, Number pMrktId, Number pOffrPerdId, String pVehIdList, Number pVerId, String pUserId) {
		AssignBl p = new AssignBl();
		p.setPRunId(pRunId);
		p.setPMrktId(pMrktId);
		p.setPOffrPerdId(pOffrPerdId);
		p.setPVehIdList(pVehIdList);
		p.setPVerId(pVerId);
		p.setPUserId(pUserId);

		p.execute(configuration);
	}

	/**
	 * No further instances allowed
	 */
	private AppLnmCenaBl() {
		super("APP_LNM_CENA_BL", Wetrn.WETRN);
	}
}
