/**
 * This class is generated by jOOQ
 */
package org.jooq.packages;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Wetrn;
import org.jooq.impl.PackageImpl;
import org.jooq.packages.forecast_boost_validation.FrcstBstSrceVlidatn;
import org.jooq.packages.forecast_boost_validation.FrcstBstTrgtVlidatn;
import org.jooq.packages.forecast_boost_validation.GetFrcstBstIndividalParam;
import org.jooq.packages.forecast_boost_validation.GetFrcstBstParams;


/**
 * Convenience access to all stored procedures and functions in FORECAST_BOOST_VALIDATION
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ForecastBoostValidation extends PackageImpl {

	private static final long serialVersionUID = 740928453;

	/**
	 * The reference instance of <code>WETRN.FORECAST_BOOST_VALIDATION</code>
	 */
	public static final ForecastBoostValidation FORECAST_BOOST_VALIDATION = new ForecastBoostValidation();

	/**
	 * Call <code>WETRN.FORECAST_BOOST_VALIDATION.FRCST_BST_SRCE_VLIDATN</code>
	 */
	public static String frcstBstSrceVlidatn(Configuration configuration, Number pClstrId, Number pSrceMrktId, Number pSrcePerdId, String pSrceVehId, Number pSrceVerId, String pUserNm) {
		FrcstBstSrceVlidatn f = new FrcstBstSrceVlidatn();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktId(pSrceMrktId);
		f.setPSrcePerdId(pSrcePerdId);
		f.setPSrceVehId(pSrceVehId);
		f.setPSrceVerId(pSrceVerId);
		f.setPUserNm(pUserNm);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.FRCST_BST_SRCE_VLIDATN</code> as a field.
	 */
	public static Field<String> frcstBstSrceVlidatn(Number pClstrId, Number pSrceMrktId, Number pSrcePerdId, String pSrceVehId, Number pSrceVerId, String pUserNm) {
		FrcstBstSrceVlidatn f = new FrcstBstSrceVlidatn();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktId(pSrceMrktId);
		f.setPSrcePerdId(pSrcePerdId);
		f.setPSrceVehId(pSrceVehId);
		f.setPSrceVerId(pSrceVerId);
		f.setPUserNm(pUserNm);

		return f.asField();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.FRCST_BST_SRCE_VLIDATN</code> as a field.
	 */
	public static Field<String> frcstBstSrceVlidatn(Field<? extends Number> pClstrId, Field<? extends Number> pSrceMrktId, Field<? extends Number> pSrcePerdId, Field<String> pSrceVehId, Field<? extends Number> pSrceVerId, Field<String> pUserNm) {
		FrcstBstSrceVlidatn f = new FrcstBstSrceVlidatn();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktId(pSrceMrktId);
		f.setPSrcePerdId(pSrcePerdId);
		f.setPSrceVehId(pSrceVehId);
		f.setPSrceVerId(pSrceVerId);
		f.setPUserNm(pUserNm);

		return f.asField();
	}

	/**
	 * Call <code>WETRN.FORECAST_BOOST_VALIDATION.FRCST_BST_TRGT_VLIDATN</code>
	 */
	public static String frcstBstTrgtVlidatn(Configuration configuration, Number pMrktId, Number pPerdId) {
		FrcstBstTrgtVlidatn f = new FrcstBstTrgtVlidatn();
		f.setPMrktId(pMrktId);
		f.setPPerdId(pPerdId);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.FRCST_BST_TRGT_VLIDATN</code> as a field.
	 */
	public static Field<String> frcstBstTrgtVlidatn(Number pMrktId, Number pPerdId) {
		FrcstBstTrgtVlidatn f = new FrcstBstTrgtVlidatn();
		f.setPMrktId(pMrktId);
		f.setPPerdId(pPerdId);

		return f.asField();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.FRCST_BST_TRGT_VLIDATN</code> as a field.
	 */
	public static Field<String> frcstBstTrgtVlidatn(Field<? extends Number> pMrktId, Field<? extends Number> pPerdId) {
		FrcstBstTrgtVlidatn f = new FrcstBstTrgtVlidatn();
		f.setPMrktId(pMrktId);
		f.setPPerdId(pPerdId);

		return f.asField();
	}

	/**
	 * Call <code>WETRN.FORECAST_BOOST_VALIDATION.GET_FRCST_BST_INDIVIDAL_PARAM</code>
	 */
	public static Object getFrcstBstIndividalParam(Configuration configuration, Number pClstrId, Number pSrceMrktId, Number pSrcePerdId, String pSrceVehId, Number pSrceVerId, String pUserNm) {
		GetFrcstBstIndividalParam f = new GetFrcstBstIndividalParam();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktId(pSrceMrktId);
		f.setPSrcePerdId(pSrcePerdId);
		f.setPSrceVehId(pSrceVehId);
		f.setPSrceVerId(pSrceVerId);
		f.setPUserNm(pUserNm);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.GET_FRCST_BST_INDIVIDAL_PARAM</code> as a field.
	 */
	public static Field<Object> getFrcstBstIndividalParam(Number pClstrId, Number pSrceMrktId, Number pSrcePerdId, String pSrceVehId, Number pSrceVerId, String pUserNm) {
		GetFrcstBstIndividalParam f = new GetFrcstBstIndividalParam();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktId(pSrceMrktId);
		f.setPSrcePerdId(pSrcePerdId);
		f.setPSrceVehId(pSrceVehId);
		f.setPSrceVerId(pSrceVerId);
		f.setPUserNm(pUserNm);

		return f.asField();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.GET_FRCST_BST_INDIVIDAL_PARAM</code> as a field.
	 */
	public static Field<Object> getFrcstBstIndividalParam(Field<? extends Number> pClstrId, Field<? extends Number> pSrceMrktId, Field<? extends Number> pSrcePerdId, Field<String> pSrceVehId, Field<? extends Number> pSrceVerId, Field<String> pUserNm) {
		GetFrcstBstIndividalParam f = new GetFrcstBstIndividalParam();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktId(pSrceMrktId);
		f.setPSrcePerdId(pSrcePerdId);
		f.setPSrceVehId(pSrceVehId);
		f.setPSrceVerId(pSrceVerId);
		f.setPUserNm(pUserNm);

		return f.asField();
	}

	/**
	 * Call <code>WETRN.FORECAST_BOOST_VALIDATION.GET_FRCST_BST_PARAMS</code>
	 */
	public static Object getFrcstBstParams(Configuration configuration, Number pClstrId, String pSrceMrktIds, String pSrcePerdIds, String pSrceVehIds, String pSrceVerIds, String pUserNm) {
		GetFrcstBstParams f = new GetFrcstBstParams();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktIds(pSrceMrktIds);
		f.setPSrcePerdIds(pSrcePerdIds);
		f.setPSrceVehIds(pSrceVehIds);
		f.setPSrceVerIds(pSrceVerIds);
		f.setPUserNm(pUserNm);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.GET_FRCST_BST_PARAMS</code> as a field.
	 */
	public static Field<Object> getFrcstBstParams(Number pClstrId, String pSrceMrktIds, String pSrcePerdIds, String pSrceVehIds, String pSrceVerIds, String pUserNm) {
		GetFrcstBstParams f = new GetFrcstBstParams();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktIds(pSrceMrktIds);
		f.setPSrcePerdIds(pSrcePerdIds);
		f.setPSrceVehIds(pSrceVehIds);
		f.setPSrceVerIds(pSrceVerIds);
		f.setPUserNm(pUserNm);

		return f.asField();
	}

	/**
	 * Get <code>WETRN.FORECAST_BOOST_VALIDATION.GET_FRCST_BST_PARAMS</code> as a field.
	 */
	public static Field<Object> getFrcstBstParams(Field<? extends Number> pClstrId, Field<String> pSrceMrktIds, Field<String> pSrcePerdIds, Field<String> pSrceVehIds, Field<String> pSrceVerIds, Field<String> pUserNm) {
		GetFrcstBstParams f = new GetFrcstBstParams();
		f.setPClstrId(pClstrId);
		f.setPSrceMrktIds(pSrceMrktIds);
		f.setPSrcePerdIds(pSrcePerdIds);
		f.setPSrceVehIds(pSrceVehIds);
		f.setPSrceVerIds(pSrceVerIds);
		f.setPUserNm(pUserNm);

		return f.asField();
	}

	/**
	 * No further instances allowed
	 */
	private ForecastBoostValidation() {
		super("FORECAST_BOOST_VALIDATION", Wetrn.WETRN);
	}
}
