/**
 * This class is generated by jOOQ
 */
package org.jooq.packages;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record;
import org.jooq.Result;
import org.jooq.Wetrn;
import org.jooq.impl.PackageImpl;
import org.jooq.packages.rep_dly_bilng_adj.Getdata;


/**
 * Convenience access to all stored procedures and functions in REP_DLY_BILNG_ADJ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepDlyBilngAdj extends PackageImpl {

	private static final long serialVersionUID = 743312917;

	/**
	 * The reference instance of <code>WETRN.REP_DLY_BILNG_ADJ</code>
	 */
	public static final RepDlyBilngAdj REP_DLY_BILNG_ADJ = new RepDlyBilngAdj();

	/**
	 * Call <code>WETRN.REP_DLY_BILNG_ADJ.GETDATA</code>
	 */
	public static Result<Record> getdata(Configuration configuration, String pClusterId, String pMrktId, String pCosPerdId, String pCooPerdIds) {
		Getdata p = new Getdata();
		p.setPClusterId(pClusterId);
		p.setPMrktId(pMrktId);
		p.setPCosPerdId(pCosPerdId);
		p.setPCooPerdIds(pCooPerdIds);

		p.execute(configuration);
		return p.getResult();
	}

	/**
	 * No further instances allowed
	 */
	private RepDlyBilngAdj() {
		super("REP_DLY_BILNG_ADJ", Wetrn.WETRN);
	}
}
