/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.pa_maps_gta;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.PaMapsGta;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetGta extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1154816688;

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.PMRKT_ID</code>.
	 */
	public static final Parameter<BigDecimal> PMRKT_ID = createParameter("PMRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.PVEH_ID</code>.
	 */
	public static final Parameter<BigDecimal> PVEH_ID = createParameter("PVEH_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.POFFR_PERD_ID</code>.
	 */
	public static final Parameter<BigDecimal> POFFR_PERD_ID = createParameter("POFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.POFFR_ID</code>.
	 */
	public static final Parameter<BigDecimal> POFFR_ID = createParameter("POFFR_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.PFROM_SLS_TYP</code>.
	 */
	public static final Parameter<BigDecimal> PFROM_SLS_TYP = createParameter("PFROM_SLS_TYP", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.PTO_SLS_TYP</code>.
	 */
	public static final Parameter<BigDecimal> PTO_SLS_TYP = createParameter("PTO_SLS_TYP", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_GTA.SET_GTA.PVER_ID</code>.
	 */
	public static final Parameter<BigDecimal> PVER_ID = createParameter("PVER_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public SetGta() {
		super("SET_GTA", Wetrn.WETRN, PaMapsGta.PA_MAPS_GTA);

		addInParameter(PMRKT_ID);
		addInParameter(PVEH_ID);
		addInParameter(POFFR_PERD_ID);
		addInParameter(POFFR_ID);
		addInParameter(PFROM_SLS_TYP);
		addInParameter(PTO_SLS_TYP);
		addInParameter(PVER_ID);
	}

	/**
	 * Set the <code>PMRKT_ID</code> parameter IN value to the routine
	 */
	public void setPmrktId(Number value) {
		setNumber(PMRKT_ID, value);
	}

	/**
	 * Set the <code>PVEH_ID</code> parameter IN value to the routine
	 */
	public void setPvehId(Number value) {
		setNumber(PVEH_ID, value);
	}

	/**
	 * Set the <code>POFFR_PERD_ID</code> parameter IN value to the routine
	 */
	public void setPoffrPerdId(Number value) {
		setNumber(POFFR_PERD_ID, value);
	}

	/**
	 * Set the <code>POFFR_ID</code> parameter IN value to the routine
	 */
	public void setPoffrId(Number value) {
		setNumber(POFFR_ID, value);
	}

	/**
	 * Set the <code>PFROM_SLS_TYP</code> parameter IN value to the routine
	 */
	public void setPfromSlsTyp(Number value) {
		setNumber(PFROM_SLS_TYP, value);
	}

	/**
	 * Set the <code>PTO_SLS_TYP</code> parameter IN value to the routine
	 */
	public void setPtoSlsTyp(Number value) {
		setNumber(PTO_SLS_TYP, value);
	}

	/**
	 * Set the <code>PVER_ID</code> parameter IN value to the routine
	 */
	public void setPverId(Number value) {
		setNumber(PVER_ID, value);
	}
}
