/**
 * This class is generated by jOOQ
 */
package org.jooq.udt.records;


import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Wetrn;
import org.jooq.impl.ArrayRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NumberArrayRecord extends ArrayRecordImpl<BigDecimal> {

	private static final long serialVersionUID = 2992971;

	/**
	 * @deprecated - 3.4.0 - [#3126] - Use the {@link #NumberArrayRecord()} constructor instead
	 */
	@java.lang.Deprecated
	public NumberArrayRecord(Configuration configuration) {
		super(Wetrn.WETRN, "NUMBER_ARRAY", org.jooq.impl.SQLDataType.NUMERIC, configuration);
	}

	/**
	 * @deprecated - 3.4.0 - [#3126] - Use the {@link #NumberArrayRecord()} constructor instead
	 */
	@java.lang.Deprecated
	public NumberArrayRecord(Configuration configuration, BigDecimal... array) {
		this(configuration);
		set(array);
	}

	/**
	 * @deprecated - 3.4.0 - [#3126] - Use the {@link #NumberArrayRecord()} constructor instead
	 */
	@java.lang.Deprecated
	public NumberArrayRecord(Configuration configuration, List<? extends BigDecimal> list) {
		this(configuration);
		setList(list);
	}

	/**
	 * Create a new <code>WETRN.NUMBER_ARRAY</code> record
	 */
	public NumberArrayRecord() {
		super(Wetrn.WETRN, "NUMBER_ARRAY", org.jooq.impl.SQLDataType.NUMERIC);
	}

	/**
	 * Create a new <code>WETRN.NUMBER_ARRAY</code> record
	 */
	public NumberArrayRecord(BigDecimal... array) {
		this();
		set(array);
	}

	/**
	 * Create a new <code>WETRN.NUMBER_ARRAY</code> record
	 */
	public NumberArrayRecord(Collection<? extends BigDecimal> collection) {
		this();
		set(collection);
	}
}
