/**
 * This class is generated by jOOQ
 */
package org.jooq.udt.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.impl.UDTRecordImpl;
import org.jooq.udt.ObjActiveNotPlanned;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjActiveNotPlannedRecord extends UDTRecordImpl<ObjActiveNotPlannedRecord> {

	private static final long serialVersionUID = 344511139;

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.REC_STUS</code>.
	 */
	public void setRecStus(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.REC_STUS</code>.
	 */
	public String getRecStus() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.CATGRY_NM</code>.
	 */
	public void setCatgryNm(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.CATGRY_NM</code>.
	 */
	public String getCatgryNm() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.BRND_FMLY_NM</code>.
	 */
	public void setBrndFmlyNm(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.BRND_FMLY_NM</code>.
	 */
	public String getBrndFmlyNm() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SGMT_NM</code>.
	 */
	public void setSgmtNm(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SGMT_NM</code>.
	 */
	public String getSgmtNm() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROD_TYP_DESC_TXT</code>.
	 */
	public void setProdTypDescTxt(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROD_TYP_DESC_TXT</code>.
	 */
	public String getProdTypDescTxt() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PRFL_CD</code>.
	 */
	public void setPrflCd(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PRFL_CD</code>.
	 */
	public Integer getPrflCd() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PRFL_NM</code>.
	 */
	public void setPrflNm(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PRFL_NM</code>.
	 */
	public String getPrflNm() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SKU_ID</code>.
	 */
	public void setSkuId(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SKU_ID</code>.
	 */
	public BigDecimal getSkuId() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.LCL_SKU_NM</code>.
	 */
	public void setLclSkuNm(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.LCL_SKU_NM</code>.
	 */
	public String getLclSkuNm() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.OFFR_DESC_TXT</code>.
	 */
	public void setOffrDescTxt(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.OFFR_DESC_TXT</code>.
	 */
	public String getOffrDescTxt() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SCTN_NM</code>.
	 */
	public void setSctnNm(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SCTN_NM</code>.
	 */
	public String getSctnNm() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SLS_CLS_DESC_TXT</code>.
	 */
	public void setSlsClsDescTxt(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SLS_CLS_DESC_TXT</code>.
	 */
	public String getSlsClsDescTxt() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.AVLBL_PERD_ID</code>.
	 */
	public void setAvlblPerdId(BigDecimal value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.AVLBL_PERD_ID</code>.
	 */
	public BigDecimal getAvlblPerdId() {
		return (BigDecimal) getValue(12);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.INTRDCTN_PERD_ID</code>.
	 */
	public void setIntrdctnPerdId(BigDecimal value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.INTRDCTN_PERD_ID</code>.
	 */
	public BigDecimal getIntrdctnPerdId() {
		return (BigDecimal) getValue(13);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.DSPOSTN_PERD_ID</code>.
	 */
	public void setDspostnPerdId(BigDecimal value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.DSPOSTN_PERD_ID</code>.
	 */
	public BigDecimal getDspostnPerdId() {
		return (BigDecimal) getValue(14);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.NON_SALE_PERD_ID</code>.
	 */
	public void setNonSalePerdId(BigDecimal value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.NON_SALE_PERD_ID</code>.
	 */
	public BigDecimal getNonSalePerdId() {
		return (BigDecimal) getValue(15);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.REG_PRC_AMT</code>.
	 */
	public void setRegPrcAmt(BigDecimal value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.REG_PRC_AMT</code>.
	 */
	public BigDecimal getRegPrcAmt() {
		return (BigDecimal) getValue(16);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.WGHTD_AVG_COST_AMT</code>.
	 */
	public void setWghtdAvgCostAmt(BigDecimal value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.WGHTD_AVG_COST_AMT</code>.
	 */
	public BigDecimal getWghtdAvgCostAmt() {
		return (BigDecimal) getValue(17);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.UNIT_QTY</code>.
	 */
	public void setUnitQty(Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.UNIT_QTY</code>.
	 */
	public Integer getUnitQty() {
		return (Integer) getValue(18);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SLS_PRC_AMT</code>.
	 */
	public void setSlsPrcAmt(BigDecimal value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SLS_PRC_AMT</code>.
	 */
	public BigDecimal getSlsPrcAmt() {
		return (BigDecimal) getValue(19);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PG_WGHT_PCT</code>.
	 */
	public void setPgWghtPct(BigDecimal value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PG_WGHT_PCT</code>.
	 */
	public BigDecimal getPgWghtPct() {
		return (BigDecimal) getValue(20);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PG_TYP_DESC_TXT</code>.
	 */
	public void setPgTypDescTxt(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PG_TYP_DESC_TXT</code>.
	 */
	public String getPgTypDescTxt() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROD_ENDRSMT_DESC_TXT</code>.
	 */
	public void setProdEndrsmtDescTxt(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROD_ENDRSMT_DESC_TXT</code>.
	 */
	public String getProdEndrsmtDescTxt() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.IMPCT_CATGRY_NM</code>.
	 */
	public void setImpctCatgryNm(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.IMPCT_CATGRY_NM</code>.
	 */
	public String getImpctCatgryNm() {
		return (String) getValue(23);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.BDGT_AMT</code>.
	 */
	public void setBdgtAmt(BigDecimal value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.BDGT_AMT</code>.
	 */
	public BigDecimal getBdgtAmt() {
		return (BigDecimal) getValue(24);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_DESC_TXT</code>.
	 */
	public void setPromtnDescTxt(String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_DESC_TXT</code>.
	 */
	public String getPromtnDescTxt() {
		return (String) getValue(25);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_CLM_DESC_TXT</code>.
	 */
	public void setPromtnClmDescTxt(String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_CLM_DESC_TXT</code>.
	 */
	public String getPromtnClmDescTxt() {
		return (String) getValue(26);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PYMT_TYP_DESC_TXT</code>.
	 */
	public void setPymtTypDescTxt(String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PYMT_TYP_DESC_TXT</code>.
	 */
	public String getPymtTypDescTxt() {
		return (String) getValue(27);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.TAX_TYP_DESC_TXT</code>.
	 */
	public void setTaxTypDescTxt(String value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.TAX_TYP_DESC_TXT</code>.
	 */
	public String getTaxTypDescTxt() {
		return (String) getValue(28);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.COMSN_TYP_DESC_TXT</code>.
	 */
	public void setComsnTypDescTxt(String value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.COMSN_TYP_DESC_TXT</code>.
	 */
	public String getComsnTypDescTxt() {
		return (String) getValue(29);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.CHRTY_AMT</code>.
	 */
	public void setChrtyAmt(BigDecimal value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.CHRTY_AMT</code>.
	 */
	public BigDecimal getChrtyAmt() {
		return (BigDecimal) getValue(30);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.AWRD_SLS_PRC_AMT</code>.
	 */
	public void setAwrdSlsPrcAmt(BigDecimal value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.AWRD_SLS_PRC_AMT</code>.
	 */
	public BigDecimal getAwrdSlsPrcAmt() {
		return (BigDecimal) getValue(31);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SLS_CLS_CD</code>.
	 */
	public void setSlsClsCd(BigDecimal value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.SLS_CLS_CD</code>.
	 */
	public BigDecimal getSlsClsCd() {
		return (BigDecimal) getValue(32);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PG_TYP_ID</code>.
	 */
	public void setPgTypId(BigDecimal value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PG_TYP_ID</code>.
	 */
	public BigDecimal getPgTypId() {
		return (BigDecimal) getValue(33);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROD_ENDRSMT_ID</code>.
	 */
	public void setProdEndrsmtId(BigDecimal value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROD_ENDRSMT_ID</code>.
	 */
	public BigDecimal getProdEndrsmtId() {
		return (BigDecimal) getValue(34);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.IMPCT_CATGRY_ID</code>.
	 */
	public void setImpctCatgryId(BigDecimal value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.IMPCT_CATGRY_ID</code>.
	 */
	public BigDecimal getImpctCatgryId() {
		return (BigDecimal) getValue(35);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_ID</code>.
	 */
	public void setPromtnId(BigDecimal value) {
		setValue(36, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_ID</code>.
	 */
	public BigDecimal getPromtnId() {
		return (BigDecimal) getValue(36);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_CLM_ID</code>.
	 */
	public void setPromtnClmId(BigDecimal value) {
		setValue(37, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PROMTN_CLM_ID</code>.
	 */
	public BigDecimal getPromtnClmId() {
		return (BigDecimal) getValue(37);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PYMT_TYP</code>.
	 */
	public void setPymtTyp(String value) {
		setValue(38, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.PYMT_TYP</code>.
	 */
	public String getPymtTyp() {
		return (String) getValue(38);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.TAX_TYPE_ID</code>.
	 */
	public void setTaxTypeId(BigDecimal value) {
		setValue(39, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.TAX_TYPE_ID</code>.
	 */
	public BigDecimal getTaxTypeId() {
		return (BigDecimal) getValue(39);
	}

	/**
	 * Setter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.COMSN_TYP</code>.
	 */
	public void setComsnTyp(String value) {
		setValue(40, value);
	}

	/**
	 * Getter for <code>WETRN.OBJ_ACTIVE_NOT_PLANNED.COMSN_TYP</code>.
	 */
	public String getComsnTyp() {
		return (String) getValue(40);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ObjActiveNotPlannedRecord
	 */
	public ObjActiveNotPlannedRecord() {
		super(ObjActiveNotPlanned.OBJ_ACTIVE_NOT_PLANNED);
	}

	/**
	 * Create a detached, initialised ObjActiveNotPlannedRecord
	 */
	public ObjActiveNotPlannedRecord(String recStus, String catgryNm, String brndFmlyNm, String sgmtNm, String prodTypDescTxt, Integer prflCd, String prflNm, BigDecimal skuId, String lclSkuNm, String offrDescTxt, String sctnNm, String slsClsDescTxt, BigDecimal avlblPerdId, BigDecimal intrdctnPerdId, BigDecimal dspostnPerdId, BigDecimal nonSalePerdId, BigDecimal regPrcAmt, BigDecimal wghtdAvgCostAmt, Integer unitQty, BigDecimal slsPrcAmt, BigDecimal pgWghtPct, String pgTypDescTxt, String prodEndrsmtDescTxt, String impctCatgryNm, BigDecimal bdgtAmt, String promtnDescTxt, String promtnClmDescTxt, String pymtTypDescTxt, String taxTypDescTxt, String comsnTypDescTxt, BigDecimal chrtyAmt, BigDecimal awrdSlsPrcAmt, BigDecimal slsClsCd, BigDecimal pgTypId, BigDecimal prodEndrsmtId, BigDecimal impctCatgryId, BigDecimal promtnId, BigDecimal promtnClmId, String pymtTyp, BigDecimal taxTypeId, String comsnTyp) {
		super(ObjActiveNotPlanned.OBJ_ACTIVE_NOT_PLANNED);

		setValue(0, recStus);
		setValue(1, catgryNm);
		setValue(2, brndFmlyNm);
		setValue(3, sgmtNm);
		setValue(4, prodTypDescTxt);
		setValue(5, prflCd);
		setValue(6, prflNm);
		setValue(7, skuId);
		setValue(8, lclSkuNm);
		setValue(9, offrDescTxt);
		setValue(10, sctnNm);
		setValue(11, slsClsDescTxt);
		setValue(12, avlblPerdId);
		setValue(13, intrdctnPerdId);
		setValue(14, dspostnPerdId);
		setValue(15, nonSalePerdId);
		setValue(16, regPrcAmt);
		setValue(17, wghtdAvgCostAmt);
		setValue(18, unitQty);
		setValue(19, slsPrcAmt);
		setValue(20, pgWghtPct);
		setValue(21, pgTypDescTxt);
		setValue(22, prodEndrsmtDescTxt);
		setValue(23, impctCatgryNm);
		setValue(24, bdgtAmt);
		setValue(25, promtnDescTxt);
		setValue(26, promtnClmDescTxt);
		setValue(27, pymtTypDescTxt);
		setValue(28, taxTypDescTxt);
		setValue(29, comsnTypDescTxt);
		setValue(30, chrtyAmt);
		setValue(31, awrdSlsPrcAmt);
		setValue(32, slsClsCd);
		setValue(33, pgTypId);
		setValue(34, prodEndrsmtId);
		setValue(35, impctCatgryId);
		setValue(36, promtnId);
		setValue(37, promtnClmId);
		setValue(38, pymtTyp);
		setValue(39, taxTypeId);
		setValue(40, comsnTyp);
	}
}
