/**
 * This class is generated by jOOQ
 */
package org.jooq.udt.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.impl.UDTRecordImpl;
import org.jooq.udt.TSaExcldVw;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSaExcldVwRecord extends UDTRecordImpl<TSaExcldVwRecord> {

	private static final long serialVersionUID = -1320374673;

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.FSC_CD</code>.
	 */
	public void setFscCd(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.FSC_CD</code>.
	 */
	public BigDecimal getFscCd() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.FSC_DESC</code>.
	 */
	public void setFscDesc(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.FSC_DESC</code>.
	 */
	public String getFscDesc() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.SKU_ID</code>.
	 */
	public void setSkuId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.SKU_ID</code>.
	 */
	public BigDecimal getSkuId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.LINE_NR</code>.
	 */
	public void setLineNr(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.LINE_NR</code>.
	 */
	public BigDecimal getLineNr() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.SLS_PRC_AMT</code>.
	 */
	public void setSlsPrcAmt(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.SLS_PRC_AMT</code>.
	 */
	public BigDecimal getSlsPrcAmt() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.NR_FOR_QTY</code>.
	 */
	public void setNrForQty(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.NR_FOR_QTY</code>.
	 */
	public BigDecimal getNrForQty() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.OFFR_TYP_DESC</code>.
	 */
	public void setOffrTypDesc(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.OFFR_TYP_DESC</code>.
	 */
	public String getOffrTypDesc() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.DMND_UNIT_QTY</code>.
	 */
	public void setDmndUnitQty(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.DMND_UNIT_QTY</code>.
	 */
	public BigDecimal getDmndUnitQty() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.DMND_GTA</code>.
	 */
	public void setDmndGta(BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.DMND_GTA</code>.
	 */
	public BigDecimal getDmndGta() {
		return (BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.BLD_UNIT_QTY</code>.
	 */
	public void setBldUnitQty(BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.BLD_UNIT_QTY</code>.
	 */
	public BigDecimal getBldUnitQty() {
		return (BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.BLD_GTA</code>.
	 */
	public void setBldGta(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.BLD_GTA</code>.
	 */
	public BigDecimal getBldGta() {
		return (BigDecimal) getValue(10);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.SLS_CHNL</code>.
	 */
	public void setSlsChnl(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.SLS_CHNL</code>.
	 */
	public String getSlsChnl() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.EXCLUDE</code>.
	 */
	public void setExclude(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.EXCLUDE</code>.
	 */
	public String getExclude() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.MATCH</code>.
	 */
	public void setMatch(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.MATCH</code>.
	 */
	public String getMatch() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.ERROR_CODE</code>.
	 */
	public void setErrorCode(BigDecimal value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.ERROR_CODE</code>.
	 */
	public BigDecimal getErrorCode() {
		return (BigDecimal) getValue(14);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.ERROR_MESSAGE</code>.
	 */
	public void setErrorMessage(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.ERROR_MESSAGE</code>.
	 */
	public String getErrorMessage() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.PRFL_CD</code>.
	 */
	public void setPrflCd(BigDecimal value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.PRFL_CD</code>.
	 */
	public BigDecimal getPrflCd() {
		return (BigDecimal) getValue(16);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.OFFR_PERD_ID</code>.
	 */
	public void setOffrPerdId(BigDecimal value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.OFFR_PERD_ID</code>.
	 */
	public BigDecimal getOffrPerdId() {
		return (BigDecimal) getValue(17);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.DLY_BILNG_ID</code>.
	 */
	public void setDlyBilngId(BigDecimal value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.DLY_BILNG_ID</code>.
	 */
	public BigDecimal getDlyBilngId() {
		return (BigDecimal) getValue(18);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.SLS_CLS_CD</code>.
	 */
	public void setSlsClsCd(BigDecimal value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.SLS_CLS_CD</code>.
	 */
	public BigDecimal getSlsClsCd() {
		return (BigDecimal) getValue(19);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.SLS_CLS_CD_DESC</code>.
	 */
	public void setSlsClsCdDesc(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.SLS_CLS_CD_DESC</code>.
	 */
	public String getSlsClsCdDesc() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.DLY_BLNG_IDS</code>.
	 */
	public void setDlyBlngIds(TblDlyBlngIdRecord value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.DLY_BLNG_IDS</code>.
	 */
	public TblDlyBlngIdRecord getDlyBlngIds() {
		return (TblDlyBlngIdRecord) getValue(21);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.DMND_COMSN_AMT</code>.
	 */
	public void setDmndComsnAmt(BigDecimal value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.DMND_COMSN_AMT</code>.
	 */
	public BigDecimal getDmndComsnAmt() {
		return (BigDecimal) getValue(22);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.DMND_TAX_AMT</code>.
	 */
	public void setDmndTaxAmt(BigDecimal value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.DMND_TAX_AMT</code>.
	 */
	public BigDecimal getDmndTaxAmt() {
		return (BigDecimal) getValue(23);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.BLD_COMSN_AMT</code>.
	 */
	public void setBldComsnAmt(BigDecimal value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.BLD_COMSN_AMT</code>.
	 */
	public BigDecimal getBldComsnAmt() {
		return (BigDecimal) getValue(24);
	}

	/**
	 * Setter for <code>WETRN.T_SA_EXCLD_VW.BLD_TAX_AMT</code>.
	 */
	public void setBldTaxAmt(BigDecimal value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>WETRN.T_SA_EXCLD_VW.BLD_TAX_AMT</code>.
	 */
	public BigDecimal getBldTaxAmt() {
		return (BigDecimal) getValue(25);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TSaExcldVwRecord
	 */
	public TSaExcldVwRecord() {
		super(TSaExcldVw.T_SA_EXCLD_VW);
	}

	/**
	 * Create a detached, initialised TSaExcldVwRecord
	 */
	public TSaExcldVwRecord(BigDecimal fscCd, String fscDesc, BigDecimal skuId, BigDecimal lineNr, BigDecimal slsPrcAmt, BigDecimal nrForQty, String offrTypDesc, BigDecimal dmndUnitQty, BigDecimal dmndGta, BigDecimal bldUnitQty, BigDecimal bldGta, String slsChnl, String exclude, String match, BigDecimal errorCode, String errorMessage, BigDecimal prflCd, BigDecimal offrPerdId, BigDecimal dlyBilngId, BigDecimal slsClsCd, String slsClsCdDesc, TblDlyBlngIdRecord dlyBlngIds, BigDecimal dmndComsnAmt, BigDecimal dmndTaxAmt, BigDecimal bldComsnAmt, BigDecimal bldTaxAmt) {
		super(TSaExcldVw.T_SA_EXCLD_VW);

		setValue(0, fscCd);
		setValue(1, fscDesc);
		setValue(2, skuId);
		setValue(3, lineNr);
		setValue(4, slsPrcAmt);
		setValue(5, nrForQty);
		setValue(6, offrTypDesc);
		setValue(7, dmndUnitQty);
		setValue(8, dmndGta);
		setValue(9, bldUnitQty);
		setValue(10, bldGta);
		setValue(11, slsChnl);
		setValue(12, exclude);
		setValue(13, match);
		setValue(14, errorCode);
		setValue(15, errorMessage);
		setValue(16, prflCd);
		setValue(17, offrPerdId);
		setValue(18, dlyBilngId);
		setValue(19, slsClsCd);
		setValue(20, slsClsCdDesc);
		setValue(21, dlyBlngIds);
		setValue(22, dmndComsnAmt);
		setValue(23, dmndTaxAmt);
		setValue(24, bldComsnAmt);
		setValue(25, bldTaxAmt);
	}
}
