/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.BrchrLineNrTypMtrx;


/**
 * Defines valid combinations of LINE_NR_TYP_ID and BRCHR_LINE_NR_GRP_ID with 
 * campaigns-before-reuse value
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrchrLineNrTypMtrxRecord extends UpdatableRecordImpl<BrchrLineNrTypMtrxRecord> implements Record9<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> {

	private static final long serialVersionUID = -1774831843;

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CLSTR_ID</code>.
	 */
	public void setClstrId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CLSTR_ID</code>.
	 */
	public BigDecimal getClstrId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.BILNG_SYS_GRP_LEAD_MRKT_ID</code>.
	 */
	public void setBilngSysGrpLeadMrktId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.BILNG_SYS_GRP_LEAD_MRKT_ID</code>.
	 */
	public BigDecimal getBilngSysGrpLeadMrktId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.LINE_NR_TYP_ID</code>.
	 */
	public void setLineNrTypId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.LINE_NR_TYP_ID</code>.
	 */
	public BigDecimal getLineNrTypId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.BRCHR_LINE_NR_GRP_ID</code>.
	 */
	public void setBrchrLineNrGrpId(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.BRCHR_LINE_NR_GRP_ID</code>.
	 */
	public BigDecimal getBrchrLineNrGrpId() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CMPGNS_BFR_REUS_NR</code>.
	 */
	public void setCmpgnsBfrReusNr(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CMPGNS_BFR_REUS_NR</code>.
	 */
	public BigDecimal getCmpgnsBfrReusNr() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CREAT_USER_ID</code>.
	 */
	public void setCreatUserId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CREAT_USER_ID</code>.
	 */
	public String getCreatUserId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CREAT_TS</code>.
	 */
	public void setCreatTs(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.CREAT_TS</code>.
	 */
	public Date getCreatTs() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.LAST_UPDT_USER_ID</code>.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.LAST_UPDT_USER_ID</code>.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.LAST_UPDT_TS</code>.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_TYP_MTRX.LAST_UPDT_TS</code>.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record4<BigDecimal, BigDecimal, BigDecimal, BigDecimal> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.CLSTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.BILNG_SYS_GRP_LEAD_MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.LINE_NR_TYP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.BRCHR_LINE_NR_GRP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.CMPGNS_BFR_REUS_NR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.CREAT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.CREAT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.LAST_UPDT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field9() {
		return BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX.LAST_UPDT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getClstrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getBilngSysGrpLeadMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getLineNrTypId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getBrchrLineNrGrpId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getCmpgnsBfrReusNr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCreatUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getCreatTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getLastUpdtUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value9() {
		return getLastUpdtTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value1(BigDecimal value) {
		setClstrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value2(BigDecimal value) {
		setBilngSysGrpLeadMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value3(BigDecimal value) {
		setLineNrTypId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value4(BigDecimal value) {
		setBrchrLineNrGrpId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value5(BigDecimal value) {
		setCmpgnsBfrReusNr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value6(String value) {
		setCreatUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value7(Date value) {
		setCreatTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value8(String value) {
		setLastUpdtUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord value9(Date value) {
		setLastUpdtTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrTypMtrxRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, String value6, Date value7, String value8, Date value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BrchrLineNrTypMtrxRecord
	 */
	public BrchrLineNrTypMtrxRecord() {
		super(BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX);
	}

	/**
	 * Create a detached, initialised BrchrLineNrTypMtrxRecord
	 */
	public BrchrLineNrTypMtrxRecord(BigDecimal clstrId, BigDecimal bilngSysGrpLeadMrktId, BigDecimal lineNrTypId, BigDecimal brchrLineNrGrpId, BigDecimal cmpgnsBfrReusNr, String creatUserId, Date creatTs, String lastUpdtUserId, Date lastUpdtTs) {
		super(BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX);

		setValue(0, clstrId);
		setValue(1, bilngSysGrpLeadMrktId);
		setValue(2, lineNrTypId);
		setValue(3, brchrLineNrGrpId);
		setValue(4, cmpgnsBfrReusNr);
		setValue(5, creatUserId);
		setValue(6, creatTs);
		setValue(7, lastUpdtUserId);
		setValue(8, lastUpdtTs);
	}
}
