/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;
import org.jooq.tables.BrchrLineNrUpd;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrchrLineNrUpdRecord extends TableRecordImpl<BrchrLineNrUpdRecord> implements Record16<BigDecimal, String, BigDecimal, String, BigDecimal, BigDecimal, String, BigDecimal, String, Date, String, Date, String, BigDecimal, String, BigDecimal> {

	private static final long serialVersionUID = -2015003868;

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.CLSTR_ID</code>.
	 */
	public void setClstrId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.CLSTR_ID</code>.
	 */
	public BigDecimal getClstrId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.LINE_NR</code>.
	 */
	public void setLineNr(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.LINE_NR</code>.
	 */
	public String getLineNr() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.LINE_NR_TYP_ID</code>.
	 */
	public void setLineNrTypId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.LINE_NR_TYP_ID</code>.
	 */
	public BigDecimal getLineNrTypId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.DFALT_ITEM_DESC_TXT</code>.
	 */
	public void setDfaltItemDescTxt(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.DFALT_ITEM_DESC_TXT</code>.
	 */
	public String getDfaltItemDescTxt() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.FRST_USED_PERD</code>.
	 */
	public void setFrstUsedPerd(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.FRST_USED_PERD</code>.
	 */
	public BigDecimal getFrstUsedPerd() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.LAST_USED_PERD</code>.
	 */
	public void setLastUsedPerd(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.LAST_USED_PERD</code>.
	 */
	public BigDecimal getLastUsedPerd() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.USED_IND</code>.
	 */
	public void setUsedInd(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.USED_IND</code>.
	 */
	public String getUsedInd() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.SKU_ID</code>.
	 */
	public void setSkuId(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.SKU_ID</code>.
	 */
	public BigDecimal getSkuId() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.CREAT_USER_ID</code>.
	 */
	public void setCreatUserId(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.CREAT_USER_ID</code>.
	 */
	public String getCreatUserId() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.CREAT_TS</code>.
	 */
	public void setCreatTs(Date value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.CREAT_TS</code>.
	 */
	public Date getCreatTs() {
		return (Date) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.LAST_UPDT_USER_ID</code>.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.LAST_UPDT_USER_ID</code>.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.LAST_UPDT_TS</code>.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.LAST_UPDT_TS</code>.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(11);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.MSTR_FSC_CD</code>.
	 */
	public void setMstrFscCd(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.MSTR_FSC_CD</code>.
	 */
	public String getMstrFscCd() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.BILNG_SYS_GRP_LEAD_MRKT_ID</code>.
	 */
	public void setBilngSysGrpLeadMrktId(BigDecimal value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.BILNG_SYS_GRP_LEAD_MRKT_ID</code>.
	 */
	public BigDecimal getBilngSysGrpLeadMrktId() {
		return (BigDecimal) getValue(13);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.CLSTR_LVL_IND</code>.
	 */
	public void setClstrLvlInd(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.CLSTR_LVL_IND</code>.
	 */
	public String getClstrLvlInd() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>WETRN.BRCHR_LINE_NR_UPD.LCL_BUS_ID</code>.
	 */
	public void setLclBusId(BigDecimal value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>WETRN.BRCHR_LINE_NR_UPD.LCL_BUS_ID</code>.
	 */
	public BigDecimal getLclBusId() {
		return (BigDecimal) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<BigDecimal, String, BigDecimal, String, BigDecimal, BigDecimal, String, BigDecimal, String, Date, String, Date, String, BigDecimal, String, BigDecimal> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<BigDecimal, String, BigDecimal, String, BigDecimal, BigDecimal, String, BigDecimal, String, Date, String, Date, String, BigDecimal, String, BigDecimal> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.CLSTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.LINE_NR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.LINE_NR_TYP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.DFALT_ITEM_DESC_TXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.FRST_USED_PERD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.LAST_USED_PERD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.USED_IND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field8() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.SKU_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.CREAT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field10() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.CREAT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.LAST_UPDT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field12() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.LAST_UPDT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.MSTR_FSC_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field14() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.BILNG_SYS_GRP_LEAD_MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.CLSTR_LVL_IND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field16() {
		return BrchrLineNrUpd.BRCHR_LINE_NR_UPD.LCL_BUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getClstrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLineNr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getLineNrTypId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDfaltItemDescTxt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getFrstUsedPerd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getLastUsedPerd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getUsedInd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value8() {
		return getSkuId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getCreatUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value10() {
		return getCreatTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getLastUpdtUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value12() {
		return getLastUpdtTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getMstrFscCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value14() {
		return getBilngSysGrpLeadMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getClstrLvlInd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value16() {
		return getLclBusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value1(BigDecimal value) {
		setClstrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value2(String value) {
		setLineNr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value3(BigDecimal value) {
		setLineNrTypId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value4(String value) {
		setDfaltItemDescTxt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value5(BigDecimal value) {
		setFrstUsedPerd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value6(BigDecimal value) {
		setLastUsedPerd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value7(String value) {
		setUsedInd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value8(BigDecimal value) {
		setSkuId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value9(String value) {
		setCreatUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value10(Date value) {
		setCreatTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value11(String value) {
		setLastUpdtUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value12(Date value) {
		setLastUpdtTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value13(String value) {
		setMstrFscCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value14(BigDecimal value) {
		setBilngSysGrpLeadMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value15(String value) {
		setClstrLvlInd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord value16(BigDecimal value) {
		setLclBusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BrchrLineNrUpdRecord values(BigDecimal value1, String value2, BigDecimal value3, String value4, BigDecimal value5, BigDecimal value6, String value7, BigDecimal value8, String value9, Date value10, String value11, Date value12, String value13, BigDecimal value14, String value15, BigDecimal value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BrchrLineNrUpdRecord
	 */
	public BrchrLineNrUpdRecord() {
		super(BrchrLineNrUpd.BRCHR_LINE_NR_UPD);
	}

	/**
	 * Create a detached, initialised BrchrLineNrUpdRecord
	 */
	public BrchrLineNrUpdRecord(BigDecimal clstrId, String lineNr, BigDecimal lineNrTypId, String dfaltItemDescTxt, BigDecimal frstUsedPerd, BigDecimal lastUsedPerd, String usedInd, BigDecimal skuId, String creatUserId, Date creatTs, String lastUpdtUserId, Date lastUpdtTs, String mstrFscCd, BigDecimal bilngSysGrpLeadMrktId, String clstrLvlInd, BigDecimal lclBusId) {
		super(BrchrLineNrUpd.BRCHR_LINE_NR_UPD);

		setValue(0, clstrId);
		setValue(1, lineNr);
		setValue(2, lineNrTypId);
		setValue(3, dfaltItemDescTxt);
		setValue(4, frstUsedPerd);
		setValue(5, lastUsedPerd);
		setValue(6, usedInd);
		setValue(7, skuId);
		setValue(8, creatUserId);
		setValue(9, creatTs);
		setValue(10, lastUpdtUserId);
		setValue(11, lastUpdtTs);
		setValue(12, mstrFscCd);
		setValue(13, bilngSysGrpLeadMrktId);
		setValue(14, clstrLvlInd);
		setValue(15, lclBusId);
	}
}
