/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;
import org.jooq.tables.ImpdpLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImpdpLogRecord extends TableRecordImpl<ImpdpLogRecord> implements Record1<String> {

	private static final long serialVersionUID = 663836278;

	/**
	 * Setter for <code>WETRN.IMPDP_LOG.TEXT</code>.
	 */
	public void setText(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.IMPDP_LOG.TEXT</code>.
	 */
	public String getText() {
		return (String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<String> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<String> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return ImpdpLog.IMPDP_LOG.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImpdpLogRecord value1(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImpdpLogRecord values(String value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ImpdpLogRecord
	 */
	public ImpdpLogRecord() {
		super(ImpdpLog.IMPDP_LOG);
	}

	/**
	 * Create a detached, initialised ImpdpLogRecord
	 */
	public ImpdpLogRecord(String text) {
		super(ImpdpLog.IMPDP_LOG);

		setValue(0, text);
	}
}
