/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;
import org.jooq.tables.IntrfcMrktFsc;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntrfcMrktFscRecord extends TableRecordImpl<IntrfcMrktFscRecord> implements Record7<BigDecimal, BigDecimal, BigDecimal, String, String, BigDecimal, BigDecimal> {

	private static final long serialVersionUID = -309274136;

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.MRKT_FSC_ID</code>.
	 */
	public void setMrktFscId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.MRKT_FSC_ID</code>.
	 */
	public BigDecimal getMrktFscId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.MRKTG_ITEM_ID</code>.
	 */
	public void setMrktgItemId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.MRKTG_ITEM_ID</code>.
	 */
	public BigDecimal getMrktgItemId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.FSC_CD</code>.
	 */
	public void setFscCd(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.FSC_CD</code>.
	 */
	public String getFscCd() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.FSC_DESC_TXT</code>.
	 */
	public void setFscDescTxt(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.FSC_DESC_TXT</code>.
	 */
	public String getFscDescTxt() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.PRMRY_PRFL_CD</code>.
	 */
	public void setPrmryPrflCd(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.PRMRY_PRFL_CD</code>.
	 */
	public BigDecimal getPrmryPrflCd() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.INTRFC_MRKT_FSC.CATGRY_ID</code>.
	 */
	public void setCatgryId(BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.INTRFC_MRKT_FSC.CATGRY_ID</code>.
	 */
	public BigDecimal getCatgryId() {
		return (BigDecimal) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<BigDecimal, BigDecimal, BigDecimal, String, String, BigDecimal, BigDecimal> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<BigDecimal, BigDecimal, BigDecimal, String, String, BigDecimal, BigDecimal> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.MRKT_FSC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.MRKTG_ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.FSC_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.FSC_DESC_TXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.PRMRY_PRFL_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field7() {
		return IntrfcMrktFsc.INTRFC_MRKT_FSC.CATGRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getMrktFscId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getMrktgItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getFscCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getFscDescTxt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getPrmryPrflCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value7() {
		return getCatgryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value1(BigDecimal value) {
		setMrktFscId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value2(BigDecimal value) {
		setMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value3(BigDecimal value) {
		setMrktgItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value4(String value) {
		setFscCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value5(String value) {
		setFscDescTxt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value6(BigDecimal value) {
		setPrmryPrflCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord value7(BigDecimal value) {
		setCatgryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntrfcMrktFscRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, String value4, String value5, BigDecimal value6, BigDecimal value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IntrfcMrktFscRecord
	 */
	public IntrfcMrktFscRecord() {
		super(IntrfcMrktFsc.INTRFC_MRKT_FSC);
	}

	/**
	 * Create a detached, initialised IntrfcMrktFscRecord
	 */
	public IntrfcMrktFscRecord(BigDecimal mrktFscId, BigDecimal mrktId, BigDecimal mrktgItemId, String fscCd, String fscDescTxt, BigDecimal prmryPrflCd, BigDecimal catgryId) {
		super(IntrfcMrktFsc.INTRFC_MRKT_FSC);

		setValue(0, mrktFscId);
		setValue(1, mrktId);
		setValue(2, mrktgItemId);
		setValue(3, fscCd);
		setValue(4, fscDescTxt);
		setValue(5, prmryPrflCd);
		setValue(6, catgryId);
	}
}
