/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.MessageTransactionRow;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageTransactionRowRecord extends UpdatableRecordImpl<MessageTransactionRowRecord> {

	private static final long serialVersionUID = 2126055126;

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.MESSAGE_TRANSACTION_ROW_ID</code>.
	 */
	public void setMessageTransactionRowId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.MESSAGE_TRANSACTION_ROW_ID</code>.
	 */
	public Long getMessageTransactionRowId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.TABLE_NAME</code>.
	 */
	public void setTableName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.TABLE_NAME</code>.
	 */
	public String getTableName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.MESSAGE_TRANSACTION_ID</code>.
	 */
	public void setMessageTransactionId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.MESSAGE_TRANSACTION_ID</code>.
	 */
	public Long getMessageTransactionId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY1</code>.
	 */
	public void setPrimaryKey1(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY1</code>.
	 */
	public String getPrimaryKey1() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY2</code>.
	 */
	public void setPrimaryKey2(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY2</code>.
	 */
	public String getPrimaryKey2() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY3</code>.
	 */
	public void setPrimaryKey3(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY3</code>.
	 */
	public String getPrimaryKey3() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY4</code>.
	 */
	public void setPrimaryKey4(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY4</code>.
	 */
	public String getPrimaryKey4() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY5</code>.
	 */
	public void setPrimaryKey5(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY5</code>.
	 */
	public String getPrimaryKey5() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY6</code>.
	 */
	public void setPrimaryKey6(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY6</code>.
	 */
	public String getPrimaryKey6() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY7</code>.
	 */
	public void setPrimaryKey7(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY7</code>.
	 */
	public String getPrimaryKey7() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY8</code>.
	 */
	public void setPrimaryKey8(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY8</code>.
	 */
	public String getPrimaryKey8() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY9</code>.
	 */
	public void setPrimaryKey9(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY9</code>.
	 */
	public String getPrimaryKey9() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY10</code>.
	 */
	public void setPrimaryKey10(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY10</code>.
	 */
	public String getPrimaryKey10() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY11</code>.
	 */
	public void setPrimaryKey11(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY11</code>.
	 */
	public String getPrimaryKey11() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY12</code>.
	 */
	public void setPrimaryKey12(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY12</code>.
	 */
	public String getPrimaryKey12() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY13</code>.
	 */
	public void setPrimaryKey13(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY13</code>.
	 */
	public String getPrimaryKey13() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY14</code>.
	 */
	public void setPrimaryKey14(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY14</code>.
	 */
	public String getPrimaryKey14() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY15</code>.
	 */
	public void setPrimaryKey15(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY15</code>.
	 */
	public String getPrimaryKey15() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY16</code>.
	 */
	public void setPrimaryKey16(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY16</code>.
	 */
	public String getPrimaryKey16() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY17</code>.
	 */
	public void setPrimaryKey17(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY17</code>.
	 */
	public String getPrimaryKey17() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY18</code>.
	 */
	public void setPrimaryKey18(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY18</code>.
	 */
	public String getPrimaryKey18() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY19</code>.
	 */
	public void setPrimaryKey19(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY19</code>.
	 */
	public String getPrimaryKey19() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY20</code>.
	 */
	public void setPrimaryKey20(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>WETRN.MESSAGE_TRANSACTION_ROW.PRIMARY_KEY20</code>.
	 */
	public String getPrimaryKey20() {
		return (String) getValue(22);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessageTransactionRowRecord
	 */
	public MessageTransactionRowRecord() {
		super(MessageTransactionRow.MESSAGE_TRANSACTION_ROW);
	}

	/**
	 * Create a detached, initialised MessageTransactionRowRecord
	 */
	public MessageTransactionRowRecord(Long messageTransactionRowId, String tableName, Long messageTransactionId, String primaryKey1, String primaryKey2, String primaryKey3, String primaryKey4, String primaryKey5, String primaryKey6, String primaryKey7, String primaryKey8, String primaryKey9, String primaryKey10, String primaryKey11, String primaryKey12, String primaryKey13, String primaryKey14, String primaryKey15, String primaryKey16, String primaryKey17, String primaryKey18, String primaryKey19, String primaryKey20) {
		super(MessageTransactionRow.MESSAGE_TRANSACTION_ROW);

		setValue(0, messageTransactionRowId);
		setValue(1, tableName);
		setValue(2, messageTransactionId);
		setValue(3, primaryKey1);
		setValue(4, primaryKey2);
		setValue(5, primaryKey3);
		setValue(6, primaryKey4);
		setValue(7, primaryKey5);
		setValue(8, primaryKey6);
		setValue(9, primaryKey7);
		setValue(10, primaryKey8);
		setValue(11, primaryKey9);
		setValue(12, primaryKey10);
		setValue(13, primaryKey11);
		setValue(14, primaryKey12);
		setValue(15, primaryKey13);
		setValue(16, primaryKey14);
		setValue(17, primaryKey15);
		setValue(18, primaryKey16);
		setValue(19, primaryKey17);
		setValue(20, primaryKey18);
		setValue(21, primaryKey19);
		setValue(22, primaryKey20);
	}
}
