/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.MrktSkuUnitSpltPct;


/**
 * Market sku unit split percent.  Unit split percentage for market sku.  
 * Rows are inserted when there is a new split percentage for items effective 
 * from a specific offer period.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MrktSkuUnitSpltPctRecord extends UpdatableRecordImpl<MrktSkuUnitSpltPctRecord> implements Record8<BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> {

	private static final long serialVersionUID = -155468079;

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.SKU_ID</code>.
	 */
	public void setSkuId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.SKU_ID</code>.
	 */
	public BigDecimal getSkuId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.EFF_OFFR_PERD_ID</code>.
	 */
	public void setEffOffrPerdId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.EFF_OFFR_PERD_ID</code>.
	 */
	public BigDecimal getEffOffrPerdId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.STATC_UNIT_SPLT_PCT</code>. Static unit split percent.  The unit split percentage for this item.  The total of split percentages for all items within a profile should add up to 100 but may not do if items have been deleted or have changed profile.
	 */
	public void setStatcUnitSpltPct(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.STATC_UNIT_SPLT_PCT</code>. Static unit split percent.  The unit split percentage for this item.  The total of split percentages for all items within a profile should add up to 100 but may not do if items have been deleted or have changed profile.
	 */
	public BigDecimal getStatcUnitSpltPct() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.CREAT_USER_ID</code>. The MAPS Application USER ID of the user (person or process) that created the row.
	 */
	public void setCreatUserId(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.CREAT_USER_ID</code>. The MAPS Application USER ID of the user (person or process) that created the row.
	 */
	public String getCreatUserId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.CREAT_TS</code>. The date and time the row was created.
	 */
	public void setCreatTs(Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.CREAT_TS</code>. The date and time the row was created.
	 */
	public Date getCreatTs() {
		return (Date) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.LAST_UPDT_USER_ID</code>. Contains the MAPS USER ID of the user (person or process) that last updated the row.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.LAST_UPDT_USER_ID</code>. Contains the MAPS USER ID of the user (person or process) that last updated the row.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.LAST_UPDT_TS</code>. The date and time the row was last updated.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.MRKT_SKU_UNIT_SPLT_PCT.LAST_UPDT_TS</code>. The date and time the row was last updated.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<BigDecimal, BigDecimal, BigDecimal> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.SKU_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.EFF_OFFR_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.STATC_UNIT_SPLT_PCT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.CREAT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field6() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.CREAT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.LAST_UPDT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field8() {
		return MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT.LAST_UPDT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getSkuId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getEffOffrPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getStatcUnitSpltPct();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getCreatUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value6() {
		return getCreatTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getLastUpdtUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value8() {
		return getLastUpdtTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value1(BigDecimal value) {
		setMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value2(BigDecimal value) {
		setSkuId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value3(BigDecimal value) {
		setEffOffrPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value4(BigDecimal value) {
		setStatcUnitSpltPct(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value5(String value) {
		setCreatUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value6(Date value) {
		setCreatTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value7(String value) {
		setLastUpdtUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord value8(Date value) {
		setLastUpdtTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktSkuUnitSpltPctRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, String value5, Date value6, String value7, Date value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MrktSkuUnitSpltPctRecord
	 */
	public MrktSkuUnitSpltPctRecord() {
		super(MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT);
	}

	/**
	 * Create a detached, initialised MrktSkuUnitSpltPctRecord
	 */
	public MrktSkuUnitSpltPctRecord(BigDecimal mrktId, BigDecimal skuId, BigDecimal effOffrPerdId, BigDecimal statcUnitSpltPct, String creatUserId, Date creatTs, String lastUpdtUserId, Date lastUpdtTs) {
		super(MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT);

		setValue(0, mrktId);
		setValue(1, skuId);
		setValue(2, effOffrPerdId);
		setValue(3, statcUnitSpltPct);
		setValue(4, creatUserId);
		setValue(5, creatTs);
		setValue(6, lastUpdtUserId);
		setValue(7, lastUpdtTs);
	}
}
