/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.OffrSkuLine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OffrSkuLineRecord extends UpdatableRecordImpl<OffrSkuLineRecord> {

	private static final long serialVersionUID = -195804118;

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.OFFR_SKU_LINE_ID</code>.
	 */
	public void setOffrSkuLineId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.OFFR_SKU_LINE_ID</code>.
	 */
	public BigDecimal getOffrSkuLineId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.OFFR_ID</code>.
	 */
	public void setOffrId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.OFFR_ID</code>.
	 */
	public BigDecimal getOffrId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.VEH_ID</code>.
	 */
	public void setVehId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.VEH_ID</code>.
	 */
	public BigDecimal getVehId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.FEATRD_SIDE_CD</code>.
	 */
	public void setFeatrdSideCd(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.FEATRD_SIDE_CD</code>.
	 */
	public String getFeatrdSideCd() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.OFFR_PERD_ID</code>.
	 */
	public void setOffrPerdId(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.OFFR_PERD_ID</code>.
	 */
	public BigDecimal getOffrPerdId() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.SKU_ID</code>.
	 */
	public void setSkuId(BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.SKU_ID</code>.
	 */
	public BigDecimal getSkuId() {
		return (BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.PG_OFS_NR</code>.
	 */
	public void setPgOfsNr(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.PG_OFS_NR</code>.
	 */
	public BigDecimal getPgOfsNr() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.PRFL_CD</code>.
	 */
	public void setPrflCd(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.PRFL_CD</code>.
	 */
	public Integer getPrflCd() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.CRNCY_CD</code>.
	 */
	public void setCrncyCd(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.CRNCY_CD</code>.
	 */
	public String getCrncyCd() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.PRMRY_SKU_OFFR_IND</code>.
	 */
	public void setPrmrySkuOffrInd(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.PRMRY_SKU_OFFR_IND</code>.
	 */
	public String getPrmrySkuOffrInd() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.SLS_CLS_CD</code>.
	 */
	public void setSlsClsCd(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.SLS_CLS_CD</code>.
	 */
	public String getSlsClsCd() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.OFFR_PRFL_PRCPT_ID</code>.
	 */
	public void setOffrPrflPrcptId(BigDecimal value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.OFFR_PRFL_PRCPT_ID</code>.
	 */
	public BigDecimal getOffrPrflPrcptId() {
		return (BigDecimal) getValue(12);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.PROMTN_DESC_TXT</code>.
	 */
	public void setPromtnDescTxt(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.PROMTN_DESC_TXT</code>.
	 */
	public String getPromtnDescTxt() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.DEMO_AVLBL_IND</code>.
	 */
	public void setDemoAvlblInd(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.DEMO_AVLBL_IND</code>.
	 */
	public String getDemoAvlblInd() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.DLTD_IND</code>.
	 */
	public void setDltdInd(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.DLTD_IND</code>.
	 */
	public String getDltdInd() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.UNIT_SPLT_PCT</code>.
	 */
	public void setUnitSpltPct(BigDecimal value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.UNIT_SPLT_PCT</code>.
	 */
	public BigDecimal getUnitSpltPct() {
		return (BigDecimal) getValue(16);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.CREAT_USER_ID</code>.
	 */
	public void setCreatUserId(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.CREAT_USER_ID</code>.
	 */
	public String getCreatUserId() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.SLS_PRC_AMT</code>.
	 */
	public void setSlsPrcAmt(BigDecimal value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.SLS_PRC_AMT</code>.
	 */
	public BigDecimal getSlsPrcAmt() {
		return (BigDecimal) getValue(18);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.CREAT_TS</code>.
	 */
	public void setCreatTs(Date value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.CREAT_TS</code>.
	 */
	public Date getCreatTs() {
		return (Date) getValue(19);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.LAST_UPDT_USER_ID</code>.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.LAST_UPDT_USER_ID</code>.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.LAST_UPDT_TS</code>.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.LAST_UPDT_TS</code>.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(21);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.COST_TYP</code>.
	 */
	public void setCostTyp(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.COST_TYP</code>.
	 */
	public String getCostTyp() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.OFFR_SKU_LINE_LINK_ID</code>.
	 */
	public void setOffrSkuLineLinkId(BigDecimal value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.OFFR_SKU_LINE_LINK_ID</code>.
	 */
	public BigDecimal getOffrSkuLineLinkId() {
		return (BigDecimal) getValue(23);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.SET_CMPNT_IND</code>.
	 */
	public void setSetCmpntInd(String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.SET_CMPNT_IND</code>.
	 */
	public String getSetCmpntInd() {
		return (String) getValue(24);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.SET_CMPNT_QTY</code>.
	 */
	public void setSetCmpntQty(Integer value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.SET_CMPNT_QTY</code>.
	 */
	public Integer getSetCmpntQty() {
		return (Integer) getValue(25);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.OFFR_SKU_SET_ID</code>.
	 */
	public void setOffrSkuSetId(BigDecimal value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.OFFR_SKU_SET_ID</code>.
	 */
	public BigDecimal getOffrSkuSetId() {
		return (BigDecimal) getValue(26);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.LINE_NR</code>.
	 */
	public void setLineNr(String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.LINE_NR</code>.
	 */
	public String getLineNr() {
		return (String) getValue(27);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.UNIT_PRC_AMT</code>.
	 */
	public void setUnitPrcAmt(BigDecimal value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.UNIT_PRC_AMT</code>.
	 */
	public BigDecimal getUnitPrcAmt() {
		return (BigDecimal) getValue(28);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.LINE_NR_TYP_ID</code>.
	 */
	public void setLineNrTypId(BigDecimal value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.LINE_NR_TYP_ID</code>.
	 */
	public BigDecimal getLineNrTypId() {
		return (BigDecimal) getValue(29);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.FINSHD_GDS_CD</code>.
	 */
	public void setFinshdGdsCd(BigDecimal value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.FINSHD_GDS_CD</code>.
	 */
	public BigDecimal getFinshdGdsCd() {
		return (BigDecimal) getValue(30);
	}

	/**
	 * Setter for <code>WETRN.OFFR_SKU_LINE.LINE_NR_ASGNMT_TYP_ID</code>.
	 */
	public void setLineNrAsgnmtTypId(BigDecimal value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>WETRN.OFFR_SKU_LINE.LINE_NR_ASGNMT_TYP_ID</code>.
	 */
	public BigDecimal getLineNrAsgnmtTypId() {
		return (BigDecimal) getValue(31);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<BigDecimal> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OffrSkuLineRecord
	 */
	public OffrSkuLineRecord() {
		super(OffrSkuLine.OFFR_SKU_LINE);
	}

	/**
	 * Create a detached, initialised OffrSkuLineRecord
	 */
	public OffrSkuLineRecord(BigDecimal offrSkuLineId, BigDecimal offrId, BigDecimal vehId, String featrdSideCd, BigDecimal offrPerdId, BigDecimal mrktId, BigDecimal skuId, BigDecimal pgOfsNr, Integer prflCd, String crncyCd, String prmrySkuOffrInd, String slsClsCd, BigDecimal offrPrflPrcptId, String promtnDescTxt, String demoAvlblInd, String dltdInd, BigDecimal unitSpltPct, String creatUserId, BigDecimal slsPrcAmt, Date creatTs, String lastUpdtUserId, Date lastUpdtTs, String costTyp, BigDecimal offrSkuLineLinkId, String setCmpntInd, Integer setCmpntQty, BigDecimal offrSkuSetId, String lineNr, BigDecimal unitPrcAmt, BigDecimal lineNrTypId, BigDecimal finshdGdsCd, BigDecimal lineNrAsgnmtTypId) {
		super(OffrSkuLine.OFFR_SKU_LINE);

		setValue(0, offrSkuLineId);
		setValue(1, offrId);
		setValue(2, vehId);
		setValue(3, featrdSideCd);
		setValue(4, offrPerdId);
		setValue(5, mrktId);
		setValue(6, skuId);
		setValue(7, pgOfsNr);
		setValue(8, prflCd);
		setValue(9, crncyCd);
		setValue(10, prmrySkuOffrInd);
		setValue(11, slsClsCd);
		setValue(12, offrPrflPrcptId);
		setValue(13, promtnDescTxt);
		setValue(14, demoAvlblInd);
		setValue(15, dltdInd);
		setValue(16, unitSpltPct);
		setValue(17, creatUserId);
		setValue(18, slsPrcAmt);
		setValue(19, creatTs);
		setValue(20, lastUpdtUserId);
		setValue(21, lastUpdtTs);
		setValue(22, costTyp);
		setValue(23, offrSkuLineLinkId);
		setValue(24, setCmpntInd);
		setValue(25, setCmpntQty);
		setValue(26, offrSkuSetId);
		setValue(27, lineNr);
		setValue(28, unitPrcAmt);
		setValue(29, lineNrTypId);
		setValue(30, finshdGdsCd);
		setValue(31, lineNrAsgnmtTypId);
	}
}
