/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Record8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.PrsnlFinclObjctv;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrsnlFinclObjctvRecord extends UpdatableRecordImpl<PrsnlFinclObjctvRecord> {

	private static final long serialVersionUID = 983429094;

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.OFFR_PERD_ID</code>.
	 */
	public void setOffrPerdId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.OFFR_PERD_ID</code>.
	 */
	public BigDecimal getOffrPerdId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.OBJCTV_ID</code>.
	 */
	public void setObjctvId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.OBJCTV_ID</code>.
	 */
	public BigDecimal getObjctvId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CLSTR_ID</code>.
	 */
	public void setClstrId(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CLSTR_ID</code>.
	 */
	public BigDecimal getClstrId() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.USER_NM</code>.
	 */
	public void setUserNm(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.USER_NM</code>.
	 */
	public String getUserNm() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.PRSNL_VER_ID</code>.
	 */
	public void setPrsnlVerId(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.PRSNL_VER_ID</code>.
	 */
	public BigDecimal getPrsnlVerId() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.OBJCTV_TYP</code>.
	 */
	public void setObjctvTyp(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.OBJCTV_TYP</code>.
	 */
	public String getObjctvTyp() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.ACTV_REP_CNT</code>.
	 */
	public void setActvRepCnt(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.ACTV_REP_CNT</code>.
	 */
	public BigDecimal getActvRepCnt() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.SYS_ID</code>.
	 */
	public void setSysId(BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.SYS_ID</code>.
	 */
	public BigDecimal getSysId() {
		return (BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.ACTV_SKU_CNT</code>.
	 */
	public void setActvSkuCnt(BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.ACTV_SKU_CNT</code>.
	 */
	public BigDecimal getActvSkuCnt() {
		return (BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_ACTVTY_PCT</code>.
	 */
	public void setRepActvtyPct(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_ACTVTY_PCT</code>.
	 */
	public BigDecimal getRepActvtyPct() {
		return (BigDecimal) getValue(10);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.ADVRTSG_BDGT_AMT</code>.
	 */
	public void setAdvrtsgBdgtAmt(BigDecimal value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.ADVRTSG_BDGT_AMT</code>.
	 */
	public BigDecimal getAdvrtsgBdgtAmt() {
		return (BigDecimal) getValue(11);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.VEH_PG_CNT</code>.
	 */
	public void setVehPgCnt(BigDecimal value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.VEH_PG_CNT</code>.
	 */
	public BigDecimal getVehPgCnt() {
		return (BigDecimal) getValue(12);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.VEH_BDGT_AMT</code>.
	 */
	public void setVehBdgtAmt(BigDecimal value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.VEH_BDGT_AMT</code>.
	 */
	public BigDecimal getVehBdgtAmt() {
		return (BigDecimal) getValue(13);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CMPETTN_PRZE_BDGT_AMT</code>.
	 */
	public void setCmpettnPrzeBdgtAmt(BigDecimal value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CMPETTN_PRZE_BDGT_AMT</code>.
	 */
	public BigDecimal getCmpettnPrzeBdgtAmt() {
		return (BigDecimal) getValue(14);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CNSMR_INCNTV_BDGT_AMT</code>.
	 */
	public void setCnsmrIncntvBdgtAmt(BigDecimal value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CNSMR_INCNTV_BDGT_AMT</code>.
	 */
	public BigDecimal getCnsmrIncntvBdgtAmt() {
		return (BigDecimal) getValue(15);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CPI_INFLTN_PCT</code>.
	 */
	public void setCpiInfltnPct(BigDecimal value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CPI_INFLTN_PCT</code>.
	 */
	public BigDecimal getCpiInfltnPct() {
		return (BigDecimal) getValue(16);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SERVC_CNT</code>.
	 */
	public void setCustServcCnt(BigDecimal value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SERVC_CNT</code>.
	 */
	public BigDecimal getCustServcCnt() {
		return (BigDecimal) getValue(17);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.DSCNTND_SKU_CNT</code>.
	 */
	public void setDscntndSkuCnt(BigDecimal value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.DSCNTND_SKU_CNT</code>.
	 */
	public BigDecimal getDscntndSkuCnt() {
		return (BigDecimal) getValue(18);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.GIFT_WITH_PRCHS_BDGT_AMT</code>.
	 */
	public void setGiftWithPrchsBdgtAmt(BigDecimal value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.GIFT_WITH_PRCHS_BDGT_AMT</code>.
	 */
	public BigDecimal getGiftWithPrchsBdgtAmt() {
		return (BigDecimal) getValue(19);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.INCNTV_VEH_BDGT_AMT</code>.
	 */
	public void setIncntvVehBdgtAmt(BigDecimal value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.INCNTV_VEH_BDGT_AMT</code>.
	 */
	public BigDecimal getIncntvVehBdgtAmt() {
		return (BigDecimal) getValue(20);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.MRKT_SHR_PCT</code>.
	 */
	public void setMrktShrPct(BigDecimal value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.MRKT_SHR_PCT</code>.
	 */
	public BigDecimal getMrktShrPct() {
		return (BigDecimal) getValue(21);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.MICR_NCPSLTN_PG_CNT</code>.
	 */
	public void setMicrNcpsltnPgCnt(BigDecimal value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.MICR_NCPSLTN_PG_CNT</code>.
	 */
	public BigDecimal getMicrNcpsltnPgCnt() {
		return (BigDecimal) getValue(22);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.MICR_NCPSLTN_BDGT_AMT</code>.
	 */
	public void setMicrNcpsltnBdgtAmt(BigDecimal value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.MICR_NCPSLTN_BDGT_AMT</code>.
	 */
	public BigDecimal getMicrNcpsltnBdgtAmt() {
		return (BigDecimal) getValue(23);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.NEW_CNCPT_CNT</code>.
	 */
	public void setNewCncptCnt(BigDecimal value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.NEW_CNCPT_CNT</code>.
	 */
	public BigDecimal getNewCncptCnt() {
		return (BigDecimal) getValue(24);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.NEW_SKU_CNT</code>.
	 */
	public void setNewSkuCnt(BigDecimal value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.NEW_SKU_CNT</code>.
	 */
	public BigDecimal getNewSkuCnt() {
		return (BigDecimal) getValue(25);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_CNT</code>.
	 */
	public void setCustCnt(BigDecimal value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_CNT</code>.
	 */
	public BigDecimal getCustCnt() {
		return (BigDecimal) getValue(26);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.ORD_CNT</code>.
	 */
	public void setOrdCnt(BigDecimal value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.ORD_CNT</code>.
	 */
	public BigDecimal getOrdCnt() {
		return (BigDecimal) getValue(27);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.OTHR_BDGT_AMT</code>.
	 */
	public void setOthrBdgtAmt(BigDecimal value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.OTHR_BDGT_AMT</code>.
	 */
	public BigDecimal getOthrBdgtAmt() {
		return (BigDecimal) getValue(28);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.PBLC_RLTNS_BDGT_AMT</code>.
	 */
	public void setPblcRltnsBdgtAmt(BigDecimal value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.PBLC_RLTNS_BDGT_AMT</code>.
	 */
	public BigDecimal getPblcRltnsBdgtAmt() {
		return (BigDecimal) getValue(29);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.PROD_INCNTV_BDGT_AMT</code>.
	 */
	public void setProdIncntvBdgtAmt(BigDecimal value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.PROD_INCNTV_BDGT_AMT</code>.
	 */
	public BigDecimal getProdIncntvBdgtAmt() {
		return (BigDecimal) getValue(30);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.FLD_INCNTV_BDGT_AMT</code>.
	 */
	public void setFldIncntvBdgtAmt(BigDecimal value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.FLD_INCNTV_BDGT_AMT</code>.
	 */
	public BigDecimal getFldIncntvBdgtAmt() {
		return (BigDecimal) getValue(31);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.SMPLG_BDGT_AMT</code>.
	 */
	public void setSmplgBdgtAmt(BigDecimal value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.SMPLG_BDGT_AMT</code>.
	 */
	public BigDecimal getSmplgBdgtAmt() {
		return (BigDecimal) getValue(32);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.RTURN_SLS_PCT</code>.
	 */
	public void setRturnSlsPct(BigDecimal value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.RTURN_SLS_PCT</code>.
	 */
	public BigDecimal getRturnSlsPct() {
		return (BigDecimal) getValue(33);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CREAT_USER_ID</code>.
	 */
	public void setCreatUserId(String value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CREAT_USER_ID</code>.
	 */
	public String getCreatUserId() {
		return (String) getValue(34);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CREAT_TS</code>.
	 */
	public void setCreatTs(Date value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CREAT_TS</code>.
	 */
	public Date getCreatTs() {
		return (Date) getValue(35);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.LAST_UPDT_USER_ID</code>.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(36, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.LAST_UPDT_USER_ID</code>.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(36);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.LAST_UPDT_TS</code>.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(37, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.LAST_UPDT_TS</code>.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(37);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.BRCHR_PG_CNT</code>.
	 */
	public void setBrchrPgCnt(Integer value) {
		setValue(38, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.BRCHR_PG_CNT</code>.
	 */
	public Integer getBrchrPgCnt() {
		return (Integer) getValue(38);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_UNITS_PER_REP_QTY</code>.
	 */
	public void setCustUnitsPerRepQty(BigDecimal value) {
		setValue(39, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_UNITS_PER_REP_QTY</code>.
	 */
	public BigDecimal getCustUnitsPerRepQty() {
		return (BigDecimal) getValue(39);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_UNITS_PER_ORD_QTY</code>.
	 */
	public void setCustUnitsPerOrdQty(BigDecimal value) {
		setValue(40, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_UNITS_PER_ORD_QTY</code>.
	 */
	public BigDecimal getCustUnitsPerOrdQty() {
		return (BigDecimal) getValue(40);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_CNT</code>.
	 */
	public void setRepCnt(BigDecimal value) {
		setValue(41, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_CNT</code>.
	 */
	public BigDecimal getRepCnt() {
		return (BigDecimal) getValue(41);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_BRCHR_SLS_AMT</code>.
	 */
	public void setTotBrchrSlsAmt(BigDecimal value) {
		setValue(42, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_BRCHR_SLS_AMT</code>.
	 */
	public BigDecimal getTotBrchrSlsAmt() {
		return (BigDecimal) getValue(42);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_CUST_SLS_AMT</code>.
	 */
	public void setTotCustSlsAmt(BigDecimal value) {
		setValue(43, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_CUST_SLS_AMT</code>.
	 */
	public BigDecimal getTotCustSlsAmt() {
		return (BigDecimal) getValue(43);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_REP_SLS_AMT</code>.
	 */
	public void setTotRepSlsAmt(BigDecimal value) {
		setValue(44, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_REP_SLS_AMT</code>.
	 */
	public BigDecimal getTotRepSlsAmt() {
		return (BigDecimal) getValue(44);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_ADJSTMT_AMT</code>.
	 */
	public void setTotAdjstmtAmt(BigDecimal value) {
		setValue(45, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_ADJSTMT_AMT</code>.
	 */
	public BigDecimal getTotAdjstmtAmt() {
		return (BigDecimal) getValue(45);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.GRS_SLS_AMT</code>.
	 */
	public void setGrsSlsAmt(BigDecimal value) {
		setValue(46, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.GRS_SLS_AMT</code>.
	 */
	public BigDecimal getGrsSlsAmt() {
		return (BigDecimal) getValue(46);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.SLS_AIDS_AMT</code>.
	 */
	public void setSlsAidsAmt(BigDecimal value) {
		setValue(47, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.SLS_AIDS_AMT</code>.
	 */
	public BigDecimal getSlsAidsAmt() {
		return (BigDecimal) getValue(47);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.BLLD_SLS_AMT</code>.
	 */
	public void setBlldSlsAmt(BigDecimal value) {
		setValue(48, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.BLLD_SLS_AMT</code>.
	 */
	public BigDecimal getBlldSlsAmt() {
		return (BigDecimal) getValue(48);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.RTURN_SLS_AMT</code>.
	 */
	public void setRturnSlsAmt(BigDecimal value) {
		setValue(49, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.RTURN_SLS_AMT</code>.
	 */
	public BigDecimal getRturnSlsAmt() {
		return (BigDecimal) getValue(49);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.NET_SLS_AMT</code>.
	 */
	public void setNetSlsAmt(BigDecimal value) {
		setValue(50, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.NET_SLS_AMT</code>.
	 */
	public BigDecimal getNetSlsAmt() {
		return (BigDecimal) getValue(50);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_SOL_QTY</code>.
	 */
	public void setTotSolQty(Integer value) {
		setValue(51, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_SOL_QTY</code>.
	 */
	public Integer getTotSolQty() {
		return (Integer) getValue(51);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_BDGT_AMT</code>.
	 */
	public void setTotBdgtAmt(BigDecimal value) {
		setValue(52, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.TOT_BDGT_AMT</code>.
	 */
	public BigDecimal getTotBdgtAmt() {
		return (BigDecimal) getValue(52);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.ACTVTY_PCT</code>.
	 */
	public void setActvtyPct(BigDecimal value) {
		setValue(53, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.ACTVTY_PCT</code>.
	 */
	public BigDecimal getActvtyPct() {
		return (BigDecimal) getValue(53);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.AVG_ORD_GRS_SLS_AMT</code>.
	 */
	public void setAvgOrdGrsSlsAmt(BigDecimal value) {
		setValue(54, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.AVG_ORD_GRS_SLS_AMT</code>.
	 */
	public BigDecimal getAvgOrdGrsSlsAmt() {
		return (BigDecimal) getValue(54);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_SPND_GRS_SLS_AMT</code>.
	 */
	public void setRepSpndGrsSlsAmt(BigDecimal value) {
		setValue(55, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_SPND_GRS_SLS_AMT</code>.
	 */
	public BigDecimal getRepSpndGrsSlsAmt() {
		return (BigDecimal) getValue(55);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.AVG_ORD_BILLD_SLS_AMT</code>.
	 */
	public void setAvgOrdBilldSlsAmt(BigDecimal value) {
		setValue(56, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.AVG_ORD_BILLD_SLS_AMT</code>.
	 */
	public BigDecimal getAvgOrdBilldSlsAmt() {
		return (BigDecimal) getValue(56);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_SPND_BILLD_SLS_AMT</code>.
	 */
	public void setRepSpndBilldSlsAmt(BigDecimal value) {
		setValue(57, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.REP_SPND_BILLD_SLS_AMT</code>.
	 */
	public BigDecimal getRepSpndBilldSlsAmt() {
		return (BigDecimal) getValue(57);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SERVC_QTY</code>.
	 */
	public void setCustServcQty(Integer value) {
		setValue(58, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SERVC_QTY</code>.
	 */
	public Integer getCustServcQty() {
		return (Integer) getValue(58);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SPND_AMT</code>.
	 */
	public void setCustSpndAmt(BigDecimal value) {
		setValue(59, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SPND_AMT</code>.
	 */
	public BigDecimal getCustSpndAmt() {
		return (BigDecimal) getValue(59);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SLS_PER_UNIT_AMT</code>.
	 */
	public void setCustSlsPerUnitAmt(BigDecimal value) {
		setValue(60, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.CUST_SLS_PER_UNIT_AMT</code>.
	 */
	public BigDecimal getCustSlsPerUnitAmt() {
		return (BigDecimal) getValue(60);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.GRS_SLS_PER_UNIT_AMT</code>.
	 */
	public void setGrsSlsPerUnitAmt(BigDecimal value) {
		setValue(61, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.GRS_SLS_PER_UNIT_AMT</code>.
	 */
	public BigDecimal getGrsSlsPerUnitAmt() {
		return (BigDecimal) getValue(61);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.PER_CUST_UNIT_QTY</code>.
	 */
	public void setPerCustUnitQty(Integer value) {
		setValue(62, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.PER_CUST_UNIT_QTY</code>.
	 */
	public Integer getPerCustUnitQty() {
		return (Integer) getValue(62);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.AVG_CMPGN_CUST_SLS_AMT</code>.
	 */
	public void setAvgCmpgnCustSlsAmt(BigDecimal value) {
		setValue(63, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.AVG_CMPGN_CUST_SLS_AMT</code>.
	 */
	public BigDecimal getAvgCmpgnCustSlsAmt() {
		return (BigDecimal) getValue(63);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.RSRCH_BDGT_AMT</code>.
	 */
	public void setRsrchBdgtAmt(BigDecimal value) {
		setValue(64, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.RSRCH_BDGT_AMT</code>.
	 */
	public BigDecimal getRsrchBdgtAmt() {
		return (BigDecimal) getValue(64);
	}

	/**
	 * Setter for <code>WETRN.PRSNL_FINCL_OBJCTV.APPT_CNT</code>. APPOINTMENT COUNT - Number of prospects officially named as Avon Representative though a signed contract (and any locally required registration) but hasn't necessarily submitted an order.
	 */
	public void setApptCnt(Long value) {
		setValue(65, value);
	}

	/**
	 * Getter for <code>WETRN.PRSNL_FINCL_OBJCTV.APPT_CNT</code>. APPOINTMENT COUNT - Number of prospects officially named as Avon Representative though a signed contract (and any locally required registration) but hasn't necessarily submitted an order.
	 */
	public Long getApptCnt() {
		return (Long) getValue(65);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record8<BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, String, BigDecimal> key() {
		return (Record8) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrsnlFinclObjctvRecord
	 */
	public PrsnlFinclObjctvRecord() {
		super(PrsnlFinclObjctv.PRSNL_FINCL_OBJCTV);
	}

	/**
	 * Create a detached, initialised PrsnlFinclObjctvRecord
	 */
	public PrsnlFinclObjctvRecord(BigDecimal mrktId, BigDecimal offrPerdId, BigDecimal objctvId, BigDecimal clstrId, String userNm, BigDecimal prsnlVerId, String objctvTyp, BigDecimal actvRepCnt, BigDecimal sysId, BigDecimal actvSkuCnt, BigDecimal repActvtyPct, BigDecimal advrtsgBdgtAmt, BigDecimal vehPgCnt, BigDecimal vehBdgtAmt, BigDecimal cmpettnPrzeBdgtAmt, BigDecimal cnsmrIncntvBdgtAmt, BigDecimal cpiInfltnPct, BigDecimal custServcCnt, BigDecimal dscntndSkuCnt, BigDecimal giftWithPrchsBdgtAmt, BigDecimal incntvVehBdgtAmt, BigDecimal mrktShrPct, BigDecimal micrNcpsltnPgCnt, BigDecimal micrNcpsltnBdgtAmt, BigDecimal newCncptCnt, BigDecimal newSkuCnt, BigDecimal custCnt, BigDecimal ordCnt, BigDecimal othrBdgtAmt, BigDecimal pblcRltnsBdgtAmt, BigDecimal prodIncntvBdgtAmt, BigDecimal fldIncntvBdgtAmt, BigDecimal smplgBdgtAmt, BigDecimal rturnSlsPct, String creatUserId, Date creatTs, String lastUpdtUserId, Date lastUpdtTs, Integer brchrPgCnt, BigDecimal custUnitsPerRepQty, BigDecimal custUnitsPerOrdQty, BigDecimal repCnt, BigDecimal totBrchrSlsAmt, BigDecimal totCustSlsAmt, BigDecimal totRepSlsAmt, BigDecimal totAdjstmtAmt, BigDecimal grsSlsAmt, BigDecimal slsAidsAmt, BigDecimal blldSlsAmt, BigDecimal rturnSlsAmt, BigDecimal netSlsAmt, Integer totSolQty, BigDecimal totBdgtAmt, BigDecimal actvtyPct, BigDecimal avgOrdGrsSlsAmt, BigDecimal repSpndGrsSlsAmt, BigDecimal avgOrdBilldSlsAmt, BigDecimal repSpndBilldSlsAmt, Integer custServcQty, BigDecimal custSpndAmt, BigDecimal custSlsPerUnitAmt, BigDecimal grsSlsPerUnitAmt, Integer perCustUnitQty, BigDecimal avgCmpgnCustSlsAmt, BigDecimal rsrchBdgtAmt, Long apptCnt) {
		super(PrsnlFinclObjctv.PRSNL_FINCL_OBJCTV);

		setValue(0, mrktId);
		setValue(1, offrPerdId);
		setValue(2, objctvId);
		setValue(3, clstrId);
		setValue(4, userNm);
		setValue(5, prsnlVerId);
		setValue(6, objctvTyp);
		setValue(7, actvRepCnt);
		setValue(8, sysId);
		setValue(9, actvSkuCnt);
		setValue(10, repActvtyPct);
		setValue(11, advrtsgBdgtAmt);
		setValue(12, vehPgCnt);
		setValue(13, vehBdgtAmt);
		setValue(14, cmpettnPrzeBdgtAmt);
		setValue(15, cnsmrIncntvBdgtAmt);
		setValue(16, cpiInfltnPct);
		setValue(17, custServcCnt);
		setValue(18, dscntndSkuCnt);
		setValue(19, giftWithPrchsBdgtAmt);
		setValue(20, incntvVehBdgtAmt);
		setValue(21, mrktShrPct);
		setValue(22, micrNcpsltnPgCnt);
		setValue(23, micrNcpsltnBdgtAmt);
		setValue(24, newCncptCnt);
		setValue(25, newSkuCnt);
		setValue(26, custCnt);
		setValue(27, ordCnt);
		setValue(28, othrBdgtAmt);
		setValue(29, pblcRltnsBdgtAmt);
		setValue(30, prodIncntvBdgtAmt);
		setValue(31, fldIncntvBdgtAmt);
		setValue(32, smplgBdgtAmt);
		setValue(33, rturnSlsPct);
		setValue(34, creatUserId);
		setValue(35, creatTs);
		setValue(36, lastUpdtUserId);
		setValue(37, lastUpdtTs);
		setValue(38, brchrPgCnt);
		setValue(39, custUnitsPerRepQty);
		setValue(40, custUnitsPerOrdQty);
		setValue(41, repCnt);
		setValue(42, totBrchrSlsAmt);
		setValue(43, totCustSlsAmt);
		setValue(44, totRepSlsAmt);
		setValue(45, totAdjstmtAmt);
		setValue(46, grsSlsAmt);
		setValue(47, slsAidsAmt);
		setValue(48, blldSlsAmt);
		setValue(49, rturnSlsAmt);
		setValue(50, netSlsAmt);
		setValue(51, totSolQty);
		setValue(52, totBdgtAmt);
		setValue(53, actvtyPct);
		setValue(54, avgOrdGrsSlsAmt);
		setValue(55, repSpndGrsSlsAmt);
		setValue(56, avgOrdBilldSlsAmt);
		setValue(57, repSpndBilldSlsAmt);
		setValue(58, custServcQty);
		setValue(59, custSpndAmt);
		setValue(60, custSlsPerUnitAmt);
		setValue(61, grsSlsPerUnitAmt);
		setValue(62, perCustUnitQty);
		setValue(63, avgCmpgnCustSlsAmt);
		setValue(64, rsrchBdgtAmt);
		setValue(65, apptCnt);
	}
}
