/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;
import org.jooq.tables.TrndBilngDays;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrndBilngDaysRecord extends TableRecordImpl<TrndBilngDaysRecord> implements Record4<BigDecimal, BigDecimal, BigDecimal, Date> {

	private static final long serialVersionUID = 346945211;

	/**
	 * Setter for <code>WETRN.TRND_BILNG_DAYS.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_BILNG_DAYS.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.TRND_BILNG_DAYS.SLS_PERD_ID</code>.
	 */
	public void setSlsPerdId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_BILNG_DAYS.SLS_PERD_ID</code>.
	 */
	public BigDecimal getSlsPerdId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.TRND_BILNG_DAYS.DAY_NUM</code>.
	 */
	public void setDayNum(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_BILNG_DAYS.DAY_NUM</code>.
	 */
	public BigDecimal getDayNum() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.TRND_BILNG_DAYS.PRCSNG_DT</code>.
	 */
	public void setPrcsngDt(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_BILNG_DAYS.PRCSNG_DT</code>.
	 */
	public Date getPrcsngDt() {
		return (Date) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<BigDecimal, BigDecimal, BigDecimal, Date> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<BigDecimal, BigDecimal, BigDecimal, Date> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return TrndBilngDays.TRND_BILNG_DAYS.MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return TrndBilngDays.TRND_BILNG_DAYS.SLS_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return TrndBilngDays.TRND_BILNG_DAYS.DAY_NUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return TrndBilngDays.TRND_BILNG_DAYS.PRCSNG_DT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getSlsPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getDayNum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getPrcsngDt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndBilngDaysRecord value1(BigDecimal value) {
		setMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndBilngDaysRecord value2(BigDecimal value) {
		setSlsPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndBilngDaysRecord value3(BigDecimal value) {
		setDayNum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndBilngDaysRecord value4(Date value) {
		setPrcsngDt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndBilngDaysRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, Date value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrndBilngDaysRecord
	 */
	public TrndBilngDaysRecord() {
		super(TrndBilngDays.TRND_BILNG_DAYS);
	}

	/**
	 * Create a detached, initialised TrndBilngDaysRecord
	 */
	public TrndBilngDaysRecord(BigDecimal mrktId, BigDecimal slsPerdId, BigDecimal dayNum, Date prcsngDt) {
		super(TrndBilngDays.TRND_BILNG_DAYS);

		setValue(0, mrktId);
		setValue(1, slsPerdId);
		setValue(2, dayNum);
		setValue(3, prcsngDt);
	}
}
