/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.TrndSlsSt;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrndSlsStRecord extends UpdatableRecordImpl<TrndSlsStRecord> implements Record9<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> {

	private static final long serialVersionUID = 645507325;

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.SLS_PERD_ID</code>.
	 */
	public void setSlsPerdId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.SLS_PERD_ID</code>.
	 */
	public BigDecimal getSlsPerdId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.REF_SLS_PERD_ID</code>.
	 */
	public void setRefSlsPerdId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.REF_SLS_PERD_ID</code>.
	 */
	public BigDecimal getRefSlsPerdId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.REF_OFFR_PERD_ID</code>.
	 */
	public void setRefOffrPerdId(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.REF_OFFR_PERD_ID</code>.
	 */
	public BigDecimal getRefOffrPerdId() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.DAY_NUM</code>.
	 */
	public void setDayNum(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.DAY_NUM</code>.
	 */
	public BigDecimal getDayNum() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.CREAT_USER_ID</code>.
	 */
	public void setCreatUserId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.CREAT_USER_ID</code>.
	 */
	public String getCreatUserId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.CREAT_TS</code>.
	 */
	public void setCreatTs(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.CREAT_TS</code>.
	 */
	public Date getCreatTs() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.LAST_UPDT_USER_ID</code>.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.LAST_UPDT_USER_ID</code>.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.TRND_SLS_ST.LAST_UPDT_TS</code>.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_SLS_ST.LAST_UPDT_TS</code>.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record5<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> key() {
		return (Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return TrndSlsSt.TRND_SLS_ST.MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return TrndSlsSt.TRND_SLS_ST.SLS_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return TrndSlsSt.TRND_SLS_ST.REF_SLS_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return TrndSlsSt.TRND_SLS_ST.REF_OFFR_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return TrndSlsSt.TRND_SLS_ST.DAY_NUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TrndSlsSt.TRND_SLS_ST.CREAT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return TrndSlsSt.TRND_SLS_ST.CREAT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return TrndSlsSt.TRND_SLS_ST.LAST_UPDT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field9() {
		return TrndSlsSt.TRND_SLS_ST.LAST_UPDT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getSlsPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getRefSlsPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getRefOffrPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getDayNum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCreatUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getCreatTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getLastUpdtUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value9() {
		return getLastUpdtTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value1(BigDecimal value) {
		setMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value2(BigDecimal value) {
		setSlsPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value3(BigDecimal value) {
		setRefSlsPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value4(BigDecimal value) {
		setRefOffrPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value5(BigDecimal value) {
		setDayNum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value6(String value) {
		setCreatUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value7(Date value) {
		setCreatTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value8(String value) {
		setLastUpdtUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord value9(Date value) {
		setLastUpdtTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndSlsStRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, String value6, Date value7, String value8, Date value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrndSlsStRecord
	 */
	public TrndSlsStRecord() {
		super(TrndSlsSt.TRND_SLS_ST);
	}

	/**
	 * Create a detached, initialised TrndSlsStRecord
	 */
	public TrndSlsStRecord(BigDecimal mrktId, BigDecimal slsPerdId, BigDecimal refSlsPerdId, BigDecimal refOffrPerdId, BigDecimal dayNum, String creatUserId, Date creatTs, String lastUpdtUserId, Date lastUpdtTs) {
		super(TrndSlsSt.TRND_SLS_ST);

		setValue(0, mrktId);
		setValue(1, slsPerdId);
		setValue(2, refSlsPerdId);
		setValue(3, refOffrPerdId);
		setValue(4, dayNum);
		setValue(5, creatUserId);
		setValue(6, creatTs);
		setValue(7, lastUpdtUserId);
		setValue(8, lastUpdtTs);
	}
}
