/**
 * This class is generated by jOOQ
 */
package org.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record5;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.tables.TrndCtgrySlsPctOvr;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrndCtgrySlsPctOvrRecord extends UpdatableRecordImpl<TrndCtgrySlsPctOvrRecord> implements Record11<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date, BigDecimal> {

	private static final long serialVersionUID = -2067786727;

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.MRKT_ID</code>.
	 */
	public void setMrktId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.MRKT_ID</code>.
	 */
	public BigDecimal getMrktId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.SLS_PERD_ID</code>.
	 */
	public void setSlsPerdId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.SLS_PERD_ID</code>.
	 */
	public BigDecimal getSlsPerdId() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.OFFR_PERD_ID</code>.
	 */
	public void setOffrPerdId(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.OFFR_PERD_ID</code>.
	 */
	public BigDecimal getOffrPerdId() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.CATGRY_ID</code>.
	 */
	public void setCatgryId(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.CATGRY_ID</code>.
	 */
	public BigDecimal getCatgryId() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.DAY_NUM</code>.
	 */
	public void setDayNum(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.DAY_NUM</code>.
	 */
	public BigDecimal getDayNum() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.PCT_OVR</code>.
	 */
	public void setPctOvr(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.PCT_OVR</code>.
	 */
	public BigDecimal getPctOvr() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.CREAT_USER_ID</code>.
	 */
	public void setCreatUserId(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.CREAT_USER_ID</code>.
	 */
	public String getCreatUserId() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.CREAT_TS</code>.
	 */
	public void setCreatTs(Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.CREAT_TS</code>.
	 */
	public Date getCreatTs() {
		return (Date) getValue(7);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.LAST_UPDT_USER_ID</code>.
	 */
	public void setLastUpdtUserId(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.LAST_UPDT_USER_ID</code>.
	 */
	public String getLastUpdtUserId() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.LAST_UPDT_TS</code>.
	 */
	public void setLastUpdtTs(Date value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.LAST_UPDT_TS</code>.
	 */
	public Date getLastUpdtTs() {
		return (Date) getValue(9);
	}

	/**
	 * Setter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.SELECTED</code>.
	 */
	public void setSelected(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>WETRN.TRND_CTGRY_SLS_PCT_OVR.SELECTED</code>.
	 */
	public BigDecimal getSelected() {
		return (BigDecimal) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record5<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> key() {
		return (Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date, BigDecimal> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, Date, String, Date, BigDecimal> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.MRKT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.SLS_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.OFFR_PERD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.CATGRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.DAY_NUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.PCT_OVR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.CREAT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field8() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.CREAT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.LAST_UPDT_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field10() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.LAST_UPDT_TS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field11() {
		return TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR.SELECTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getMrktId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getSlsPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getOffrPerdId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getCatgryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getDayNum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getPctOvr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getCreatUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value8() {
		return getCreatTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getLastUpdtUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value10() {
		return getLastUpdtTs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value11() {
		return getSelected();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value1(BigDecimal value) {
		setMrktId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value2(BigDecimal value) {
		setSlsPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value3(BigDecimal value) {
		setOffrPerdId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value4(BigDecimal value) {
		setCatgryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value5(BigDecimal value) {
		setDayNum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value6(BigDecimal value) {
		setPctOvr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value7(String value) {
		setCreatUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value8(Date value) {
		setCreatTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value9(String value) {
		setLastUpdtUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value10(Date value) {
		setLastUpdtTs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord value11(BigDecimal value) {
		setSelected(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrndCtgrySlsPctOvrRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, String value7, Date value8, String value9, Date value10, BigDecimal value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrndCtgrySlsPctOvrRecord
	 */
	public TrndCtgrySlsPctOvrRecord() {
		super(TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR);
	}

	/**
	 * Create a detached, initialised TrndCtgrySlsPctOvrRecord
	 */
	public TrndCtgrySlsPctOvrRecord(BigDecimal mrktId, BigDecimal slsPerdId, BigDecimal offrPerdId, BigDecimal catgryId, BigDecimal dayNum, BigDecimal pctOvr, String creatUserId, Date creatTs, String lastUpdtUserId, Date lastUpdtTs, BigDecimal selected) {
		super(TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR);

		setValue(0, mrktId);
		setValue(1, slsPerdId);
		setValue(2, offrPerdId);
		setValue(3, catgryId);
		setValue(4, dayNum);
		setValue(5, pctOvr);
		setValue(6, creatUserId);
		setValue(7, creatTs);
		setValue(8, lastUpdtUserId);
		setValue(9, lastUpdtTs);
		setValue(10, selected);
	}
}
