/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.app_lnm_sea_reassign_normal;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.AppLnmSeaReassignNormal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetReassignItemsGeneral extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 697358119;

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"), false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_LEAD_MRKT_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_LEAD_MRKT_ID = createParameter("P_LEAD_MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_CATGRY_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_CATGRY_ID = createParameter("P_CATGRY_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_GENDR_ID_LIST</code>.
	 */
	public static final Parameter<String> P_GENDR_ID_LIST = createParameter("P_GENDR_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_BRND_FMLY_ID_LIST</code>.
	 */
	public static final Parameter<String> P_BRND_FMLY_ID_LIST = createParameter("P_BRND_FMLY_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_BRND_ID_LIST</code>.
	 */
	public static final Parameter<String> P_BRND_ID_LIST = createParameter("P_BRND_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_FORM_GRP_ID_LIST</code>.
	 */
	public static final Parameter<String> P_FORM_GRP_ID_LIST = createParameter("P_FORM_GRP_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_PROD_TYP_ID_LIST</code>.
	 */
	public static final Parameter<String> P_PROD_TYP_ID_LIST = createParameter("P_PROD_TYP_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_FORM_ID_LIST</code>.
	 */
	public static final Parameter<String> P_FORM_ID_LIST = createParameter("P_FORM_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_LNM_SEA_REASSIGN_NORMAL.GET_REASSIGN_ITEMS_GENERAL.P_SGMT_ID_LIST</code>.
	 */
	public static final Parameter<String> P_SGMT_ID_LIST = createParameter("P_SGMT_ID_LIST", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public GetReassignItemsGeneral() {
		super("GET_REASSIGN_ITEMS_GENERAL", Wetrn.WETRN, AppLnmSeaReassignNormal.APP_LNM_SEA_REASSIGN_NORMAL, org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"));

		setReturnParameter(RETURN_VALUE);
		addInParameter(P_LEAD_MRKT_ID);
		addInParameter(P_CATGRY_ID);
		addInParameter(P_GENDR_ID_LIST);
		addInParameter(P_BRND_FMLY_ID_LIST);
		addInParameter(P_BRND_ID_LIST);
		addInParameter(P_FORM_GRP_ID_LIST);
		addInParameter(P_PROD_TYP_ID_LIST);
		addInParameter(P_FORM_ID_LIST);
		addInParameter(P_SGMT_ID_LIST);
	}

	/**
	 * Set the <code>P_LEAD_MRKT_ID</code> parameter IN value to the routine
	 */
	public void setPLeadMrktId(Number value) {
		setNumber(P_LEAD_MRKT_ID, value);
	}

	/**
	 * Set the <code>P_LEAD_MRKT_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPLeadMrktId(Field<? extends Number> field) {
		setNumber(P_LEAD_MRKT_ID, field);
	}

	/**
	 * Set the <code>P_CATGRY_ID</code> parameter IN value to the routine
	 */
	public void setPCatgryId(Number value) {
		setNumber(P_CATGRY_ID, value);
	}

	/**
	 * Set the <code>P_CATGRY_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPCatgryId(Field<? extends Number> field) {
		setNumber(P_CATGRY_ID, field);
	}

	/**
	 * Set the <code>P_GENDR_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPGendrIdList(String value) {
		setValue(P_GENDR_ID_LIST, value);
	}

	/**
	 * Set the <code>P_GENDR_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPGendrIdList(Field<String> field) {
		setField(P_GENDR_ID_LIST, field);
	}

	/**
	 * Set the <code>P_BRND_FMLY_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPBrndFmlyIdList(String value) {
		setValue(P_BRND_FMLY_ID_LIST, value);
	}

	/**
	 * Set the <code>P_BRND_FMLY_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPBrndFmlyIdList(Field<String> field) {
		setField(P_BRND_FMLY_ID_LIST, field);
	}

	/**
	 * Set the <code>P_BRND_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPBrndIdList(String value) {
		setValue(P_BRND_ID_LIST, value);
	}

	/**
	 * Set the <code>P_BRND_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPBrndIdList(Field<String> field) {
		setField(P_BRND_ID_LIST, field);
	}

	/**
	 * Set the <code>P_FORM_GRP_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPFormGrpIdList(String value) {
		setValue(P_FORM_GRP_ID_LIST, value);
	}

	/**
	 * Set the <code>P_FORM_GRP_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPFormGrpIdList(Field<String> field) {
		setField(P_FORM_GRP_ID_LIST, field);
	}

	/**
	 * Set the <code>P_PROD_TYP_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPProdTypIdList(String value) {
		setValue(P_PROD_TYP_ID_LIST, value);
	}

	/**
	 * Set the <code>P_PROD_TYP_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPProdTypIdList(Field<String> field) {
		setField(P_PROD_TYP_ID_LIST, field);
	}

	/**
	 * Set the <code>P_FORM_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPFormIdList(String value) {
		setValue(P_FORM_ID_LIST, value);
	}

	/**
	 * Set the <code>P_FORM_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPFormIdList(Field<String> field) {
		setField(P_FORM_ID_LIST, field);
	}

	/**
	 * Set the <code>P_SGMT_ID_LIST</code> parameter IN value to the routine
	 */
	public void setPSgmtIdList(String value) {
		setValue(P_SGMT_ID_LIST, value);
	}

	/**
	 * Set the <code>P_SGMT_ID_LIST</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSgmtIdList(Field<String> field) {
		setField(P_SGMT_ID_LIST, field);
	}
}
