/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.pa_maps_move_concept;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.PaMapsMoveConcept;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoveConcept extends AbstractRoutine<BigDecimal> {

	private static final long serialVersionUID = -628350011;

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.RETURN_VALUE</code>.
	 */
	public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_SOURCEOFFERID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_SOURCEOFFERID = createParameter("PAR_SOURCEOFFERID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_TARGETOFFERID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_TARGETOFFERID = createParameter("PAR_TARGETOFFERID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_VEHID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_VEHID = createParameter("PAR_VEHID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_PRFLCD</code>.
	 */
	public static final Parameter<BigDecimal> PAR_PRFLCD = createParameter("PAR_PRFLCD", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_SOURCESIDE</code>.
	 */
	public static final Parameter<String> PAR_SOURCESIDE = createParameter("PAR_SOURCESIDE", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_TARGETSIDE</code>.
	 */
	public static final Parameter<String> PAR_TARGETSIDE = createParameter("PAR_TARGETSIDE", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_SOURCEOFFSET</code>.
	 */
	public static final Parameter<BigDecimal> PAR_SOURCEOFFSET = createParameter("PAR_SOURCEOFFSET", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_TARGETOFFSET</code>.
	 */
	public static final Parameter<BigDecimal> PAR_TARGETOFFSET = createParameter("PAR_TARGETOFFSET", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_SLSCLS</code>.
	 */
	public static final Parameter<String> PAR_SLSCLS = createParameter("PAR_SLSCLS", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_ZEROUNITS</code>.
	 */
	public static final Parameter<BigDecimal> PAR_ZEROUNITS = createParameter("PAR_ZEROUNITS", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_MOVE_CONCEPT.MOVE_CONCEPT.PAR_USER</code>.
	 */
	public static final Parameter<String> PAR_USER = createParameter("PAR_USER", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public MoveConcept() {
		super("MOVE_CONCEPT", Wetrn.WETRN, PaMapsMoveConcept.PA_MAPS_MOVE_CONCEPT, org.jooq.impl.SQLDataType.NUMERIC);

		setReturnParameter(RETURN_VALUE);
		addInParameter(PAR_SOURCEOFFERID);
		addInParameter(PAR_TARGETOFFERID);
		addInParameter(PAR_VEHID);
		addInParameter(PAR_PRFLCD);
		addInParameter(PAR_SOURCESIDE);
		addInParameter(PAR_TARGETSIDE);
		addInParameter(PAR_SOURCEOFFSET);
		addInParameter(PAR_TARGETOFFSET);
		addInParameter(PAR_SLSCLS);
		addInParameter(PAR_ZEROUNITS);
		addInParameter(PAR_USER);
	}

	/**
	 * Set the <code>PAR_SOURCEOFFERID</code> parameter IN value to the routine
	 */
	public void setParSourceofferid(Number value) {
		setNumber(PAR_SOURCEOFFERID, value);
	}

	/**
	 * Set the <code>PAR_SOURCEOFFERID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParSourceofferid(Field<? extends Number> field) {
		setNumber(PAR_SOURCEOFFERID, field);
	}

	/**
	 * Set the <code>PAR_TARGETOFFERID</code> parameter IN value to the routine
	 */
	public void setParTargetofferid(Number value) {
		setNumber(PAR_TARGETOFFERID, value);
	}

	/**
	 * Set the <code>PAR_TARGETOFFERID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParTargetofferid(Field<? extends Number> field) {
		setNumber(PAR_TARGETOFFERID, field);
	}

	/**
	 * Set the <code>PAR_VEHID</code> parameter IN value to the routine
	 */
	public void setParVehid(Number value) {
		setNumber(PAR_VEHID, value);
	}

	/**
	 * Set the <code>PAR_VEHID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParVehid(Field<? extends Number> field) {
		setNumber(PAR_VEHID, field);
	}

	/**
	 * Set the <code>PAR_PRFLCD</code> parameter IN value to the routine
	 */
	public void setParPrflcd(Number value) {
		setNumber(PAR_PRFLCD, value);
	}

	/**
	 * Set the <code>PAR_PRFLCD</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParPrflcd(Field<? extends Number> field) {
		setNumber(PAR_PRFLCD, field);
	}

	/**
	 * Set the <code>PAR_SOURCESIDE</code> parameter IN value to the routine
	 */
	public void setParSourceside(String value) {
		setValue(PAR_SOURCESIDE, value);
	}

	/**
	 * Set the <code>PAR_SOURCESIDE</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParSourceside(Field<String> field) {
		setField(PAR_SOURCESIDE, field);
	}

	/**
	 * Set the <code>PAR_TARGETSIDE</code> parameter IN value to the routine
	 */
	public void setParTargetside(String value) {
		setValue(PAR_TARGETSIDE, value);
	}

	/**
	 * Set the <code>PAR_TARGETSIDE</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParTargetside(Field<String> field) {
		setField(PAR_TARGETSIDE, field);
	}

	/**
	 * Set the <code>PAR_SOURCEOFFSET</code> parameter IN value to the routine
	 */
	public void setParSourceoffset(Number value) {
		setNumber(PAR_SOURCEOFFSET, value);
	}

	/**
	 * Set the <code>PAR_SOURCEOFFSET</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParSourceoffset(Field<? extends Number> field) {
		setNumber(PAR_SOURCEOFFSET, field);
	}

	/**
	 * Set the <code>PAR_TARGETOFFSET</code> parameter IN value to the routine
	 */
	public void setParTargetoffset(Number value) {
		setNumber(PAR_TARGETOFFSET, value);
	}

	/**
	 * Set the <code>PAR_TARGETOFFSET</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParTargetoffset(Field<? extends Number> field) {
		setNumber(PAR_TARGETOFFSET, field);
	}

	/**
	 * Set the <code>PAR_SLSCLS</code> parameter IN value to the routine
	 */
	public void setParSlscls(String value) {
		setValue(PAR_SLSCLS, value);
	}

	/**
	 * Set the <code>PAR_SLSCLS</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParSlscls(Field<String> field) {
		setField(PAR_SLSCLS, field);
	}

	/**
	 * Set the <code>PAR_ZEROUNITS</code> parameter IN value to the routine
	 */
	public void setParZerounits(Number value) {
		setNumber(PAR_ZEROUNITS, value);
	}

	/**
	 * Set the <code>PAR_ZEROUNITS</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParZerounits(Field<? extends Number> field) {
		setNumber(PAR_ZEROUNITS, field);
	}

	/**
	 * Set the <code>PAR_USER</code> parameter IN value to the routine
	 */
	public void setParUser(String value) {
		setValue(PAR_USER, value);
	}

	/**
	 * Set the <code>PAR_USER</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParUser(Field<String> field) {
		setField(PAR_USER, field);
	}
}
