/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.pa_maps_cos;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.PaMapsCos;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetDispositionPeriod extends AbstractRoutine<BigDecimal> {

	private static final long serialVersionUID = -288905852;

	/**
	 * The parameter <code>WETRN.PA_MAPS_COS.GET_DISPOSITION_PERIOD.RETURN_VALUE</code>.
	 */
	public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COS.GET_DISPOSITION_PERIOD.MARKETID</code>.
	 */
	public static final Parameter<BigDecimal> MARKETID = createParameter("MARKETID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COS.GET_DISPOSITION_PERIOD.SKUID</code>.
	 */
	public static final Parameter<BigDecimal> SKUID = createParameter("SKUID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COS.GET_DISPOSITION_PERIOD.FSC</code>.
	 */
	public static final Parameter<String> FSC = createParameter("FSC", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public GetDispositionPeriod() {
		super("GET_DISPOSITION_PERIOD", Wetrn.WETRN, PaMapsCos.PA_MAPS_COS, org.jooq.impl.SQLDataType.NUMERIC);

		setReturnParameter(RETURN_VALUE);
		addInParameter(MARKETID);
		addInParameter(SKUID);
		addInParameter(FSC);
	}

	/**
	 * Set the <code>MARKETID</code> parameter IN value to the routine
	 */
	public void setMarketid(Number value) {
		setNumber(MARKETID, value);
	}

	/**
	 * Set the <code>MARKETID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setMarketid(Field<? extends Number> field) {
		setNumber(MARKETID, field);
	}

	/**
	 * Set the <code>SKUID</code> parameter IN value to the routine
	 */
	public void setSkuid(Number value) {
		setNumber(SKUID, value);
	}

	/**
	 * Set the <code>SKUID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setSkuid(Field<? extends Number> field) {
		setNumber(SKUID, field);
	}

	/**
	 * Set the <code>FSC</code> parameter IN value to the routine
	 */
	public void setFsc(String value) {
		setValue(FSC, value);
	}

	/**
	 * Set the <code>FSC</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setFsc(Field<String> field) {
		setField(FSC, field);
	}
}
