/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.cpy_offr;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.CpyOffr;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetTgrtMrktDtl extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 890932447;

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"), false);

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.P_CLSRT_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_CLSRT_ID = createParameter("P_CLSRT_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.P_SRCE_MRKT_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_SRCE_MRKT_ID = createParameter("P_SRCE_MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.P_SRCE_VEH_ID</code>.
	 */
	public static final Parameter<String> P_SRCE_VEH_ID = createParameter("P_SRCE_VEH_ID", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.P_SRCE_VER_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_SRCE_VER_ID = createParameter("P_SRCE_VER_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.P_SRCE_PERD_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_SRCE_PERD_ID = createParameter("P_SRCE_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.CPY_OFFR.GET_TGRT_MRKT_DTL.P_USER_NM</code>.
	 */
	public static final Parameter<String> P_USER_NM = createParameter("P_USER_NM", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public GetTgrtMrktDtl() {
		super("GET_TGRT_MRKT_DTL", Wetrn.WETRN, CpyOffr.CPY_OFFR, org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"));

		setReturnParameter(RETURN_VALUE);
		addInParameter(P_CLSRT_ID);
		addInParameter(P_SRCE_MRKT_ID);
		addInParameter(P_SRCE_VEH_ID);
		addInParameter(P_SRCE_VER_ID);
		addInParameter(P_SRCE_PERD_ID);
		addInParameter(P_USER_NM);
	}

	/**
	 * Set the <code>P_CLSRT_ID</code> parameter IN value to the routine
	 */
	public void setPClsrtId(Number value) {
		setNumber(P_CLSRT_ID, value);
	}

	/**
	 * Set the <code>P_CLSRT_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPClsrtId(Field<? extends Number> field) {
		setNumber(P_CLSRT_ID, field);
	}

	/**
	 * Set the <code>P_SRCE_MRKT_ID</code> parameter IN value to the routine
	 */
	public void setPSrceMrktId(Number value) {
		setNumber(P_SRCE_MRKT_ID, value);
	}

	/**
	 * Set the <code>P_SRCE_MRKT_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSrceMrktId(Field<? extends Number> field) {
		setNumber(P_SRCE_MRKT_ID, field);
	}

	/**
	 * Set the <code>P_SRCE_VEH_ID</code> parameter IN value to the routine
	 */
	public void setPSrceVehId(String value) {
		setValue(P_SRCE_VEH_ID, value);
	}

	/**
	 * Set the <code>P_SRCE_VEH_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSrceVehId(Field<String> field) {
		setField(P_SRCE_VEH_ID, field);
	}

	/**
	 * Set the <code>P_SRCE_VER_ID</code> parameter IN value to the routine
	 */
	public void setPSrceVerId(Number value) {
		setNumber(P_SRCE_VER_ID, value);
	}

	/**
	 * Set the <code>P_SRCE_VER_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSrceVerId(Field<? extends Number> field) {
		setNumber(P_SRCE_VER_ID, field);
	}

	/**
	 * Set the <code>P_SRCE_PERD_ID</code> parameter IN value to the routine
	 */
	public void setPSrcePerdId(Number value) {
		setNumber(P_SRCE_PERD_ID, value);
	}

	/**
	 * Set the <code>P_SRCE_PERD_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSrcePerdId(Field<? extends Number> field) {
		setNumber(P_SRCE_PERD_ID, field);
	}

	/**
	 * Set the <code>P_USER_NM</code> parameter IN value to the routine
	 */
	public void setPUserNm(String value) {
		setValue(P_USER_NM, value);
	}

	/**
	 * Set the <code>P_USER_NM</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPUserNm(Field<String> field) {
		setField(P_USER_NM, field);
	}
}
