/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.pa_maps;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.PaMaps;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RollbackIntrfcCntrlPending extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 438813277;

	/**
	 * The parameter <code>WETRN.PA_MAPS.ROLLBACK_INTRFC_CNTRL_PENDING.P_TOPIC</code>.
	 */
	public static final Parameter<BigDecimal> P_TOPIC = createParameter("P_TOPIC", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public RollbackIntrfcCntrlPending() {
		super("ROLLBACK_INTRFC_CNTRL_PENDING", Wetrn.WETRN, PaMaps.PA_MAPS);

		addInParameter(P_TOPIC);
	}

	/**
	 * Set the <code>P_TOPIC</code> parameter IN value to the routine
	 */
	public void setPTopic(Number value) {
		setNumber(P_TOPIC, value);
	}
}
