/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.app_fcb_exp_imp;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.AppFcbExpImp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FGetExpDet extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 1009022719;

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"), false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_MRKT_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_MRKT_ID = createParameter("P_MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_OFF_PER_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_OFF_PER_ID = createParameter("P_OFF_PER_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_CATEGORY_ID</code>.
	 */
	public static final Parameter<String> P_CATEGORY_ID = createParameter("P_CATEGORY_ID", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_SLS_CLS</code>.
	 */
	public static final Parameter<String> P_SLS_CLS = createParameter("P_SLS_CLS", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_BRND</code>.
	 */
	public static final Parameter<String> P_BRND = createParameter("P_BRND", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_SUB_BRND</code>.
	 */
	public static final Parameter<String> P_SUB_BRND = createParameter("P_SUB_BRND", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_FRM_GRP</code>.
	 */
	public static final Parameter<String> P_FRM_GRP = createParameter("P_FRM_GRP", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_FRM</code>.
	 */
	public static final Parameter<String> P_FRM = createParameter("P_FRM", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.APP_FCB_EXP_IMP.F_GET_EXP_DET.P_SEG</code>.
	 */
	public static final Parameter<String> P_SEG = createParameter("P_SEG", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public FGetExpDet() {
		super("F_GET_EXP_DET", Wetrn.WETRN, AppFcbExpImp.APP_FCB_EXP_IMP, org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"));

		setReturnParameter(RETURN_VALUE);
		addInParameter(P_MRKT_ID);
		addInParameter(P_OFF_PER_ID);
		addInParameter(P_CATEGORY_ID);
		addInParameter(P_SLS_CLS);
		addInParameter(P_BRND);
		addInParameter(P_SUB_BRND);
		addInParameter(P_FRM_GRP);
		addInParameter(P_FRM);
		addInParameter(P_SEG);
	}

	/**
	 * Set the <code>P_MRKT_ID</code> parameter IN value to the routine
	 */
	public void setPMrktId(Number value) {
		setNumber(P_MRKT_ID, value);
	}

	/**
	 * Set the <code>P_MRKT_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPMrktId(Field<? extends Number> field) {
		setNumber(P_MRKT_ID, field);
	}

	/**
	 * Set the <code>P_OFF_PER_ID</code> parameter IN value to the routine
	 */
	public void setPOffPerId(Number value) {
		setNumber(P_OFF_PER_ID, value);
	}

	/**
	 * Set the <code>P_OFF_PER_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPOffPerId(Field<? extends Number> field) {
		setNumber(P_OFF_PER_ID, field);
	}

	/**
	 * Set the <code>P_CATEGORY_ID</code> parameter IN value to the routine
	 */
	public void setPCategoryId(String value) {
		setValue(P_CATEGORY_ID, value);
	}

	/**
	 * Set the <code>P_CATEGORY_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPCategoryId(Field<String> field) {
		setField(P_CATEGORY_ID, field);
	}

	/**
	 * Set the <code>P_SLS_CLS</code> parameter IN value to the routine
	 */
	public void setPSlsCls(String value) {
		setValue(P_SLS_CLS, value);
	}

	/**
	 * Set the <code>P_SLS_CLS</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSlsCls(Field<String> field) {
		setField(P_SLS_CLS, field);
	}

	/**
	 * Set the <code>P_BRND</code> parameter IN value to the routine
	 */
	public void setPBrnd(String value) {
		setValue(P_BRND, value);
	}

	/**
	 * Set the <code>P_BRND</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPBrnd(Field<String> field) {
		setField(P_BRND, field);
	}

	/**
	 * Set the <code>P_SUB_BRND</code> parameter IN value to the routine
	 */
	public void setPSubBrnd(String value) {
		setValue(P_SUB_BRND, value);
	}

	/**
	 * Set the <code>P_SUB_BRND</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSubBrnd(Field<String> field) {
		setField(P_SUB_BRND, field);
	}

	/**
	 * Set the <code>P_FRM_GRP</code> parameter IN value to the routine
	 */
	public void setPFrmGrp(String value) {
		setValue(P_FRM_GRP, value);
	}

	/**
	 * Set the <code>P_FRM_GRP</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPFrmGrp(Field<String> field) {
		setField(P_FRM_GRP, field);
	}

	/**
	 * Set the <code>P_FRM</code> parameter IN value to the routine
	 */
	public void setPFrm(String value) {
		setValue(P_FRM, value);
	}

	/**
	 * Set the <code>P_FRM</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPFrm(Field<String> field) {
		setField(P_FRM, field);
	}

	/**
	 * Set the <code>P_SEG</code> parameter IN value to the routine
	 */
	public void setPSeg(String value) {
		setValue(P_SEG, value);
	}

	/**
	 * Set the <code>P_SEG</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPSeg(Field<String> field) {
		setField(P_SEG, field);
	}
}
