/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.rep_sos_campaign;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.RepSosCampaign;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetValidSlsTypIds extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 563346179;

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("PL/SQL TABLE"), false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_MRKT_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_MRKT_ID = createParameter("P_MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_FROM_OFFR_PERD_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_FROM_OFFR_PERD_ID = createParameter("P_FROM_OFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_TO_OFFR_PERD_ID</code>.
	 */
	public static final Parameter<BigDecimal> P_TO_OFFR_PERD_ID = createParameter("P_TO_OFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_VEH_ID</code>.
	 */
	public static final Parameter<String> P_VEH_ID = createParameter("P_VEH_ID", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_VER_ID_1</code>.
	 */
	public static final Parameter<BigDecimal> P_VER_ID_1 = createParameter("P_VER_ID_1", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_VER_ID_2</code>.
	 */
	public static final Parameter<BigDecimal> P_VER_ID_2 = createParameter("P_VER_ID_2", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_VER_ID_3</code>.
	 */
	public static final Parameter<BigDecimal> P_VER_ID_3 = createParameter("P_VER_ID_3", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_VER_ID_4</code>.
	 */
	public static final Parameter<BigDecimal> P_VER_ID_4 = createParameter("P_VER_ID_4", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.REP_SOS_CAMPAIGN.GET_VALID_SLS_TYP_IDS.P_VER_ID_5</code>.
	 */
	public static final Parameter<BigDecimal> P_VER_ID_5 = createParameter("P_VER_ID_5", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public GetValidSlsTypIds() {
		super("GET_VALID_SLS_TYP_IDS", Wetrn.WETRN, RepSosCampaign.REP_SOS_CAMPAIGN, org.jooq.impl.DefaultDataType.getDefaultDataType("PL/SQL TABLE"));

		setReturnParameter(RETURN_VALUE);
		addInParameter(P_MRKT_ID);
		addInParameter(P_FROM_OFFR_PERD_ID);
		addInParameter(P_TO_OFFR_PERD_ID);
		addInParameter(P_VEH_ID);
		addInParameter(P_VER_ID_1);
		addInParameter(P_VER_ID_2);
		addInParameter(P_VER_ID_3);
		addInParameter(P_VER_ID_4);
		addInParameter(P_VER_ID_5);
	}

	/**
	 * Set the <code>P_MRKT_ID</code> parameter IN value to the routine
	 */
	public void setPMrktId(Number value) {
		setNumber(P_MRKT_ID, value);
	}

	/**
	 * Set the <code>P_MRKT_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPMrktId(Field<? extends Number> field) {
		setNumber(P_MRKT_ID, field);
	}

	/**
	 * Set the <code>P_FROM_OFFR_PERD_ID</code> parameter IN value to the routine
	 */
	public void setPFromOffrPerdId(Number value) {
		setNumber(P_FROM_OFFR_PERD_ID, value);
	}

	/**
	 * Set the <code>P_FROM_OFFR_PERD_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPFromOffrPerdId(Field<? extends Number> field) {
		setNumber(P_FROM_OFFR_PERD_ID, field);
	}

	/**
	 * Set the <code>P_TO_OFFR_PERD_ID</code> parameter IN value to the routine
	 */
	public void setPToOffrPerdId(Number value) {
		setNumber(P_TO_OFFR_PERD_ID, value);
	}

	/**
	 * Set the <code>P_TO_OFFR_PERD_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPToOffrPerdId(Field<? extends Number> field) {
		setNumber(P_TO_OFFR_PERD_ID, field);
	}

	/**
	 * Set the <code>P_VEH_ID</code> parameter IN value to the routine
	 */
	public void setPVehId(String value) {
		setValue(P_VEH_ID, value);
	}

	/**
	 * Set the <code>P_VEH_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPVehId(Field<String> field) {
		setField(P_VEH_ID, field);
	}

	/**
	 * Set the <code>P_VER_ID_1</code> parameter IN value to the routine
	 */
	public void setPVerId_1(Number value) {
		setNumber(P_VER_ID_1, value);
	}

	/**
	 * Set the <code>P_VER_ID_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPVerId_1(Field<? extends Number> field) {
		setNumber(P_VER_ID_1, field);
	}

	/**
	 * Set the <code>P_VER_ID_2</code> parameter IN value to the routine
	 */
	public void setPVerId_2(Number value) {
		setNumber(P_VER_ID_2, value);
	}

	/**
	 * Set the <code>P_VER_ID_2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPVerId_2(Field<? extends Number> field) {
		setNumber(P_VER_ID_2, field);
	}

	/**
	 * Set the <code>P_VER_ID_3</code> parameter IN value to the routine
	 */
	public void setPVerId_3(Number value) {
		setNumber(P_VER_ID_3, value);
	}

	/**
	 * Set the <code>P_VER_ID_3</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPVerId_3(Field<? extends Number> field) {
		setNumber(P_VER_ID_3, field);
	}

	/**
	 * Set the <code>P_VER_ID_4</code> parameter IN value to the routine
	 */
	public void setPVerId_4(Number value) {
		setNumber(P_VER_ID_4, value);
	}

	/**
	 * Set the <code>P_VER_ID_4</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPVerId_4(Field<? extends Number> field) {
		setNumber(P_VER_ID_4, field);
	}

	/**
	 * Set the <code>P_VER_ID_5</code> parameter IN value to the routine
	 */
	public void setPVerId_5(Number value) {
		setNumber(P_VER_ID_5, value);
	}

	/**
	 * Set the <code>P_VER_ID_5</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPVerId_5(Field<? extends Number> field) {
		setNumber(P_VER_ID_5, field);
	}
}
