/**
 * This class is generated by jOOQ
 */
package org.jooq.udt;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.UDTField;
import org.jooq.Wetrn;
import org.jooq.impl.UDTImpl;
import org.jooq.udt.records.TEditOffrGwpDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TEditOffrGwpData extends UDTImpl<TEditOffrGwpDataRecord> {

	private static final long serialVersionUID = 1808799626;

	/**
	 * The reference instance of <code>WETRN.T_EDIT_OFFR_GWP_DATA</code>
	 */
	public static final TEditOffrGwpData T_EDIT_OFFR_GWP_DATA = new TEditOffrGwpData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TEditOffrGwpDataRecord> getRecordType() {
		return TEditOffrGwpDataRecord.class;
	}

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.OFFR_ID</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, BigDecimal> OFFR_ID = createField("OFFR_ID", org.jooq.impl.SQLDataType.NUMERIC, T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.OFFR_DESC</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, String> OFFR_DESC = createField("OFFR_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(400), T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.PRFL_CD</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, BigDecimal> PRFL_CD = createField("PRFL_CD", org.jooq.impl.SQLDataType.NUMERIC, T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.PRFL_NM</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, String> PRFL_NM = createField("PRFL_NM", org.jooq.impl.SQLDataType.VARCHAR.length(200), T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.SKU_ID</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, BigDecimal> SKU_ID = createField("SKU_ID", org.jooq.impl.SQLDataType.NUMERIC, T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.SKU_NM</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, String> SKU_NM = createField("SKU_NM", org.jooq.impl.SQLDataType.VARCHAR.length(200), T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.GIFT_SKU_ID</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, BigDecimal> GIFT_SKU_ID = createField("GIFT_SKU_ID", org.jooq.impl.SQLDataType.NUMERIC, T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * The attribute <code>WETRN.T_EDIT_OFFR_GWP_DATA.GIFT_SKU_NM</code>.
	 */
	public static final UDTField<TEditOffrGwpDataRecord, String> GIFT_SKU_NM = createField("GIFT_SKU_NM", org.jooq.impl.SQLDataType.VARCHAR.length(200), T_EDIT_OFFR_GWP_DATA, "");

	/**
	 * No further instances allowed
	 */
	private TEditOffrGwpData() {
		super("T_EDIT_OFFR_GWP_DATA", Wetrn.WETRN);

		// Initialise data type
		getDataType();
	}
}
