/**
 * This class is generated by jOOQ
 */
package org.jooq.udt;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.UDTField;
import org.jooq.Wetrn;
import org.jooq.impl.UDTImpl;
import org.jooq.udt.records.TSaCntrlTotExpRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSaCntrlTotExp extends UDTImpl<TSaCntrlTotExpRecord> {

	private static final long serialVersionUID = 2084729152;

	/**
	 * The reference instance of <code>WETRN.T_SA_CNTRL_TOT_EXP</code>
	 */
	public static final TSaCntrlTotExp T_SA_CNTRL_TOT_EXP = new TSaCntrlTotExp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TSaCntrlTotExpRecord> getRecordType() {
		return TSaCntrlTotExpRecord.class;
	}

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.MRKT_ID</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> MRKT_ID = createField("MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.OFFR_PERD_ID</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> OFFR_PERD_ID = createField("OFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_CHNL_CD</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> SLS_CHNL_CD = createField("SLS_CHNL_CD", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.FSC_CD</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> FSC_CD = createField("FSC_CD", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.FSC_DESC</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> FSC_DESC = createField("FSC_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_TYP</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> SLS_TYP = createField("SLS_TYP", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_ALOCTN_AUTO_STUS_ID</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> SLS_ALOCTN_AUTO_STUS_ID = createField("SLS_ALOCTN_AUTO_STUS_ID", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_ALOCTN_AUTO_STUS_DESC</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> SLS_ALOCTN_AUTO_STUS_DESC = createField("SLS_ALOCTN_AUTO_STUS_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_ALOCTN_MANUL_STUS_ID</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> SLS_ALOCTN_MANUL_STUS_ID = createField("SLS_ALOCTN_MANUL_STUS_ID", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_ALOCTN_MANUL_STUS_DESC</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> SLS_ALOCTN_MANUL_STUS_DESC = createField("SLS_ALOCTN_MANUL_STUS_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.LCL_BILNG_OFFR_TYP</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> LCL_BILNG_OFFR_TYP = createField("LCL_BILNG_OFFR_TYP", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.BILNG_LINE_NR</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> BILNG_LINE_NR = createField("BILNG_LINE_NR", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_PRC_AMT</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> SLS_PRC_AMT = createField("SLS_PRC_AMT", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.NR_FOR_QTY</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> NR_FOR_QTY = createField("NR_FOR_QTY", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.LCL_BILNG_DEFRD_CD</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> LCL_BILNG_DEFRD_CD = createField("LCL_BILNG_DEFRD_CD", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.LCL_BILNG_ACTN_CD</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> LCL_BILNG_ACTN_CD = createField("LCL_BILNG_ACTN_CD", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.LCL_BILNG_TRAN_TYP</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> LCL_BILNG_TRAN_TYP = createField("LCL_BILNG_TRAN_TYP", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.LCL_BILNG_SHPNG_CD</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> LCL_BILNG_SHPNG_CD = createField("LCL_BILNG_SHPNG_CD", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.CAMPGN_OF_AVLBLT</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> CAMPGN_OF_AVLBLT = createField("CAMPGN_OF_AVLBLT", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.NO_SLBL_CMPGN</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> NO_SLBL_CMPGN = createField("NO_SLBL_CMPGN", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SKU_ID</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> SKU_ID = createField("SKU_ID", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.NUMBR_OF_RECDS</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> NUMBR_OF_RECDS = createField("NUMBR_OF_RECDS", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.UNIT_QTY</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> UNIT_QTY = createField("UNIT_QTY", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.COMSN_AMT</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> COMSN_AMT = createField("COMSN_AMT", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.TAX_AMT</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, BigDecimal> TAX_AMT = createField("TAX_AMT", org.jooq.impl.SQLDataType.NUMERIC, T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.SLS_TYP_DESC</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> SLS_TYP_DESC = createField("SLS_TYP_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(255), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * The attribute <code>WETRN.T_SA_CNTRL_TOT_EXP.PLN_IND</code>.
	 */
	public static final UDTField<TSaCntrlTotExpRecord, String> PLN_IND = createField("PLN_IND", org.jooq.impl.SQLDataType.VARCHAR.length(20), T_SA_CNTRL_TOT_EXP, "");

	/**
	 * No further instances allowed
	 */
	private TSaCntrlTotExp() {
		super("T_SA_CNTRL_TOT_EXP", Wetrn.WETRN);

		// Initialise data type
		getDataType();
	}
}
