/**
 * This class is generated by jOOQ
 */
package org.jooq.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.Wetrn;
import org.jooq.impl.TableImpl;
import org.jooq.tables.records.DlyBilngTempRecord;


/**
 * Temporary table used during the Sales Allocation process to hold status/sku 
 * data for a daily billing record
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DlyBilngTemp extends TableImpl<DlyBilngTempRecord> {

	private static final long serialVersionUID = -1189280192;

	/**
	 * The reference instance of <code>WETRN.DLY_BILNG_TEMP</code>
	 */
	public static final DlyBilngTemp DLY_BILNG_TEMP = new DlyBilngTemp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DlyBilngTempRecord> getRecordType() {
		return DlyBilngTempRecord.class;
	}

	/**
	 * The column <code>WETRN.DLY_BILNG_TEMP.DLY_BILNG_ID</code>.
	 */
	public final TableField<DlyBilngTempRecord, BigDecimal> DLY_BILNG_ID = createField("DLY_BILNG_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>WETRN.DLY_BILNG_TEMP.SLS_ALOCTN_AUTO_STUS_ID</code>.
	 */
	public final TableField<DlyBilngTempRecord, BigDecimal> SLS_ALOCTN_AUTO_STUS_ID = createField("SLS_ALOCTN_AUTO_STUS_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>WETRN.DLY_BILNG_TEMP.SKU_ID</code>.
	 */
	public final TableField<DlyBilngTempRecord, BigDecimal> SKU_ID = createField("SKU_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>WETRN.DLY_BILNG_TEMP.SKU_MTCH_MTHD_ID</code>.
	 */
	public final TableField<DlyBilngTempRecord, BigDecimal> SKU_MTCH_MTHD_ID = createField("SKU_MTCH_MTHD_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * Create a <code>WETRN.DLY_BILNG_TEMP</code> table reference
	 */
	public DlyBilngTemp() {
		this("DLY_BILNG_TEMP", null);
	}

	/**
	 * Create an aliased <code>WETRN.DLY_BILNG_TEMP</code> table reference
	 */
	public DlyBilngTemp(String alias) {
		this(alias, DLY_BILNG_TEMP);
	}

	private DlyBilngTemp(String alias, Table<DlyBilngTempRecord> aliased) {
		this(alias, aliased, null);
	}

	private DlyBilngTemp(String alias, Table<DlyBilngTempRecord> aliased, Field<?>[] parameters) {
		super(alias, Wetrn.WETRN, aliased, parameters, "Temporary table used during the Sales Allocation process to hold status/sku data for a daily billing record");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DlyBilngTemp as(String alias) {
		return new DlyBilngTemp(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DlyBilngTemp rename(String name) {
		return new DlyBilngTemp(name, null);
	}
}
