/**
 * This class is generated by jOOQ
 */
package org.jooq.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Keys;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.Wetrn;
import org.jooq.impl.TableImpl;
import org.jooq.tables.records.LclChnlRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LclChnl extends TableImpl<LclChnlRecord> {

	private static final long serialVersionUID = -1458186931;

	/**
	 * The reference instance of <code>WETRN.LCL_CHNL</code>
	 */
	public static final LclChnl LCL_CHNL = new LclChnl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LclChnlRecord> getRecordType() {
		return LclChnlRecord.class;
	}

	/**
	 * The column <code>WETRN.LCL_CHNL.MRKT_ID</code>.
	 */
	public final TableField<LclChnlRecord, BigDecimal> MRKT_ID = createField("MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.LCL_CHNL.LCL_CHNL_ID</code>.
	 */
	public final TableField<LclChnlRecord, String> LCL_CHNL_ID = createField("LCL_CHNL_ID", org.jooq.impl.SQLDataType.VARCHAR.length(4).nullable(false), this, "");

	/**
	 * The column <code>WETRN.LCL_CHNL.LCL_CHNL_DESC_TXT</code>.
	 */
	public final TableField<LclChnlRecord, String> LCL_CHNL_DESC_TXT = createField("LCL_CHNL_DESC_TXT", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>WETRN.LCL_CHNL.CREAT_USER_ID</code>.
	 */
	public final TableField<LclChnlRecord, String> CREAT_USER_ID = createField("CREAT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.LCL_CHNL.CREAT_TS</code>.
	 */
	public final TableField<LclChnlRecord, Date> CREAT_TS = createField("CREAT_TS", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.LCL_CHNL.LAST_UPDT_USER_ID</code>.
	 */
	public final TableField<LclChnlRecord, String> LAST_UPDT_USER_ID = createField("LAST_UPDT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

	/**
	 * The column <code>WETRN.LCL_CHNL.LAST_UPDT_TS</code>.
	 */
	public final TableField<LclChnlRecord, Date> LAST_UPDT_TS = createField("LAST_UPDT_TS", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>WETRN.LCL_CHNL</code> table reference
	 */
	public LclChnl() {
		this("LCL_CHNL", null);
	}

	/**
	 * Create an aliased <code>WETRN.LCL_CHNL</code> table reference
	 */
	public LclChnl(String alias) {
		this(alias, LCL_CHNL);
	}

	private LclChnl(String alias, Table<LclChnlRecord> aliased) {
		this(alias, aliased, null);
	}

	private LclChnl(String alias, Table<LclChnlRecord> aliased, Field<?>[] parameters) {
		super(alias, Wetrn.WETRN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<LclChnlRecord> getPrimaryKey() {
		return Keys.PK_LCL_CHNL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<LclChnlRecord>> getKeys() {
		return Arrays.<UniqueKey<LclChnlRecord>>asList(Keys.PK_LCL_CHNL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<LclChnlRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<LclChnlRecord, ?>>asList(Keys.FK_MRKT_LCLCHNL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LclChnl as(String alias) {
		return new LclChnl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public LclChnl rename(String name) {
		return new LclChnl(name, null);
	}
}
