/**
 * This class is generated by jOOQ
 */
package org.jooq.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.Wetrn;
import org.jooq.impl.TableImpl;
import org.jooq.tables.records.MrktgProdRspbltyBrndFmlyRecord;


/**
 * snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_BRND_FMLY
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MrktgProdRspbltyBrndFmly extends TableImpl<MrktgProdRspbltyBrndFmlyRecord> {

	private static final long serialVersionUID = -1975243287;

	/**
	 * The reference instance of <code>WETRN.MRKTG_PROD_RSPBLTY_BRND_FMLY</code>
	 */
	public static final MrktgProdRspbltyBrndFmly MRKTG_PROD_RSPBLTY_BRND_FMLY = new MrktgProdRspbltyBrndFmly();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MrktgProdRspbltyBrndFmlyRecord> getRecordType() {
		return MrktgProdRspbltyBrndFmlyRecord.class;
	}

	/**
	 * The column <code>WETRN.MRKTG_PROD_RSPBLTY_BRND_FMLY.MRKTG_PROD_RSPBLTY_ID</code>.
	 */
	public final TableField<MrktgProdRspbltyBrndFmlyRecord, BigDecimal> MRKTG_PROD_RSPBLTY_ID = createField("MRKTG_PROD_RSPBLTY_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.MRKTG_PROD_RSPBLTY_BRND_FMLY.MRKT_ID</code>.
	 */
	public final TableField<MrktgProdRspbltyBrndFmlyRecord, BigDecimal> MRKT_ID = createField("MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.MRKTG_PROD_RSPBLTY_BRND_FMLY.BRND_FMLY_ID</code>.
	 */
	public final TableField<MrktgProdRspbltyBrndFmlyRecord, BigDecimal> BRND_FMLY_ID = createField("BRND_FMLY_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * Create a <code>WETRN.MRKTG_PROD_RSPBLTY_BRND_FMLY</code> table reference
	 */
	public MrktgProdRspbltyBrndFmly() {
		this("MRKTG_PROD_RSPBLTY_BRND_FMLY", null);
	}

	/**
	 * Create an aliased <code>WETRN.MRKTG_PROD_RSPBLTY_BRND_FMLY</code> table reference
	 */
	public MrktgProdRspbltyBrndFmly(String alias) {
		this(alias, MRKTG_PROD_RSPBLTY_BRND_FMLY);
	}

	private MrktgProdRspbltyBrndFmly(String alias, Table<MrktgProdRspbltyBrndFmlyRecord> aliased) {
		this(alias, aliased, null);
	}

	private MrktgProdRspbltyBrndFmly(String alias, Table<MrktgProdRspbltyBrndFmlyRecord> aliased, Field<?>[] parameters) {
		super(alias, Wetrn.WETRN, aliased, parameters, "snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_BRND_FMLY");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktgProdRspbltyBrndFmly as(String alias) {
		return new MrktgProdRspbltyBrndFmly(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MrktgProdRspbltyBrndFmly rename(String name) {
		return new MrktgProdRspbltyBrndFmly(name, null);
	}
}
