/**
 * This class is generated by jOOQ
 */
package org.jooq.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Keys;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.Wetrn;
import org.jooq.impl.TableImpl;
import org.jooq.tables.records.MrktVehPerdBrchrPlcmtRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MrktVehPerdBrchrPlcmt extends TableImpl<MrktVehPerdBrchrPlcmtRecord> {

	private static final long serialVersionUID = -742636309;

	/**
	 * The reference instance of <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT</code>
	 */
	public static final MrktVehPerdBrchrPlcmt MRKT_VEH_PERD_BRCHR_PLCMT = new MrktVehPerdBrchrPlcmt();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MrktVehPerdBrchrPlcmtRecord> getRecordType() {
		return MrktVehPerdBrchrPlcmtRecord.class;
	}

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.MRKT_ID</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, BigDecimal> MRKT_ID = createField("MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.VEH_ID</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, BigDecimal> VEH_ID = createField("VEH_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.OFFR_PERD_ID</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, BigDecimal> OFFR_PERD_ID = createField("OFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.BRCHR_PLCMT_ID</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, BigDecimal> BRCHR_PLCMT_ID = createField("BRCHR_PLCMT_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.PG_CNT</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, Integer> PG_CNT = createField("PG_CNT", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.CREAT_USER_ID</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, String> CREAT_USER_ID = createField("CREAT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.CREAT_TS</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, Date> CREAT_TS = createField("CREAT_TS", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.LAST_UPDT_USER_ID</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, String> LAST_UPDT_USER_ID = createField("LAST_UPDT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

	/**
	 * The column <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT.LAST_UPDT_TS</code>.
	 */
	public final TableField<MrktVehPerdBrchrPlcmtRecord, Date> LAST_UPDT_TS = createField("LAST_UPDT_TS", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT</code> table reference
	 */
	public MrktVehPerdBrchrPlcmt() {
		this("MRKT_VEH_PERD_BRCHR_PLCMT", null);
	}

	/**
	 * Create an aliased <code>WETRN.MRKT_VEH_PERD_BRCHR_PLCMT</code> table reference
	 */
	public MrktVehPerdBrchrPlcmt(String alias) {
		this(alias, MRKT_VEH_PERD_BRCHR_PLCMT);
	}

	private MrktVehPerdBrchrPlcmt(String alias, Table<MrktVehPerdBrchrPlcmtRecord> aliased) {
		this(alias, aliased, null);
	}

	private MrktVehPerdBrchrPlcmt(String alias, Table<MrktVehPerdBrchrPlcmtRecord> aliased, Field<?>[] parameters) {
		super(alias, Wetrn.WETRN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MrktVehPerdBrchrPlcmtRecord> getPrimaryKey() {
		return Keys.PK_MRKT_VEH_PERD_BRCHR_PLCMT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MrktVehPerdBrchrPlcmtRecord>> getKeys() {
		return Arrays.<UniqueKey<MrktVehPerdBrchrPlcmtRecord>>asList(Keys.PK_MRKT_VEH_PERD_BRCHR_PLCMT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<MrktVehPerdBrchrPlcmtRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<MrktVehPerdBrchrPlcmtRecord, ?>>asList(Keys.FK_MRKTVEHPERD_MRKTVEHPERDBRCH, Keys.FK_BRCHRPLCMT_MRKTVEHPERDBRCHR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MrktVehPerdBrchrPlcmt as(String alias) {
		return new MrktVehPerdBrchrPlcmt(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MrktVehPerdBrchrPlcmt rename(String name) {
		return new MrktVehPerdBrchrPlcmt(name, null);
	}
}
