/**
 * This class is generated by jOOQ
 */
package org.jooq.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Keys;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.Wetrn;
import org.jooq.impl.TableImpl;
import org.jooq.tables.records.SkuCostRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkuCost extends TableImpl<SkuCostRecord> {

	private static final long serialVersionUID = 979660437;

	/**
	 * The reference instance of <code>WETRN.SKU_COST</code>
	 */
	public static final SkuCost SKU_COST = new SkuCost();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SkuCostRecord> getRecordType() {
		return SkuCostRecord.class;
	}

	/**
	 * The column <code>WETRN.SKU_COST.MRKT_ID</code>.
	 */
	public final TableField<SkuCostRecord, BigDecimal> MRKT_ID = createField("MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.OFFR_PERD_ID</code>.
	 */
	public final TableField<SkuCostRecord, BigDecimal> OFFR_PERD_ID = createField("OFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.SKU_ID</code>.
	 */
	public final TableField<SkuCostRecord, BigDecimal> SKU_ID = createField("SKU_ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.COST_TYP</code>.
	 */
	public final TableField<SkuCostRecord, String> COST_TYP = createField("COST_TYP", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.CRNCY_CD</code>.
	 */
	public final TableField<SkuCostRecord, String> CRNCY_CD = createField("CRNCY_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.WGHTD_AVG_COST_AMT</code>.
	 */
	public final TableField<SkuCostRecord, BigDecimal> WGHTD_AVG_COST_AMT = createField("WGHTD_AVG_COST_AMT", org.jooq.impl.SQLDataType.NUMERIC.precision(15, 3).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.CREAT_USER_ID</code>.
	 */
	public final TableField<SkuCostRecord, String> CREAT_USER_ID = createField("CREAT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.CREAT_TS</code>.
	 */
	public final TableField<SkuCostRecord, Date> CREAT_TS = createField("CREAT_TS", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.LAST_UPDT_USER_ID</code>.
	 */
	public final TableField<SkuCostRecord, String> LAST_UPDT_USER_ID = createField("LAST_UPDT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.LAST_UPDT_TS</code>.
	 */
	public final TableField<SkuCostRecord, Date> LAST_UPDT_TS = createField("LAST_UPDT_TS", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>WETRN.SKU_COST.HOLD_COSTS_IND</code>.
	 */
	public final TableField<SkuCostRecord, String> HOLD_COSTS_IND = createField("HOLD_COSTS_IND", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>WETRN.SKU_COST.LCL_COST_IND</code>.
	 */
	public final TableField<SkuCostRecord, String> LCL_COST_IND = createField("LCL_COST_IND", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

	/**
	 * Create a <code>WETRN.SKU_COST</code> table reference
	 */
	public SkuCost() {
		this("SKU_COST", null);
	}

	/**
	 * Create an aliased <code>WETRN.SKU_COST</code> table reference
	 */
	public SkuCost(String alias) {
		this(alias, SKU_COST);
	}

	private SkuCost(String alias, Table<SkuCostRecord> aliased) {
		this(alias, aliased, null);
	}

	private SkuCost(String alias, Table<SkuCostRecord> aliased, Field<?>[] parameters) {
		super(alias, Wetrn.WETRN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SkuCostRecord> getPrimaryKey() {
		return Keys.PK_SKU_COST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SkuCostRecord>> getKeys() {
		return Arrays.<UniqueKey<SkuCostRecord>>asList(Keys.PK_SKU_COST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<SkuCostRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<SkuCostRecord, ?>>asList(Keys.FK_MRKTPERD_SKUCOST, Keys.FK_MRKTSKU_SKUCOST, Keys.FK_CRNCY_SKUCOST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkuCost as(String alias) {
		return new SkuCost(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SkuCost rename(String name) {
		return new SkuCost(name, null);
	}
}
