/**
 * This class is generated by jOOQ
 */
package org.jooq.tables;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.Wetrn;
import org.jooq.impl.TableImpl;
import org.jooq.tables.records.VwBestSkuCostRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBestSkuCost extends TableImpl<VwBestSkuCostRecord> {

	private static final long serialVersionUID = 1261116652;

	/**
	 * The reference instance of <code>WETRN.VW_BEST_SKU_COST</code>
	 */
	public static final VwBestSkuCost VW_BEST_SKU_COST = new VwBestSkuCost();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VwBestSkuCostRecord> getRecordType() {
		return VwBestSkuCostRecord.class;
	}

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.MRKT_ID</code>.
	 */
	public final TableField<VwBestSkuCostRecord, BigDecimal> MRKT_ID = createField("MRKT_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.OFFR_PERD_ID</code>.
	 */
	public final TableField<VwBestSkuCostRecord, BigDecimal> OFFR_PERD_ID = createField("OFFR_PERD_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.SKU_ID</code>.
	 */
	public final TableField<VwBestSkuCostRecord, BigDecimal> SKU_ID = createField("SKU_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.COST_TYP</code>.
	 */
	public final TableField<VwBestSkuCostRecord, String> COST_TYP = createField("COST_TYP", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.CRNCY_CD</code>.
	 */
	public final TableField<VwBestSkuCostRecord, String> CRNCY_CD = createField("CRNCY_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.WGHTD_AVG_COST_AMT</code>.
	 */
	public final TableField<VwBestSkuCostRecord, BigDecimal> WGHTD_AVG_COST_AMT = createField("WGHTD_AVG_COST_AMT", org.jooq.impl.SQLDataType.NUMERIC.precision(15, 3), this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.CREAT_USER_ID</code>.
	 */
	public final TableField<VwBestSkuCostRecord, String> CREAT_USER_ID = createField("CREAT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.CREAT_TS</code>.
	 */
	public final TableField<VwBestSkuCostRecord, Date> CREAT_TS = createField("CREAT_TS", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.LAST_UPDT_USER_ID</code>.
	 */
	public final TableField<VwBestSkuCostRecord, String> LAST_UPDT_USER_ID = createField("LAST_UPDT_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(35), this, "");

	/**
	 * The column <code>WETRN.VW_BEST_SKU_COST.LAST_UPDT_TS</code>.
	 */
	public final TableField<VwBestSkuCostRecord, Date> LAST_UPDT_TS = createField("LAST_UPDT_TS", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>WETRN.VW_BEST_SKU_COST</code> table reference
	 */
	public VwBestSkuCost() {
		this("VW_BEST_SKU_COST", null);
	}

	/**
	 * Create an aliased <code>WETRN.VW_BEST_SKU_COST</code> table reference
	 */
	public VwBestSkuCost(String alias) {
		this(alias, VW_BEST_SKU_COST);
	}

	private VwBestSkuCost(String alias, Table<VwBestSkuCostRecord> aliased) {
		this(alias, aliased, null);
	}

	private VwBestSkuCost(String alias, Table<VwBestSkuCostRecord> aliased, Field<?>[] parameters) {
		super(alias, Wetrn.WETRN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VwBestSkuCost as(String alias) {
		return new VwBestSkuCost(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VwBestSkuCost rename(String name) {
		return new VwBestSkuCost(name, null);
	}
}
