/**
 * This class is generated by jOOQ
 */
package org.jooq;


import javax.annotation.Generated;

import org.jooq.tables.AdminMsg;
import org.jooq.tables.AltLineNr;
import org.jooq.tables.AltLineNrUpd;
import org.jooq.tables.AudtMrktSku;
import org.jooq.tables.BbMrktVeh;
import org.jooq.tables.BilngLineNrData;
import org.jooq.tables.BilngLineNrGrp;
import org.jooq.tables.BilngLineNrGrpLkup;
import org.jooq.tables.BilngSetFscReus;
import org.jooq.tables.BilngSys;
import org.jooq.tables.BilngSysLineNrTyp;
import org.jooq.tables.BrchrLineNr;
import org.jooq.tables.BrchrLineNrAudit;
import org.jooq.tables.BrchrLineNrGrp;
import org.jooq.tables.BrchrLineNrGrpLkup;
import org.jooq.tables.BrchrLineNrReassignAudit;
import org.jooq.tables.BrchrLineNrTyp;
import org.jooq.tables.BrchrLineNrTypLkup;
import org.jooq.tables.BrchrLineNrTypMtrx;
import org.jooq.tables.BrchrLineNrUpd;
import org.jooq.tables.BrchrPlcmt;
import org.jooq.tables.BrchrPostn;
import org.jooq.tables.Brnch;
import org.jooq.tables.BrnchPerdDstrbtn;
import org.jooq.tables.BrnchSls;
import org.jooq.tables.Brnd;
import org.jooq.tables.BrndFmly;
import org.jooq.tables.BrndGrp;
import org.jooq.tables.BrndPostnng;
import org.jooq.tables.BrndTyp;
import org.jooq.tables.BtchJob;
import org.jooq.tables.BtchJobStus;
import org.jooq.tables.BtchJobTyp;
import org.jooq.tables.BtchJobTypGrp;
import org.jooq.tables.BtchTask;
import org.jooq.tables.BtchTaskLog;
import org.jooq.tables.BtchTaskLogTyp;
import org.jooq.tables.BtchTaskStus;
import org.jooq.tables.BtchTaskTyp;
import org.jooq.tables.Bus;
import org.jooq.tables.Catgry;
import org.jooq.tables.CatgryBrnd;
import org.jooq.tables.CatgryForm;
import org.jooq.tables.CatgrySgmt;
import org.jooq.tables.CatgrySgmtForm;
import org.jooq.tables.CatgrySuplr;
import org.jooq.tables.ChkDigtCalcltn;
import org.jooq.tables.Chnl;
import org.jooq.tables.ChoiceVehCopy;
import org.jooq.tables.ChoiceVehTyp;
import org.jooq.tables.ClstrBrchrPlcmt;
import org.jooq.tables.ClstrLclBus;
import org.jooq.tables.ClstrMrktgProdRspblty;
import org.jooq.tables.ClstrSlsTyp;
import org.jooq.tables.ClstrVeh;
import org.jooq.tables.ClstrVer;
import org.jooq.tables.CmpttnTyp;
import org.jooq.tables.Cmpttr;
import org.jooq.tables.CmpttrProdPromtn;
import org.jooq.tables.CmpttrProdRegPrc;
import org.jooq.tables.CncptlOffr;
import org.jooq.tables.CnsmrInvstmt;
import org.jooq.tables.CnsmrInvstmtBdgt;
import org.jooq.tables.CntntForm;
import org.jooq.tables.ComsnTyp;
import org.jooq.tables.ComsnTypLkup;
import org.jooq.tables.ConfigItem;
import org.jooq.tables.ConfigItemAudit;
import org.jooq.tables.CopyUnitsRul;
import org.jooq.tables.Crncy;
import org.jooq.tables.CubeConfig;
import org.jooq.tables.CustGrp;
import org.jooq.tables.CustPull;
import org.jooq.tables.DailyBilling;
import org.jooq.tables.DataXclusnTyp;
import org.jooq.tables.DemoDiscnt;
import org.jooq.tables.DemoDiscntGrp;
import org.jooq.tables.DfaltPrcRule;
import org.jooq.tables.DfltMrktVehComsn;
import org.jooq.tables.DfltMrktVehTax;
import org.jooq.tables.DltdBilngLineNrData;
import org.jooq.tables.DltdDstrbtdMrktSls;
import org.jooq.tables.DltdOffr;
import org.jooq.tables.DltdOffrPrflPrcPoint;
import org.jooq.tables.DltdOffrPrflSlsClsPlcmt;
import org.jooq.tables.DltdOffrSkuLine;
import org.jooq.tables.DltdOffrSkuSet;
import org.jooq.tables.DltdOffrSlsClsSku;
import org.jooq.tables.DltdPlugSls;
import org.jooq.tables.DlyBilng;
import org.jooq.tables.DlyBilngBkup;
import org.jooq.tables.DlyBilngBkupTrnsTyp;
import org.jooq.tables.DlyBilngCntrl;
import org.jooq.tables.DlyBilngCntrlAudit;
import org.jooq.tables.DlyBilngFscSplt;
import org.jooq.tables.DlyBilngMtch;
import org.jooq.tables.DlyBilngMtchAudit;
import org.jooq.tables.DlyBilngOffrSkuLine;
import org.jooq.tables.DlyBilngOffrSkuLineOld;
import org.jooq.tables.DlyBilngOslAudit;
import org.jooq.tables.DlyBilngOslTemp;
import org.jooq.tables.DlyBilngTemp;
import org.jooq.tables.DlyBilngTrnd;
import org.jooq.tables.DlyBilngTrndCntrl;
import org.jooq.tables.DlyBilngTrndMtch;
import org.jooq.tables.DlyBilngTrndOffrSkuLine;
import org.jooq.tables.DlyBilngTrndOslAudit;
import org.jooq.tables.DlyBilngTrndOslTemp;
import org.jooq.tables.DlyBilngTrndTemp;
import org.jooq.tables.DstrbtdBrnchSls;
import org.jooq.tables.DstrbtdMrktSls;
import org.jooq.tables.EnrgyChrt;
import org.jooq.tables.EnrgyChrtPostn;
import org.jooq.tables.ErrLog;
import org.jooq.tables.EstLink;
import org.jooq.tables.EstLnkg;
import org.jooq.tables.EstOnDmnd;
import org.jooq.tables.EstTrndExcptn;
import org.jooq.tables.EstWghtTyp;
import org.jooq.tables.FinclObjctv;
import org.jooq.tables.FinclVer;
import org.jooq.tables.Form;
import org.jooq.tables.FormGrp;
import org.jooq.tables.FrcMtchMthd;
import org.jooq.tables.FrcstBoostXclusn;
import org.jooq.tables.Gendr;
import org.jooq.tables.GendrSpltCatgry;
import org.jooq.tables.GtaMthd;
import org.jooq.tables.GttDlyBilngRpt;
import org.jooq.tables.ImgDataTyp;
import org.jooq.tables.ImgFileTyp;
import org.jooq.tables.ImgImprtDataMapg;
import org.jooq.tables.ImgImprtDataPostn;
import org.jooq.tables.Impdp;
import org.jooq.tables.ImpdpLog;
import org.jooq.tables.ImpdpMapsWetrn;
import org.jooq.tables.ImpdpMaster;
import org.jooq.tables.ImpdpStats;
import org.jooq.tables.Incntv;
import org.jooq.tables.IncrementalsLog;
import org.jooq.tables.IntrfcCntrl;
import org.jooq.tables.IntrfcMrktFsc;
import org.jooq.tables.IntrfcSys;
import org.jooq.tables.IntrfcSysTpc;
import org.jooq.tables.ItemLineNrTyp;
import org.jooq.tables.ItemTyp;
import org.jooq.tables.LclBusOffrCls;
import org.jooq.tables.LclBusOffrClsPerdVer;
import org.jooq.tables.LclChnl;
import org.jooq.tables.LclChnlAudit;
import org.jooq.tables.LeadBusDiv;
import org.jooq.tables.LineNrAsgnmtTyp;
import org.jooq.tables.LineNrTyp;
import org.jooq.tables.LineNrTypCd;
import org.jooq.tables.MapsDbUpgrade;
import org.jooq.tables.MapsErrMsg;
import org.jooq.tables.MapsMenuItem;
import org.jooq.tables.MapsSmphr;
import org.jooq.tables.MessageTransaction;
import org.jooq.tables.MessageTransactionRow;
import org.jooq.tables.MissingSlsClsPlcmt;
import org.jooq.tables.MpsObj;
import org.jooq.tables.MpsParm;
import org.jooq.tables.MpsParmOffr;
import org.jooq.tables.MpsParmReplctnMovMrkt;
import org.jooq.tables.MpsParmSrceOffrPerd;
import org.jooq.tables.MpsParmSrceSlsPerd;
import org.jooq.tables.MpsParmSrceVeh;
import org.jooq.tables.MpsParmTrgtMrkt;
import org.jooq.tables.MpsParmTrgtOffrPerd;
import org.jooq.tables.MpsParmTrgtSlsPerd;
import org.jooq.tables.MpsParmTrgtVeh;
import org.jooq.tables.MpsParmTrgtVer;
import org.jooq.tables.MpsPlsqlLog;
import org.jooq.tables.MpsPlsqlOutput;
import org.jooq.tables.MpsRl;
import org.jooq.tables.MpsSys;
import org.jooq.tables.MpsUser;
import org.jooq.tables.MpsUserCatgryAcs;
import org.jooq.tables.MpsUserGrp;
import org.jooq.tables.MpsUserGrpObj;
import org.jooq.tables.MpsUserGrpUser;
import org.jooq.tables.MpsUserMrktAcs;
import org.jooq.tables.MpsUserMrktVehAcs;
import org.jooq.tables.MpsUserRl;
import org.jooq.tables.MpsUserRlMrktAcs;
import org.jooq.tables.Mrkt;
import org.jooq.tables.MrktBilngSys;
import org.jooq.tables.MrktBrnchDstrbtn;
import org.jooq.tables.MrktCmpttr;
import org.jooq.tables.MrktCmpttrCatgry;
import org.jooq.tables.MrktCmpttrProd;
import org.jooq.tables.MrktCmpttrProdPrfl;
import org.jooq.tables.MrktCnsmrInvstmtBdgtWsl;
import org.jooq.tables.MrktComsnTyp;
import org.jooq.tables.MrktComsnTypEffPerd;
import org.jooq.tables.MrktComsnTypLkup;
import org.jooq.tables.MrktConfigItem;
import org.jooq.tables.MrktConfigItemAudit;
import org.jooq.tables.MrktDemoDiscntFct;
import org.jooq.tables.MrktDemoDiscntLkup;
import org.jooq.tables.MrktEffOffrPerdLineNr;
import org.jooq.tables.MrktEffSlsPerd;
import org.jooq.tables.MrktEffSlsPerdAudit;
import org.jooq.tables.MrktEffTrndSlsPerd;
import org.jooq.tables.MrktEstWght;
import org.jooq.tables.MrktFsc;
import org.jooq.tables.MrktLclBilngOffrTyp;
import org.jooq.tables.MrktLclBilngOffrTypAudit;
import org.jooq.tables.MrktLclBus;
import org.jooq.tables.MrktMrktgProdRspblty;
import org.jooq.tables.MrktOffrTaxCatgryLkup;
import org.jooq.tables.MrktOfsUsg;
import org.jooq.tables.MrktPerd;
import org.jooq.tables.MrktPerdCatgry;
import org.jooq.tables.MrktPerdCmpgnMapg;
import org.jooq.tables.MrktPerdDstrbtn;
import org.jooq.tables.MrktPerdPrfl;
import org.jooq.tables.MrktPerdSkuBias;
import org.jooq.tables.MrktPerdSkuPrc;
import org.jooq.tables.MrktPerdSlngPrcRndngFct;
import org.jooq.tables.MrktPerdVehSprd;
import org.jooq.tables.MrktPrcLvl;
import org.jooq.tables.MrktPrcLvlTyp;
import org.jooq.tables.MrktPrfl;
import org.jooq.tables.MrktPrflChrty;
import org.jooq.tables.MrktPrflPrcStrtgy;
import org.jooq.tables.MrktPrflRoylt;
import org.jooq.tables.MrktPromtn;
import org.jooq.tables.MrktPromtnClm;
import org.jooq.tables.MrktPromtnCmplnc;
import org.jooq.tables.MrktRltnshp;
import org.jooq.tables.MrktRltnshpTyp;
import org.jooq.tables.MrktSaGtaOvrrdAudit;
import org.jooq.tables.MrktSetBilngFsc;
import org.jooq.tables.MrktSetBilngFscAudit;
import org.jooq.tables.MrktSku;
import org.jooq.tables.MrktSkuUnitSpltPct;
import org.jooq.tables.MrktSls;
import org.jooq.tables.MrktSlsAloctnGtaOvrrd;
import org.jooq.tables.MrktSlsChnlOffrTypSlsperd;
import org.jooq.tables.MrktSlsClsWsl;
import org.jooq.tables.MrktSlsPerd;
import org.jooq.tables.MrktTaxCatgry;
import org.jooq.tables.MrktTaxEffPerd;
import org.jooq.tables.MrktTaxTyp;
import org.jooq.tables.MrktTaxTypEffPerd;
import org.jooq.tables.MrktTaxTypGrp;
import org.jooq.tables.MrktTaxTypLkup;
import org.jooq.tables.MrktTrndSlsPerd;
import org.jooq.tables.MrktUnitPrc;
import org.jooq.tables.MrktUnitPrcEffPerd;
import org.jooq.tables.MrktVeh;
import org.jooq.tables.MrktVehCopyExcptn;
import org.jooq.tables.MrktVehOffrCls;
import org.jooq.tables.MrktVehPerd;
import org.jooq.tables.MrktVehPerdBrchrPlcmt;
import org.jooq.tables.MrktVehPerdCatgry;
import org.jooq.tables.MrktVehPerdLclChnl;
import org.jooq.tables.MrktVehPerdSctn;
import org.jooq.tables.MrktVehPerdVer;
import org.jooq.tables.MrktVehPostn;
import org.jooq.tables.MrktXportStus;
import org.jooq.tables.MrktgProdRspbltyBrnd;
import org.jooq.tables.MrktgProdRspbltyBrndFmly;
import org.jooq.tables.MrktgProdRspbltyCatgry;
import org.jooq.tables.MrktgProdRspbltyForm;
import org.jooq.tables.MrktgProdRspbltySgmt;
import org.jooq.tables.MrktgProdRspbltySuplr;
import org.jooq.tables.MrktngSetFgc;
import org.jooq.tables.MrktngSetFgcHist;
import org.jooq.tables.MsgTyp;
import org.jooq.tables.MstrFscAsgnmt;
import org.jooq.tables.MvRepCostHlpr;
import org.jooq.tables.ObjDsplyMsg;
import org.jooq.tables.ObjDsplyMsgTyp;
import org.jooq.tables.Objctv;
import org.jooq.tables.ObjctvCmpnt;
import org.jooq.tables.ObjctvTyp;
import org.jooq.tables.OdsMrktFscCost;
import org.jooq.tables.OdsMrktPrflCost;
import org.jooq.tables.Offr;
import org.jooq.tables.OffrCls;
import org.jooq.tables.OffrLock;
import org.jooq.tables.OffrPrflPrcPoint;
import org.jooq.tables.OffrPrflSlsClsPlcmt;
import org.jooq.tables.OffrPrsntnStrnth;
import org.jooq.tables.OffrSkuLine;
import org.jooq.tables.OffrSkuSet;
import org.jooq.tables.OffrSlsClsSku;
import org.jooq.tables.OffrStus;
import org.jooq.tables.OffrTran;
import org.jooq.tables.OffrTrgt;
import org.jooq.tables.OffrTyp;
import org.jooq.tables.OfsDstrbtnPct;
import org.jooq.tables.PatrnTyp;
import org.jooq.tables.PerdOfsNr;
import org.jooq.tables.PgTyp;
import org.jooq.tables.PgWght;
import org.jooq.tables.PlsqlProfilerData;
import org.jooq.tables.PlsqlProfilerRuns;
import org.jooq.tables.PlsqlProfilerUnits;
import org.jooq.tables.Plug;
import org.jooq.tables.PlugGrp;
import org.jooq.tables.PlugSls;
import org.jooq.tables.PlugType;
import org.jooq.tables.PrcLvlTyp;
import org.jooq.tables.PrcTyp;
import org.jooq.tables.PrcsStus;
import org.jooq.tables.Prfl;
import org.jooq.tables.ProdEndrsmt;
import org.jooq.tables.ProdLife;
import org.jooq.tables.ProdTyp;
import org.jooq.tables.Promtn;
import org.jooq.tables.PromtnClm;
import org.jooq.tables.PrsnlFinclObjctv;
import org.jooq.tables.PrsnlSrceOfSlsFinclObjctv;
import org.jooq.tables.PrsnlVer;
import org.jooq.tables.PymtTyp;
import org.jooq.tables.PymtTypGrp;
import org.jooq.tables.RepCol;
import org.jooq.tables.RepColTyp;
import org.jooq.tables.RepFileTyp;
import org.jooq.tables.RepGlblTmplt;
import org.jooq.tables.RepMrktTmplt;
import org.jooq.tables.RepMstrQry;
import org.jooq.tables.RepMstrQryCol;
import org.jooq.tables.RepMstrQryTmplt;
import org.jooq.tables.RepRunPrgrss;
import org.jooq.tables.RepSlsTypVer;
import org.jooq.tables.RepTmpltCol;
import org.jooq.tables.RepTmpltFileTyp;
import org.jooq.tables.RepTmpltSlsTypVer;
import org.jooq.tables.RepTmpltTyp;
import org.jooq.tables.RetlTyp;
import org.jooq.tables.RndngMthd;
import org.jooq.tables.Rpt;
import org.jooq.tables.RptFltr;
import org.jooq.tables.RptLog;
import org.jooq.tables.RptParmLog;
import org.jooq.tables.RptSbtlTyp;
import org.jooq.tables.RptStus;
import org.jooq.tables.RturnSls;
import org.jooq.tables.SaAutoPrcsOvrrdAudit;
import org.jooq.tables.ScrCss;
import org.jooq.tables.ScrJs;
import org.jooq.tables.ScrObjConfig;
import org.jooq.tables.ScrObjErrorMsg;
import org.jooq.tables.SetPrcTyp;
import org.jooq.tables.Sgmt;
import org.jooq.tables.Sku;
import org.jooq.tables.SkuCost;
import org.jooq.tables.SkuMtchMthd;
import org.jooq.tables.SkuRegPrc;
import org.jooq.tables.SlsAloctnAutoPrcsOvrrd;
import org.jooq.tables.SlsAloctnAutoStus;
import org.jooq.tables.SlsAloctnDataXclusn;
import org.jooq.tables.SlsAloctnManulStus;
import org.jooq.tables.SlsAloctnResetAudit;
import org.jooq.tables.SlsCls;
import org.jooq.tables.SlsPerdRng;
import org.jooq.tables.SlsSrce;
import org.jooq.tables.SlsStus;
import org.jooq.tables.SlsTyp;
import org.jooq.tables.SlsTypGrp;
import org.jooq.tables.SrceOfSlsCustGrp;
import org.jooq.tables.SrceOfSlsElmnt;
import org.jooq.tables.SrceOfSlsFinclObjctv;
import org.jooq.tables.SrceOfSlsProdTyp;
import org.jooq.tables.SrceOfSlsSlsCls;
import org.jooq.tables.SrceOfSlsVehTyp;
import org.jooq.tables.SsnlEvnt;
import org.jooq.tables.StdOffr;
import org.jooq.tables.StdOffrPrflPlcmt;
import org.jooq.tables.StdOffrPrflPrcPoint;
import org.jooq.tables.StdOffrPrflPrcpt;
import org.jooq.tables.StdOffrPrflSlsCls;
import org.jooq.tables.StgDstrbtdMrktSls;
import org.jooq.tables.Suplr;
import org.jooq.tables.SysParm;
import org.jooq.tables.TLogErrors;
import org.jooq.tables.TempOfferCopy;
import org.jooq.tables.TempOffrPrflPrcPoint;
import org.jooq.tables.Tpc;
import org.jooq.tables.TpcXportStus;
import org.jooq.tables.TranTyp;
import org.jooq.tables.TrgtCnsmrGrp;
import org.jooq.tables.TrndAloctnAutoPrcsOvrrd;
import org.jooq.tables.TrndBilngDays;
import org.jooq.tables.TrndCtgrySlsJob;
import org.jooq.tables.TrndCtgrySlsNew;
import org.jooq.tables.TrndCtgrySlsPctOvr;
import org.jooq.tables.TrndCtgrySlsSt;
import org.jooq.tables.TrndExcptn;
import org.jooq.tables.TrndSlsPctOvr;
import org.jooq.tables.TrndSlsSt;
import org.jooq.tables.TrnsfrmPrevYrMrktPerd;
import org.jooq.tables.UnitRptgLvl;
import org.jooq.tables.UomCnvrsn;
import org.jooq.tables.UomTyp;
import org.jooq.tables.VBestCost;
import org.jooq.tables.VBrnd;
import org.jooq.tables.VOffr;
import org.jooq.tables.VOffrAll;
import org.jooq.tables.VOffrAllWithBestCost;
import org.jooq.tables.VOffrSlsAll;
import org.jooq.tables.VOffrSlsMsGift;
import org.jooq.tables.VOffrWithMsGift;
import org.jooq.tables.VOffrWithoutSlsPerd;
import org.jooq.tables.Veh;
import org.jooq.tables.VehTyp;
import org.jooq.tables.Ver;
import org.jooq.tables.VerGrp;
import org.jooq.tables.VerSlsTyp;
import org.jooq.tables.VerTyp;
import org.jooq.tables.VwBestSkuCost;
import org.jooq.tables.WhatIfScnrio;
import org.jooq.tables.WhatIfTran;
import org.jooq.tables.XchngRte;
import org.jooq.tables.XportStus;
import org.jooq.tables.XportStusTran;
import org.jooq.tables.XportStusTyp;


/**
 * Convenience access to all tables in WETRN
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table WETRN.ADMIN_MSG
	 */
	public static final AdminMsg ADMIN_MSG = org.jooq.tables.AdminMsg.ADMIN_MSG;

	/**
	 * The table WETRN.ALT_LINE_NR
	 */
	public static final AltLineNr ALT_LINE_NR = org.jooq.tables.AltLineNr.ALT_LINE_NR;

	/**
	 * The table WETRN.ALT_LINE_NR_UPD
	 */
	public static final AltLineNrUpd ALT_LINE_NR_UPD = org.jooq.tables.AltLineNrUpd.ALT_LINE_NR_UPD;

	/**
	 * The table WETRN.AUDT_MRKT_SKU
	 */
	public static final AudtMrktSku AUDT_MRKT_SKU = org.jooq.tables.AudtMrktSku.AUDT_MRKT_SKU;

	/**
	 * The table WETRN.BB_MRKT_VEH
	 */
	public static final BbMrktVeh BB_MRKT_VEH = org.jooq.tables.BbMrktVeh.BB_MRKT_VEH;

	/**
	 * The table WETRN.BILNG_LINE_NR_DATA
	 */
	public static final BilngLineNrData BILNG_LINE_NR_DATA = org.jooq.tables.BilngLineNrData.BILNG_LINE_NR_DATA;

	/**
	 * The table WETRN.BILNG_LINE_NR_GRP
	 */
	public static final BilngLineNrGrp BILNG_LINE_NR_GRP = org.jooq.tables.BilngLineNrGrp.BILNG_LINE_NR_GRP;

	/**
	 * The table WETRN.BILNG_LINE_NR_GRP_LKUP
	 */
	public static final BilngLineNrGrpLkup BILNG_LINE_NR_GRP_LKUP = org.jooq.tables.BilngLineNrGrpLkup.BILNG_LINE_NR_GRP_LKUP;

	/**
	 * The table WETRN.BILNG_SET_FSC_REUS
	 */
	public static final BilngSetFscReus BILNG_SET_FSC_REUS = org.jooq.tables.BilngSetFscReus.BILNG_SET_FSC_REUS;

	/**
	 * The table WETRN.BILNG_SYS
	 */
	public static final BilngSys BILNG_SYS = org.jooq.tables.BilngSys.BILNG_SYS;

	/**
	 * The table WETRN.BILNG_SYS_LINE_NR_TYP
	 */
	public static final BilngSysLineNrTyp BILNG_SYS_LINE_NR_TYP = org.jooq.tables.BilngSysLineNrTyp.BILNG_SYS_LINE_NR_TYP;

	/**
	 * The table WETRN.BRCHR_LINE_NR
	 */
	public static final BrchrLineNr BRCHR_LINE_NR = org.jooq.tables.BrchrLineNr.BRCHR_LINE_NR;

	/**
	 * Audit trail of changes made via batch assignment or MAPS screens
	 */
	public static final BrchrLineNrAudit BRCHR_LINE_NR_AUDIT = org.jooq.tables.BrchrLineNrAudit.BRCHR_LINE_NR_AUDIT;

	/**
	 * The table WETRN.BRCHR_LINE_NR_GRP
	 */
	public static final BrchrLineNrGrp BRCHR_LINE_NR_GRP = org.jooq.tables.BrchrLineNrGrp.BRCHR_LINE_NR_GRP;

	/**
	 * The table WETRN.BRCHR_LINE_NR_GRP_LKUP
	 */
	public static final BrchrLineNrGrpLkup BRCHR_LINE_NR_GRP_LKUP = org.jooq.tables.BrchrLineNrGrpLkup.BRCHR_LINE_NR_GRP_LKUP;

	/**
	 * Audit trail of changes made via MAPS Brochure Line Number Re-Assignment Screen
	 */
	public static final BrchrLineNrReassignAudit BRCHR_LINE_NR_REASSIGN_AUDIT = org.jooq.tables.BrchrLineNrReassignAudit.BRCHR_LINE_NR_REASSIGN_AUDIT;

	/**
	 * The table WETRN.BRCHR_LINE_NR_TYP
	 */
	public static final BrchrLineNrTyp BRCHR_LINE_NR_TYP = org.jooq.tables.BrchrLineNrTyp.BRCHR_LINE_NR_TYP;

	/**
	 * The table WETRN.BRCHR_LINE_NR_TYP_LKUP
	 */
	public static final BrchrLineNrTypLkup BRCHR_LINE_NR_TYP_LKUP = org.jooq.tables.BrchrLineNrTypLkup.BRCHR_LINE_NR_TYP_LKUP;

	/**
	 * Defines valid combinations of LINE_NR_TYP_ID and BRCHR_LINE_NR_GRP_ID with campaigns-before-reuse value
	 */
	public static final BrchrLineNrTypMtrx BRCHR_LINE_NR_TYP_MTRX = org.jooq.tables.BrchrLineNrTypMtrx.BRCHR_LINE_NR_TYP_MTRX;

	/**
	 * The table WETRN.BRCHR_LINE_NR_UPD
	 */
	public static final BrchrLineNrUpd BRCHR_LINE_NR_UPD = org.jooq.tables.BrchrLineNrUpd.BRCHR_LINE_NR_UPD;

	/**
	 * The table WETRN.BRCHR_PLCMT
	 */
	public static final BrchrPlcmt BRCHR_PLCMT = org.jooq.tables.BrchrPlcmt.BRCHR_PLCMT;

	/**
	 * The table WETRN.BRCHR_POSTN
	 */
	public static final BrchrPostn BRCHR_POSTN = org.jooq.tables.BrchrPostn.BRCHR_POSTN;

	/**
	 * The table WETRN.BRNCH
	 */
	public static final Brnch BRNCH = org.jooq.tables.Brnch.BRNCH;

	/**
	 * The table WETRN.BRNCH_PERD_DSTRBTN
	 */
	public static final BrnchPerdDstrbtn BRNCH_PERD_DSTRBTN = org.jooq.tables.BrnchPerdDstrbtn.BRNCH_PERD_DSTRBTN;

	/**
	 * The table WETRN.BRNCH_SLS
	 */
	public static final BrnchSls BRNCH_SLS = org.jooq.tables.BrnchSls.BRNCH_SLS;

	/**
	 * The table WETRN.BRND
	 */
	public static final Brnd BRND = org.jooq.tables.Brnd.BRND;

	/**
	 * The table WETRN.BRND_FMLY
	 */
	public static final BrndFmly BRND_FMLY = org.jooq.tables.BrndFmly.BRND_FMLY;

	/**
	 * The table WETRN.BRND_GRP
	 */
	public static final BrndGrp BRND_GRP = org.jooq.tables.BrndGrp.BRND_GRP;

	/**
	 * The table WETRN.BRND_POSTNNG
	 */
	public static final BrndPostnng BRND_POSTNNG = org.jooq.tables.BrndPostnng.BRND_POSTNNG;

	/**
	 * The table WETRN.BRND_TYP
	 */
	public static final BrndTyp BRND_TYP = org.jooq.tables.BrndTyp.BRND_TYP;

	/**
	 * Batch job.  There are none, one or many batch jobs in a batch job type.  A batch job groups together tasks that are related but not necessarily dependent on each other.  They may have been submitted as part of one user request.  E.g. Copy offers to market.
	 */
	public static final BtchJob BTCH_JOB = org.jooq.tables.BtchJob.BTCH_JOB;

	/**
	 * Batch job status.  The status of the job.  E.g. 'Scheduled'.
	 */
	public static final BtchJobStus BTCH_JOB_STUS = org.jooq.tables.BtchJobStus.BTCH_JOB_STUS;

	/**
	 * Batch job type.  There are none, one or many batch job types in a batch job type group.
	 */
	public static final BtchJobTyp BTCH_JOB_TYP = org.jooq.tables.BtchJobTyp.BTCH_JOB_TYP;

	/**
	 * Batch job type group.  The group that the batch job type belongs to (for grouping related job types).  Job types within the same job type group should not be run at the same time.
	 */
	public static final BtchJobTypGrp BTCH_JOB_TYP_GRP = org.jooq.tables.BtchJobTypGrp.BTCH_JOB_TYP_GRP;

	/**
	 * Batch task.  There are one or many tasks per job.
	 */
	public static final BtchTask BTCH_TASK = org.jooq.tables.BtchTask.BTCH_TASK;

	/**
	 * Batch task log.  Log for error and information messages.  The BTCH_TASK_LOG_TYP_ID indicates the type of log entry.
	 */
	public static final BtchTaskLog BTCH_TASK_LOG = org.jooq.tables.BtchTaskLog.BTCH_TASK_LOG;

	/**
	 * Batch task log type.  The type of log entry for the batch task.
	 */
	public static final BtchTaskLogTyp BTCH_TASK_LOG_TYP = org.jooq.tables.BtchTaskLogTyp.BTCH_TASK_LOG_TYP;

	/**
	 * Batch task status.  The status of the task.  E.g. 'Running'.
	 */
	public static final BtchTaskStus BTCH_TASK_STUS = org.jooq.tables.BtchTaskStus.BTCH_TASK_STUS;

	/**
	 * Batch task type.  The type of a task.  E.g. 'Copy offer'.  The task type is used to determine the procedure that is responsible for executing the task.
	 */
	public static final BtchTaskTyp BTCH_TASK_TYP = org.jooq.tables.BtchTaskTyp.BTCH_TASK_TYP;

	/**
	 * The table WETRN.BUS
	 */
	public static final Bus BUS = org.jooq.tables.Bus.BUS;

	/**
	 * The table WETRN.CATGRY
	 */
	public static final Catgry CATGRY = org.jooq.tables.Catgry.CATGRY;

	/**
	 * The table WETRN.CATGRY_BRND
	 */
	public static final CatgryBrnd CATGRY_BRND = org.jooq.tables.CatgryBrnd.CATGRY_BRND;

	/**
	 * The table WETRN.CATGRY_FORM
	 */
	public static final CatgryForm CATGRY_FORM = org.jooq.tables.CatgryForm.CATGRY_FORM;

	/**
	 * The table WETRN.CATGRY_SGMT
	 */
	public static final CatgrySgmt CATGRY_SGMT = org.jooq.tables.CatgrySgmt.CATGRY_SGMT;

	/**
	 * The table WETRN.CATGRY_SGMT_FORM
	 */
	public static final CatgrySgmtForm CATGRY_SGMT_FORM = org.jooq.tables.CatgrySgmtForm.CATGRY_SGMT_FORM;

	/**
	 * The table WETRN.CATGRY_SUPLR
	 */
	public static final CatgrySuplr CATGRY_SUPLR = org.jooq.tables.CatgrySuplr.CATGRY_SUPLR;

	/**
	 * Check digit calculation.  Stores the possible check digit calculation codes that are used by pa_maps_public.linedigit_calc().
	 */
	public static final ChkDigtCalcltn CHK_DIGT_CALCLTN = org.jooq.tables.ChkDigtCalcltn.CHK_DIGT_CALCLTN;

	/**
	 * The table WETRN.CHNL
	 */
	public static final Chnl CHNL = org.jooq.tables.Chnl.CHNL;

	/**
	 * The table WETRN.CHOICE_VEH_COPY
	 */
	public static final ChoiceVehCopy CHOICE_VEH_COPY = org.jooq.tables.ChoiceVehCopy.CHOICE_VEH_COPY;

	/**
	 * The table WETRN.CHOICE_VEH_TYP
	 */
	public static final ChoiceVehTyp CHOICE_VEH_TYP = org.jooq.tables.ChoiceVehTyp.CHOICE_VEH_TYP;

	/**
	 * The table WETRN.CLSTR_BRCHR_PLCMT
	 */
	public static final ClstrBrchrPlcmt CLSTR_BRCHR_PLCMT = org.jooq.tables.ClstrBrchrPlcmt.CLSTR_BRCHR_PLCMT;

	/**
	 * The table WETRN.CLSTR_LCL_BUS
	 */
	public static final ClstrLclBus CLSTR_LCL_BUS = org.jooq.tables.ClstrLclBus.CLSTR_LCL_BUS;

	/**
	 * The table WETRN.CLSTR_MRKTG_PROD_RSPBLTY
	 */
	public static final ClstrMrktgProdRspblty CLSTR_MRKTG_PROD_RSPBLTY = org.jooq.tables.ClstrMrktgProdRspblty.CLSTR_MRKTG_PROD_RSPBLTY;

	/**
	 * The table WETRN.CLSTR_SLS_TYP
	 */
	public static final ClstrSlsTyp CLSTR_SLS_TYP = org.jooq.tables.ClstrSlsTyp.CLSTR_SLS_TYP;

	/**
	 * The table WETRN.CLSTR_VEH
	 */
	public static final ClstrVeh CLSTR_VEH = org.jooq.tables.ClstrVeh.CLSTR_VEH;

	/**
	 * The table WETRN.CLSTR_VER
	 */
	public static final ClstrVer CLSTR_VER = org.jooq.tables.ClstrVer.CLSTR_VER;

	/**
	 * The table WETRN.CMPTTN_TYP
	 */
	public static final CmpttnTyp CMPTTN_TYP = org.jooq.tables.CmpttnTyp.CMPTTN_TYP;

	/**
	 * The table WETRN.CMPTTR
	 */
	public static final Cmpttr CMPTTR = org.jooq.tables.Cmpttr.CMPTTR;

	/**
	 * The table WETRN.CMPTTR_PROD_PROMTN
	 */
	public static final CmpttrProdPromtn CMPTTR_PROD_PROMTN = org.jooq.tables.CmpttrProdPromtn.CMPTTR_PROD_PROMTN;

	/**
	 * The table WETRN.CMPTTR_PROD_REG_PRC
	 */
	public static final CmpttrProdRegPrc CMPTTR_PROD_REG_PRC = org.jooq.tables.CmpttrProdRegPrc.CMPTTR_PROD_REG_PRC;

	/**
	 * The table WETRN.CNCPTL_OFFR
	 */
	public static final CncptlOffr CNCPTL_OFFR = org.jooq.tables.CncptlOffr.CNCPTL_OFFR;

	/**
	 * The table WETRN.CNSMR_INVSTMT
	 */
	public static final CnsmrInvstmt CNSMR_INVSTMT = org.jooq.tables.CnsmrInvstmt.CNSMR_INVSTMT;

	/**
	 * The table WETRN.CNSMR_INVSTMT_BDGT
	 */
	public static final CnsmrInvstmtBdgt CNSMR_INVSTMT_BDGT = org.jooq.tables.CnsmrInvstmtBdgt.CNSMR_INVSTMT_BDGT;

	/**
	 * The table WETRN.CNTNT_FORM
	 */
	public static final CntntForm CNTNT_FORM = org.jooq.tables.CntntForm.CNTNT_FORM;

	/**
	 * The table WETRN.COMSN_TYP
	 */
	public static final ComsnTyp COMSN_TYP = org.jooq.tables.ComsnTyp.COMSN_TYP;

	/**
	 * The table WETRN.COMSN_TYP_LKUP
	 */
	public static final ComsnTypLkup COMSN_TYP_LKUP = org.jooq.tables.ComsnTypLkup.COMSN_TYP_LKUP;

	/**
	 * The table WETRN.CONFIG_ITEM
	 */
	public static final ConfigItem CONFIG_ITEM = org.jooq.tables.ConfigItem.CONFIG_ITEM;

	/**
	 * The table WETRN.CONFIG_ITEM_AUDIT
	 */
	public static final ConfigItemAudit CONFIG_ITEM_AUDIT = org.jooq.tables.ConfigItemAudit.CONFIG_ITEM_AUDIT;

	/**
	 * Copy units rule.  The different rules available for copying units between offers.  The offers could be copied between markets, campaigns, vehicles, versions or within the same brochure.
	 */
	public static final CopyUnitsRul COPY_UNITS_RUL = org.jooq.tables.CopyUnitsRul.COPY_UNITS_RUL;

	/**
	 * The table WETRN.CRNCY
	 */
	public static final Crncy CRNCY = org.jooq.tables.Crncy.CRNCY;

	/**
	 * The table WETRN.CUBE_CONFIG
	 */
	public static final CubeConfig CUBE_CONFIG = org.jooq.tables.CubeConfig.CUBE_CONFIG;

	/**
	 * The table WETRN.CUST_GRP
	 */
	public static final CustGrp CUST_GRP = org.jooq.tables.CustGrp.CUST_GRP;

	/**
	 * Customer Pulls are effectively a second Promotion Claim that can optionally be applied to any CENA offer
	 */
	public static final CustPull CUST_PULL = org.jooq.tables.CustPull.CUST_PULL;

	/**
	 * The table WETRN.DAILY_BILLING
	 */
	public static final DailyBilling DAILY_BILLING = org.jooq.tables.DailyBilling.DAILY_BILLING;

	/**
	 * Data exclusion type.  The type of data exclusion being specified.
	 */
	public static final DataXclusnTyp DATA_XCLUSN_TYP = org.jooq.tables.DataXclusnTyp.DATA_XCLUSN_TYP;

	/**
	 * DEMO DISCOUNT - Used to give a description to a Demo Discount e.g. 'Apparel and Accessories' or 'Germany, CFT, Silver' or 'Germany, CFT, Gold'.  A Demo Discount belongs to a Demo Discount Group.  A Demo Discount is associated to an Offer Profile Price Point. Rule: in a Market Campaign, for a Product Default Demo Discount, a Demo Offer must exist for each Demo Discount.
	 */
	public static final DemoDiscnt DEMO_DISCNT = org.jooq.tables.DemoDiscnt.DEMO_DISCNT;

	/**
	 * DEMO DISCOUNT GROUP -  Used to give a description to a Demo Discount grouping e.g. 'Apparel and Accessories' or 'Italy CFT'.  A Demo Discount Group collects together all the Demo Discounts that will be created for a New Offer.  A Demo Discount Group has zero, one or more Demo Discount Rates (but normally one or more).  This group will be used later when deciding which Markets have its Demo Discount Factors.
	 */
	public static final DemoDiscntGrp DEMO_DISCNT_GRP = org.jooq.tables.DemoDiscntGrp.DEMO_DISCNT_GRP;

	/**
	 * The table WETRN.DFALT_PRC_RULE
	 */
	public static final DfaltPrcRule DFALT_PRC_RULE = org.jooq.tables.DfaltPrcRule.DFALT_PRC_RULE;

	/**
	 * The table WETRN.DFLT_MRKT_VEH_COMSN
	 */
	public static final DfltMrktVehComsn DFLT_MRKT_VEH_COMSN = org.jooq.tables.DfltMrktVehComsn.DFLT_MRKT_VEH_COMSN;

	/**
	 * The table WETRN.DFLT_MRKT_VEH_TAX
	 */
	public static final DfltMrktVehTax DFLT_MRKT_VEH_TAX = org.jooq.tables.DfltMrktVehTax.DFLT_MRKT_VEH_TAX;

	/**
	 * The table WETRN.DLTD_BILNG_LINE_NR_DATA
	 */
	public static final DltdBilngLineNrData DLTD_BILNG_LINE_NR_DATA = org.jooq.tables.DltdBilngLineNrData.DLTD_BILNG_LINE_NR_DATA;

	/**
	 * The table WETRN.DLTD_DSTRBTD_MRKT_SLS
	 */
	public static final DltdDstrbtdMrktSls DLTD_DSTRBTD_MRKT_SLS = org.jooq.tables.DltdDstrbtdMrktSls.DLTD_DSTRBTD_MRKT_SLS;

	/**
	 * The table WETRN.DLTD_OFFR
	 */
	public static final DltdOffr DLTD_OFFR = org.jooq.tables.DltdOffr.DLTD_OFFR;

	/**
	 * The table WETRN.DLTD_OFFR_PRFL_PRC_POINT
	 */
	public static final DltdOffrPrflPrcPoint DLTD_OFFR_PRFL_PRC_POINT = org.jooq.tables.DltdOffrPrflPrcPoint.DLTD_OFFR_PRFL_PRC_POINT;

	/**
	 * The table WETRN.DLTD_OFFR_PRFL_SLS_CLS_PLCMT
	 */
	public static final DltdOffrPrflSlsClsPlcmt DLTD_OFFR_PRFL_SLS_CLS_PLCMT = org.jooq.tables.DltdOffrPrflSlsClsPlcmt.DLTD_OFFR_PRFL_SLS_CLS_PLCMT;

	/**
	 * The table WETRN.DLTD_OFFR_SKU_LINE
	 */
	public static final DltdOffrSkuLine DLTD_OFFR_SKU_LINE = org.jooq.tables.DltdOffrSkuLine.DLTD_OFFR_SKU_LINE;

	/**
	 * The table WETRN.DLTD_OFFR_SKU_SET
	 */
	public static final DltdOffrSkuSet DLTD_OFFR_SKU_SET = org.jooq.tables.DltdOffrSkuSet.DLTD_OFFR_SKU_SET;

	/**
	 * The table WETRN.DLTD_OFFR_SLS_CLS_SKU
	 */
	public static final DltdOffrSlsClsSku DLTD_OFFR_SLS_CLS_SKU = org.jooq.tables.DltdOffrSlsClsSku.DLTD_OFFR_SLS_CLS_SKU;

	/**
	 * The table WETRN.DLTD_PLUG_SLS
	 */
	public static final DltdPlugSls DLTD_PLUG_SLS = org.jooq.tables.DltdPlugSls.DLTD_PLUG_SLS;

	/**
	 * Billing data inserted by ODS for sales allocation processing in MAPS.
	 */
	public static final DlyBilng DLY_BILNG = org.jooq.tables.DlyBilng.DLY_BILNG;

	/**
	 * The table WETRN.DLY_BILNG_BKUP
	 */
	public static final DlyBilngBkup DLY_BILNG_BKUP = org.jooq.tables.DlyBilngBkup.DLY_BILNG_BKUP;

	/**
	 * The table WETRN.DLY_BILNG_BKUP_TRNS_TYP
	 */
	public static final DlyBilngBkupTrnsTyp DLY_BILNG_BKUP_TRNS_TYP = org.jooq.tables.DlyBilngBkupTrnsTyp.DLY_BILNG_BKUP_TRNS_TYP;

	/**
	 * Daily billing control.  Set of billing system rules for each DLY_BILNG_MTCH_ID.  Either a different billing system or change to interface file or possible attribute values.  MRKT_EFF_SLS_PERD.DLY_BILNG_MTCH_ID indicates which DLY_BILNG_MTCH is used by which markets for which sales periods.  Many markets can use the same DLY_BILNG_MTCH.  Many DLY_BILNG_MTCH can be used by the same market for different sales periods.  E.g. when changing from one set of matching rules to another or from one system to another.
	 */
	public static final DlyBilngCntrl DLY_BILNG_CNTRL = org.jooq.tables.DlyBilngCntrl.DLY_BILNG_CNTRL;

	/**
	 * The table WETRN.DLY_BILNG_CNTRL_AUDIT
	 */
	public static final DlyBilngCntrlAudit DLY_BILNG_CNTRL_AUDIT = org.jooq.tables.DlyBilngCntrlAudit.DLY_BILNG_CNTRL_AUDIT;

	/**
	 * Daily Billing FSC Split.  Data provided by the users to indicate how one (dummy) FSC is to be split into many valid FSCs.  The sum of original units in dly_bilng are split across the target FSCs according to the ratio of units in dly_bilng_fsc_splt for the same SRCE_FSC,SLS_PRC,NR_FOR.
	 */
	public static final DlyBilngFscSplt DLY_BILNG_FSC_SPLT = org.jooq.tables.DlyBilngFscSplt.DLY_BILNG_FSC_SPLT;

	/**
	 * Daily billing match identifies a unique set of daily billing matching rules.  Either a different billing system or change to interface file or change to set of rules.  MRKT_EFF_SLS_PERD.DLY_BILNG_MTCH_ID indicates which DLY_BILNG_MTCH set of rules is used by which markets for which sales periods.  Many markets can use the same DLY_BILNG_MTCH.  Many DLY_BILNG_MTCH can be used by the same market for different sales periods.  E.g. when changing from one set of matching rules to another or from one system to another.  DLY_BILNG_MTCH_ID must be unique globally if the matching rules are different.
	 */
	public static final DlyBilngMtch DLY_BILNG_MTCH = org.jooq.tables.DlyBilngMtch.DLY_BILNG_MTCH;

	/**
	 * The table WETRN.DLY_BILNG_MTCH_AUDIT
	 */
	public static final DlyBilngMtchAudit DLY_BILNG_MTCH_AUDIT = org.jooq.tables.DlyBilngMtchAudit.DLY_BILNG_MTCH_AUDIT;

	/**
	 * Unit split and mapping between billing data and offers.  Data retained after matching for force matched (and related) rows.
	 */
	public static final DlyBilngOffrSkuLine DLY_BILNG_OFFR_SKU_LINE = org.jooq.tables.DlyBilngOffrSkuLine.DLY_BILNG_OFFR_SKU_LINE;

	/**
	 * The table WETRN.DLY_BILNG_OFFR_SKU_LINE_OLD
	 */
	public static final DlyBilngOffrSkuLineOld DLY_BILNG_OFFR_SKU_LINE_OLD = org.jooq.tables.DlyBilngOffrSkuLineOld.DLY_BILNG_OFFR_SKU_LINE_OLD;

	/**
	 * Audit Trail table populated during the Sales Allocation process to record possible OSL matches for a daily billing record
	 */
	public static final DlyBilngOslAudit DLY_BILNG_OSL_AUDIT = org.jooq.tables.DlyBilngOslAudit.DLY_BILNG_OSL_AUDIT;

	/**
	 * Temporary table used during the Sales Allocation process to hold possible OSL matches for a daily billing record
	 */
	public static final DlyBilngOslTemp DLY_BILNG_OSL_TEMP = org.jooq.tables.DlyBilngOslTemp.DLY_BILNG_OSL_TEMP;

	/**
	 * Temporary table used during the Sales Allocation process to hold status/sku data for a daily billing record
	 */
	public static final DlyBilngTemp DLY_BILNG_TEMP = org.jooq.tables.DlyBilngTemp.DLY_BILNG_TEMP;

	/**
	 * The table WETRN.DLY_BILNG_TRND
	 */
	public static final DlyBilngTrnd DLY_BILNG_TRND = org.jooq.tables.DlyBilngTrnd.DLY_BILNG_TRND;

	/**
	 * The table WETRN.DLY_BILNG_TRND_CNTRL
	 */
	public static final DlyBilngTrndCntrl DLY_BILNG_TRND_CNTRL = org.jooq.tables.DlyBilngTrndCntrl.DLY_BILNG_TRND_CNTRL;

	/**
	 * The table WETRN.DLY_BILNG_TRND_MTCH
	 */
	public static final DlyBilngTrndMtch DLY_BILNG_TRND_MTCH = org.jooq.tables.DlyBilngTrndMtch.DLY_BILNG_TRND_MTCH;

	/**
	 * The table WETRN.DLY_BILNG_TRND_OFFR_SKU_LINE
	 */
	public static final DlyBilngTrndOffrSkuLine DLY_BILNG_TRND_OFFR_SKU_LINE = org.jooq.tables.DlyBilngTrndOffrSkuLine.DLY_BILNG_TRND_OFFR_SKU_LINE;

	/**
	 * The table WETRN.DLY_BILNG_TRND_OSL_AUDIT
	 */
	public static final DlyBilngTrndOslAudit DLY_BILNG_TRND_OSL_AUDIT = org.jooq.tables.DlyBilngTrndOslAudit.DLY_BILNG_TRND_OSL_AUDIT;

	/**
	 * Temporary table used during the Trend Allocation process to hold possible OSL matches for a daily billing trend record
	 */
	public static final DlyBilngTrndOslTemp DLY_BILNG_TRND_OSL_TEMP = org.jooq.tables.DlyBilngTrndOslTemp.DLY_BILNG_TRND_OSL_TEMP;

	/**
	 * The table WETRN.DLY_BILNG_TRND_TEMP
	 */
	public static final DlyBilngTrndTemp DLY_BILNG_TRND_TEMP = org.jooq.tables.DlyBilngTrndTemp.DLY_BILNG_TRND_TEMP;

	/**
	 * The table WETRN.DSTRBTD_BRNCH_SLS
	 */
	public static final DstrbtdBrnchSls DSTRBTD_BRNCH_SLS = org.jooq.tables.DstrbtdBrnchSls.DSTRBTD_BRNCH_SLS;

	/**
	 * The table WETRN.DSTRBTD_MRKT_SLS
	 */
	public static final DstrbtdMrktSls DSTRBTD_MRKT_SLS = org.jooq.tables.DstrbtdMrktSls.DSTRBTD_MRKT_SLS;

	/**
	 * The table WETRN.ENRGY_CHRT
	 */
	public static final EnrgyChrt ENRGY_CHRT = org.jooq.tables.EnrgyChrt.ENRGY_CHRT;

	/**
	 * The table WETRN.ENRGY_CHRT_POSTN
	 */
	public static final EnrgyChrtPostn ENRGY_CHRT_POSTN = org.jooq.tables.EnrgyChrtPostn.ENRGY_CHRT_POSTN;

	/**
	 * The table WETRN.ERR_LOG
	 */
	public static final ErrLog ERR_LOG = org.jooq.tables.ErrLog.ERR_LOG;

	/**
	 * The table WETRN.EST_LINK
	 */
	public static final EstLink EST_LINK = org.jooq.tables.EstLink.EST_LINK;

	/**
	 * The table WETRN.EST_LNKG
	 */
	public static final EstLnkg EST_LNKG = org.jooq.tables.EstLnkg.EST_LNKG;

	/**
	 * The table WETRN.EST_ON_DMND
	 */
	public static final EstOnDmnd EST_ON_DMND = org.jooq.tables.EstOnDmnd.EST_ON_DMND;

	/**
	 * The table WETRN.EST_TRND_EXCPTN
	 */
	public static final EstTrndExcptn EST_TRND_EXCPTN = org.jooq.tables.EstTrndExcptn.EST_TRND_EXCPTN;

	/**
	 * Purpose: within the MAPS Marketing system, store the Weighting (importance) Types for use in the Demand Planning process.  These are the weighting types available when deciding which historical Campaigns to use in calculating Demand Units.  Note that this is not the same metric as the MAPS screen Real Weighting field.-- Note: this is static data, it is not proposed to develop a screen to maintain this data.  Instead this will be configured by the MAPS IT team.

	 */
	public static final EstWghtTyp EST_WGHT_TYP = org.jooq.tables.EstWghtTyp.EST_WGHT_TYP;

	/**
	 * The table WETRN.FINCL_OBJCTV
	 */
	public static final FinclObjctv FINCL_OBJCTV = org.jooq.tables.FinclObjctv.FINCL_OBJCTV;

	/**
	 * The table WETRN.FINCL_VER
	 */
	public static final FinclVer FINCL_VER = org.jooq.tables.FinclVer.FINCL_VER;

	/**
	 * The table WETRN.FORM
	 */
	public static final Form FORM = org.jooq.tables.Form.FORM;

	/**
	 * The table WETRN.FORM_GRP
	 */
	public static final FormGrp FORM_GRP = org.jooq.tables.FormGrp.FORM_GRP;

	/**
	 * Forecast boost exclusion.  This is for exclusions in the target market (not source market).  Vehicle exclusions in the source market are by exclusion in the multiselect drop down list in the copy offer screen.  A null vehicle assumes all vehicles for the specified sales class.  A null sales class assumes all sales classes for the specified vehicle.  veh_id and sls_cls_cd must not both be null.  Therefore, offers are excluded where mvpv.veh_id = nvl(fbx.veh_id, mvpv.veh_id) and x.sls_cls_cd = nvl(fbx.sls_cls_cd, x.sls_cls_cd).
	 */
	public static final FrcstBoostXclusn FRCST_BOOST_XCLUSN = org.jooq.tables.FrcstBoostXclusn.FRCST_BOOST_XCLUSN;

	/**
	 * Force match options for offers.
	 */
	public static final FrcMtchMthd FRC_MTCH_MTHD = org.jooq.tables.FrcMtchMthd.FRC_MTCH_MTHD;

	/**
	 * The table WETRN.GENDR
	 */
	public static final Gendr GENDR = org.jooq.tables.Gendr.GENDR;

	/**
	 * The table WETRN.GENDR_SPLT_CATGRY
	 */
	public static final GendrSpltCatgry GENDR_SPLT_CATGRY = org.jooq.tables.GendrSpltCatgry.GENDR_SPLT_CATGRY;

	/**
	 * The table WETRN.GTA_MTHD
	 */
	public static final GtaMthd GTA_MTHD = org.jooq.tables.GtaMthd.GTA_MTHD;

	/**
	 * The Daily Billing reports have to show the correct FSC Descriptions for the cluster level FSCs too. This table contains these special records (mappings) to make the look up (sub-select) in the report eaiser (faster). 
	 */
	public static final GttDlyBilngRpt GTT_DLY_BILNG_RPT = org.jooq.tables.GttDlyBilngRpt.GTT_DLY_BILNG_RPT;

	/**
	 * Identifies the type of Data to be used
	 */
	public static final ImgDataTyp IMG_DATA_TYP = org.jooq.tables.ImgDataTyp.IMG_DATA_TYP;

	/**
	 * The format of the Image File itself.  As seen in the Filename suffix. Normally .jpeg or .gif.
	 */
	public static final ImgFileTyp IMG_FILE_TYP = org.jooq.tables.ImgFileTyp.IMG_FILE_TYP;

	/**
	 * Used by the MAPS application to transform a part of the Image Filename to a MAPS Standard Data value.
	 */
	public static final ImgImprtDataMapg IMG_IMPRT_DATA_MAPG = org.jooq.tables.ImgImprtDataMapg.IMG_IMPRT_DATA_MAPG;

	/**
	 * Used by the MAPS application to identify part of the Image Filename as a data item.
	 */
	public static final ImgImprtDataPostn IMG_IMPRT_DATA_POSTN = org.jooq.tables.ImgImprtDataPostn.IMG_IMPRT_DATA_POSTN;

	/**
	 * The table WETRN.IMPDP
	 */
	public static final Impdp IMPDP = org.jooq.tables.Impdp.IMPDP;

	/**
	 * The table WETRN.IMPDP_LOG
	 */
	public static final ImpdpLog IMPDP_LOG = org.jooq.tables.ImpdpLog.IMPDP_LOG;

	/**
	 * The table WETRN.IMPDP_MASTER
	 */
	public static final ImpdpMaster IMPDP_MASTER = org.jooq.tables.ImpdpMaster.IMPDP_MASTER;

	/**
	 * The table WETRN.IMPDP_STATS
	 */
	public static final ImpdpStats IMPDP_STATS = org.jooq.tables.ImpdpStats.IMPDP_STATS;

	/**
	 * The table WETRN.INCNTV
	 */
	public static final Incntv INCNTV = org.jooq.tables.Incntv.INCNTV;

	/**
	 * The table WETRN.INCREMENTALS_LOG
	 */
	public static final IncrementalsLog INCREMENTALS_LOG = org.jooq.tables.IncrementalsLog.INCREMENTALS_LOG;

	/**
	 * The table WETRN.INTRFC_CNTRL
	 */
	public static final IntrfcCntrl INTRFC_CNTRL = org.jooq.tables.IntrfcCntrl.INTRFC_CNTRL;

	/**
	 * The table WETRN.INTRFC_MRKT_FSC
	 */
	public static final IntrfcMrktFsc INTRFC_MRKT_FSC = org.jooq.tables.IntrfcMrktFsc.INTRFC_MRKT_FSC;

	/**
	 * The table WETRN.INTRFC_SYS
	 */
	public static final IntrfcSys INTRFC_SYS = org.jooq.tables.IntrfcSys.INTRFC_SYS;

	/**
	 * The table WETRN.INTRFC_SYS_TPC
	 */
	public static final IntrfcSysTpc INTRFC_SYS_TPC = org.jooq.tables.IntrfcSysTpc.INTRFC_SYS_TPC;

	/**
	 * The table WETRN.ITEM_LINE_NR_TYP
	 */
	public static final ItemLineNrTyp ITEM_LINE_NR_TYP = org.jooq.tables.ItemLineNrTyp.ITEM_LINE_NR_TYP;

	/**
	 * The table WETRN.ITEM_TYP
	 */
	public static final ItemTyp ITEM_TYP = org.jooq.tables.ItemTyp.ITEM_TYP;

	/**
	 * The table WETRN.LCL_BUS_OFFR_CLS
	 */
	public static final LclBusOffrCls LCL_BUS_OFFR_CLS = org.jooq.tables.LclBusOffrCls.LCL_BUS_OFFR_CLS;

	/**
	 * The table WETRN.LCL_BUS_OFFR_CLS_PERD_VER
	 */
	public static final LclBusOffrClsPerdVer LCL_BUS_OFFR_CLS_PERD_VER = org.jooq.tables.LclBusOffrClsPerdVer.LCL_BUS_OFFR_CLS_PERD_VER;

	/**
	 * The table WETRN.LCL_CHNL
	 */
	public static final LclChnl LCL_CHNL = org.jooq.tables.LclChnl.LCL_CHNL;

	/**
	 * The table WETRN.LCL_CHNL_AUDIT
	 */
	public static final LclChnlAudit LCL_CHNL_AUDIT = org.jooq.tables.LclChnlAudit.LCL_CHNL_AUDIT;

	/**
	 * The table WETRN.LEAD_BUS_DIV
	 */
	public static final LeadBusDiv LEAD_BUS_DIV = org.jooq.tables.LeadBusDiv.LEAD_BUS_DIV;

	/**
	 * Defines assignment methods for brochure line numbers eg get free, reuse rule 1 etc
	 */
	public static final LineNrAsgnmtTyp LINE_NR_ASGNMT_TYP = org.jooq.tables.LineNrAsgnmtTyp.LINE_NR_ASGNMT_TYP;

	/**
	 * The table WETRN.LINE_NR_TYP
	 */
	public static final LineNrTyp LINE_NR_TYP = org.jooq.tables.LineNrTyp.LINE_NR_TYP;

	/**
	 * The table WETRN.LINE_NR_TYP_CD
	 */
	public static final LineNrTypCd LINE_NR_TYP_CD = org.jooq.tables.LineNrTypCd.LINE_NR_TYP_CD;

	/**
	 * Audit trail of upgrade/backout scripts applied to a MAPS Database
	 */
	public static final MapsDbUpgrade MAPS_DB_UPGRADE = org.jooq.tables.MapsDbUpgrade.MAPS_DB_UPGRADE;

	/**
	 * The table WETRN.MAPS_ERR_MSG
	 */
	public static final MapsErrMsg MAPS_ERR_MSG = org.jooq.tables.MapsErrMsg.MAPS_ERR_MSG;

	/**
	 * Error codes and messages returned from MAPS stored PL/SQL
	 */
	public static final MapsMenuItem MAPS_MENU_ITEM = org.jooq.tables.MapsMenuItem.MAPS_MENU_ITEM;

	/**
	 * MAPS semaphore.  Locking table for any procedure or function to use.  Procedures can use this to prevent instances of themselves running at the same time in another session by selecting where maps_smphr_cd = <procedure name> for update.  The code between the select and commit/rollback will then be the only instance of this code running in any session.
	 */
	public static final MapsSmphr MAPS_SMPHR = org.jooq.tables.MapsSmphr.MAPS_SMPHR;

	/**
	 * The table WETRN.MESSAGE_TRANSACTION
	 */
	public static final MessageTransaction MESSAGE_TRANSACTION = org.jooq.tables.MessageTransaction.MESSAGE_TRANSACTION;

	/**
	 * The table WETRN.MESSAGE_TRANSACTION_ROW
	 */
	public static final MessageTransactionRow MESSAGE_TRANSACTION_ROW = org.jooq.tables.MessageTransactionRow.MESSAGE_TRANSACTION_ROW;

	/**
	 * The table WETRN.MISSING_SLS_CLS_PLCMT
	 */
	public static final MissingSlsClsPlcmt MISSING_SLS_CLS_PLCMT = org.jooq.tables.MissingSlsClsPlcmt.MISSING_SLS_CLS_PLCMT;

	/**
	 * The table WETRN.MPS_OBJ
	 */
	public static final MpsObj MPS_OBJ = org.jooq.tables.MpsObj.MPS_OBJ;

	/**
	 * The table WETRN.MPS_PARM
	 */
	public static final MpsParm MPS_PARM = org.jooq.tables.MpsParm.MPS_PARM;

	/**
	 * The table WETRN.MPS_PARM_OFFR
	 */
	public static final MpsParmOffr MPS_PARM_OFFR = org.jooq.tables.MpsParmOffr.MPS_PARM_OFFR;

	/**
	 * The table WETRN.MPS_PARM_REPLCTN_MOV_MRKT
	 */
	public static final MpsParmReplctnMovMrkt MPS_PARM_REPLCTN_MOV_MRKT = org.jooq.tables.MpsParmReplctnMovMrkt.MPS_PARM_REPLCTN_MOV_MRKT;

	/**
	 * The table WETRN.MPS_PARM_SRCE_OFFR_PERD
	 */
	public static final MpsParmSrceOffrPerd MPS_PARM_SRCE_OFFR_PERD = org.jooq.tables.MpsParmSrceOffrPerd.MPS_PARM_SRCE_OFFR_PERD;

	/**
	 * The table WETRN.MPS_PARM_SRCE_SLS_PERD
	 */
	public static final MpsParmSrceSlsPerd MPS_PARM_SRCE_SLS_PERD = org.jooq.tables.MpsParmSrceSlsPerd.MPS_PARM_SRCE_SLS_PERD;

	/**
	 * The table WETRN.MPS_PARM_SRCE_VEH
	 */
	public static final MpsParmSrceVeh MPS_PARM_SRCE_VEH = org.jooq.tables.MpsParmSrceVeh.MPS_PARM_SRCE_VEH;

	/**
	 * The table WETRN.MPS_PARM_TRGT_MRKT
	 */
	public static final MpsParmTrgtMrkt MPS_PARM_TRGT_MRKT = org.jooq.tables.MpsParmTrgtMrkt.MPS_PARM_TRGT_MRKT;

	/**
	 * The table WETRN.MPS_PARM_TRGT_OFFR_PERD
	 */
	public static final MpsParmTrgtOffrPerd MPS_PARM_TRGT_OFFR_PERD = org.jooq.tables.MpsParmTrgtOffrPerd.MPS_PARM_TRGT_OFFR_PERD;

	/**
	 * The table WETRN.MPS_PARM_TRGT_SLS_PERD
	 */
	public static final MpsParmTrgtSlsPerd MPS_PARM_TRGT_SLS_PERD = org.jooq.tables.MpsParmTrgtSlsPerd.MPS_PARM_TRGT_SLS_PERD;

	/**
	 * The table WETRN.MPS_PARM_TRGT_VEH
	 */
	public static final MpsParmTrgtVeh MPS_PARM_TRGT_VEH = org.jooq.tables.MpsParmTrgtVeh.MPS_PARM_TRGT_VEH;

	/**
	 * The table WETRN.MPS_PARM_TRGT_VER
	 */
	public static final MpsParmTrgtVer MPS_PARM_TRGT_VER = org.jooq.tables.MpsParmTrgtVer.MPS_PARM_TRGT_VER;

	/**
	 * The table WETRN.MPS_PLSQL_LOG
	 */
	public static final MpsPlsqlLog MPS_PLSQL_LOG = org.jooq.tables.MpsPlsqlLog.MPS_PLSQL_LOG;

	/**
	 * The table WETRN.MPS_PLSQL_OUTPUT
	 */
	public static final MpsPlsqlOutput MPS_PLSQL_OUTPUT = org.jooq.tables.MpsPlsqlOutput.MPS_PLSQL_OUTPUT;

	/**
	 * The table WETRN.MPS_RL
	 */
	public static final MpsRl MPS_RL = org.jooq.tables.MpsRl.MPS_RL;

	/**
	 * The table WETRN.MPS_SYS
	 */
	public static final MpsSys MPS_SYS = org.jooq.tables.MpsSys.MPS_SYS;

	/**
	 * The table WETRN.MPS_USER
	 */
	public static final MpsUser MPS_USER = org.jooq.tables.MpsUser.MPS_USER;

	/**
	 * The table WETRN.MPS_USER_CATGRY_ACS
	 */
	public static final MpsUserCatgryAcs MPS_USER_CATGRY_ACS = org.jooq.tables.MpsUserCatgryAcs.MPS_USER_CATGRY_ACS;

	/**
	 * The table WETRN.MPS_USER_GRP
	 */
	public static final MpsUserGrp MPS_USER_GRP = org.jooq.tables.MpsUserGrp.MPS_USER_GRP;

	/**
	 * The table WETRN.MPS_USER_GRP_OBJ
	 */
	public static final MpsUserGrpObj MPS_USER_GRP_OBJ = org.jooq.tables.MpsUserGrpObj.MPS_USER_GRP_OBJ;

	/**
	 * The table WETRN.MPS_USER_GRP_USER
	 */
	public static final MpsUserGrpUser MPS_USER_GRP_USER = org.jooq.tables.MpsUserGrpUser.MPS_USER_GRP_USER;

	/**
	 * The table WETRN.MPS_USER_MRKT_ACS
	 */
	public static final MpsUserMrktAcs MPS_USER_MRKT_ACS = org.jooq.tables.MpsUserMrktAcs.MPS_USER_MRKT_ACS;

	/**
	 * The table WETRN.MPS_USER_MRKT_VEH_ACS
	 */
	public static final MpsUserMrktVehAcs MPS_USER_MRKT_VEH_ACS = org.jooq.tables.MpsUserMrktVehAcs.MPS_USER_MRKT_VEH_ACS;

	/**
	 * The table WETRN.MPS_USER_RL
	 */
	public static final MpsUserRl MPS_USER_RL = org.jooq.tables.MpsUserRl.MPS_USER_RL;

	/**
	 * The table WETRN.MPS_USER_RL_MRKT_ACS
	 */
	public static final MpsUserRlMrktAcs MPS_USER_RL_MRKT_ACS = org.jooq.tables.MpsUserRlMrktAcs.MPS_USER_RL_MRKT_ACS;

	/**
	 * The table WETRN.MRKT
	 */
	public static final Mrkt MRKT = org.jooq.tables.Mrkt.MRKT;

	/**
	 * snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_BRND
	 */
	public static final MrktgProdRspbltyBrnd MRKTG_PROD_RSPBLTY_BRND = org.jooq.tables.MrktgProdRspbltyBrnd.MRKTG_PROD_RSPBLTY_BRND;

	/**
	 * snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_BRND_FMLY
	 */
	public static final MrktgProdRspbltyBrndFmly MRKTG_PROD_RSPBLTY_BRND_FMLY = org.jooq.tables.MrktgProdRspbltyBrndFmly.MRKTG_PROD_RSPBLTY_BRND_FMLY;

	/**
	 * snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_CATGRY
	 */
	public static final MrktgProdRspbltyCatgry MRKTG_PROD_RSPBLTY_CATGRY = org.jooq.tables.MrktgProdRspbltyCatgry.MRKTG_PROD_RSPBLTY_CATGRY;

	/**
	 * snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_FORM
	 */
	public static final MrktgProdRspbltyForm MRKTG_PROD_RSPBLTY_FORM = org.jooq.tables.MrktgProdRspbltyForm.MRKTG_PROD_RSPBLTY_FORM;

	/**
	 * snapshot table for snapshot ESCON.MRKTG_PROD_RSPBLTY_SGMT
	 */
	public static final MrktgProdRspbltySgmt MRKTG_PROD_RSPBLTY_SGMT = org.jooq.tables.MrktgProdRspbltySgmt.MRKTG_PROD_RSPBLTY_SGMT;

	/**
	 * The table WETRN.MRKTG_PROD_RSPBLTY_SUPLR
	 */
	public static final MrktgProdRspbltySuplr MRKTG_PROD_RSPBLTY_SUPLR = org.jooq.tables.MrktgProdRspbltySuplr.MRKTG_PROD_RSPBLTY_SUPLR;

	/**
	 * Holds list of valid FGC codes for Marketing Sets in a Market
	 */
	public static final MrktngSetFgc MRKTNG_SET_FGC = org.jooq.tables.MrktngSetFgc.MRKTNG_SET_FGC;

	/**
	 * Holds history of FGC assignment for Marketing Sets in a Market
	 */
	public static final MrktngSetFgcHist MRKTNG_SET_FGC_HIST = org.jooq.tables.MrktngSetFgcHist.MRKTNG_SET_FGC_HIST;

	/**
	 * The table WETRN.MRKT_BILNG_SYS
	 */
	public static final MrktBilngSys MRKT_BILNG_SYS = org.jooq.tables.MrktBilngSys.MRKT_BILNG_SYS;

	/**
	 * The table WETRN.MRKT_BRNCH_DSTRBTN
	 */
	public static final MrktBrnchDstrbtn MRKT_BRNCH_DSTRBTN = org.jooq.tables.MrktBrnchDstrbtn.MRKT_BRNCH_DSTRBTN;

	/**
	 * The table WETRN.MRKT_CMPTTR
	 */
	public static final MrktCmpttr MRKT_CMPTTR = org.jooq.tables.MrktCmpttr.MRKT_CMPTTR;

	/**
	 * The table WETRN.MRKT_CMPTTR_CATGRY
	 */
	public static final MrktCmpttrCatgry MRKT_CMPTTR_CATGRY = org.jooq.tables.MrktCmpttrCatgry.MRKT_CMPTTR_CATGRY;

	/**
	 * The table WETRN.MRKT_CMPTTR_PROD
	 */
	public static final MrktCmpttrProd MRKT_CMPTTR_PROD = org.jooq.tables.MrktCmpttrProd.MRKT_CMPTTR_PROD;

	/**
	 * The table WETRN.MRKT_CMPTTR_PROD_PRFL
	 */
	public static final MrktCmpttrProdPrfl MRKT_CMPTTR_PROD_PRFL = org.jooq.tables.MrktCmpttrProdPrfl.MRKT_CMPTTR_PROD_PRFL;

	/**
	 * The table WETRN.MRKT_CNSMR_INVSTMT_BDGT_WSL
	 */
	public static final MrktCnsmrInvstmtBdgtWsl MRKT_CNSMR_INVSTMT_BDGT_WSL = org.jooq.tables.MrktCnsmrInvstmtBdgtWsl.MRKT_CNSMR_INVSTMT_BDGT_WSL;

	/**
	 * The table WETRN.MRKT_COMSN_TYP
	 */
	public static final MrktComsnTyp MRKT_COMSN_TYP = org.jooq.tables.MrktComsnTyp.MRKT_COMSN_TYP;

	/**
	 * The table WETRN.MRKT_COMSN_TYP_EFF_PERD
	 */
	public static final MrktComsnTypEffPerd MRKT_COMSN_TYP_EFF_PERD = org.jooq.tables.MrktComsnTypEffPerd.MRKT_COMSN_TYP_EFF_PERD;

	/**
	 * The table WETRN.MRKT_COMSN_TYP_LKUP
	 */
	public static final MrktComsnTypLkup MRKT_COMSN_TYP_LKUP = org.jooq.tables.MrktComsnTypLkup.MRKT_COMSN_TYP_LKUP;

	/**
	 * The table WETRN.MRKT_CONFIG_ITEM
	 */
	public static final MrktConfigItem MRKT_CONFIG_ITEM = org.jooq.tables.MrktConfigItem.MRKT_CONFIG_ITEM;

	/**
	 * The table WETRN.MRKT_CONFIG_ITEM_AUDIT
	 */
	public static final MrktConfigItemAudit MRKT_CONFIG_ITEM_AUDIT = org.jooq.tables.MrktConfigItemAudit.MRKT_CONFIG_ITEM_AUDIT;

	/**
	 * Market Demo Discount Factor is a Demo Discount % for a single Market, e.g. 0.7 for Germany for 'CFT - Silver', or 0.6 for Germany for 'CFT - Gold'.  A Market Demo Discount Factor belongs to a Demo Discount.  A Market Demo Discount Factor is a % rate that represents the % of the Selling Price of the New Offer.  So, a Free Demo Offer would have a Market Demo Discount Factor of 0, and a Demo Offer for the same Price as the New Offer would have a factor of 100%. A Market Demo Discount Factor has an Effective Start Campaign and an Effective End Campaign, this allows the % to vary over time.  For example from C5 2010 onwards (with blank End Campaign) Spain will change its 'CFT - Silver' from 0.7000 to 0.6900.  The Effective Start Campaign refers to the New Campaign not the Demo Campaign. Not all Markets use all Demo Discounts.  In CENA, most Demo Discounts apply to a single Market.  In CENA, some Markets have many Demo Discounts in a single Campaign.
Commission Removal Indicator, identifies whether the Selling Price of the Demo Offer should be calculated by removing the Commission from the New Offer (uses the Commission Type stored in the Offer Profile Price Point to calculate this).   Instead of entering a Market Demo Discount Factor, alternatively the Commission Removal Indicator is set.  If the Commission Removal Indicator is set this means that whatever the Commission % rate is for the New Offer then this will be deducted from the New Selling Price in order to calculate the Demo Selling Price.
	 */
	public static final MrktDemoDiscntFct MRKT_DEMO_DISCNT_FCT = org.jooq.tables.MrktDemoDiscntFct.MRKT_DEMO_DISCNT_FCT;

	/**
	 * MARKET DEMO DISCOUNT LOOKUP - an Offer Product classification, from the following list: Product Type, Business, Category, Segment, Form Group, Form, Lead Business, Concept Number, Commission Type. Note: all fields above are single selection only. A Product Default Demo Discount has the attribute(s): Demo Discount Group, this identifies the Demo Discount Offers that should be created in each Demo Market Campaign. Technical Note: uses table Market Demo Discount Lookup.
	 */
	public static final MrktDemoDiscntLkup MRKT_DEMO_DISCNT_LKUP = org.jooq.tables.MrktDemoDiscntLkup.MRKT_DEMO_DISCNT_LKUP;

	/**
	 * Market effective offer period line number.  Stores the values used for line number length and check digit calculation.
	 */
	public static final MrktEffOffrPerdLineNr MRKT_EFF_OFFR_PERD_LINE_NR = org.jooq.tables.MrktEffOffrPerdLineNr.MRKT_EFF_OFFR_PERD_LINE_NR;

	/**
	 * Parameters at MRKT+SLS_PERD level that do not change every SLS_PERD.  De-normalised table containing all parameters at this level that would be in individual tables if fully normalised.  Any parameters not changing must be copied to the new row where a parameter is changing.
	 */
	public static final MrktEffSlsPerd MRKT_EFF_SLS_PERD = org.jooq.tables.MrktEffSlsPerd.MRKT_EFF_SLS_PERD;

	/**
	 * The table WETRN.MRKT_EFF_SLS_PERD_AUDIT
	 */
	public static final MrktEffSlsPerdAudit MRKT_EFF_SLS_PERD_AUDIT = org.jooq.tables.MrktEffSlsPerdAudit.MRKT_EFF_SLS_PERD_AUDIT;

	/**
	 * The table WETRN.MRKT_EFF_TRND_SLS_PERD
	 */
	public static final MrktEffTrndSlsPerd MRKT_EFF_TRND_SLS_PERD = org.jooq.tables.MrktEffTrndSlsPerd.MRKT_EFF_TRND_SLS_PERD;

	/**
	 * Purpose: within the MAPS Marketing system, store the Estimate Relative Weighting Percentage (importance) for a Campaign.  The Campaign is stored here as a relative campaign i.e. starting at the latest Offset Anchor Sales Type (for example the latest Actual campaign), for the campaign that is offset by the number of plus or minus campaigns.  These are the weighting's to be applied to this campaign. -- Note: this Relative Weighting Percentage information is used to calculate the Real Weighting Percentage which can be viewed by the MAPS user in the MAPS Demand Planning screens when estimating Units demand for an Offer Concept. Because this is static data, it is not proposed to develop a screen to maintain this data.  Instead this will be configured by the MAPS IT team.
	 */
	public static final MrktEstWght MRKT_EST_WGHT = org.jooq.tables.MrktEstWght.MRKT_EST_WGHT;

	/**
	 * The table WETRN.MRKT_FSC
	 */
	public static final MrktFsc MRKT_FSC = org.jooq.tables.MrktFsc.MRKT_FSC;

	/**
	 * Market local billing offer type.  Contains all the possible local billing offer types for each market.  This is not related to the MAPS offer type.  The main purpose for this table is to provide the values for drop down lists on the application screens.
	 */
	public static final MrktLclBilngOffrTyp MRKT_LCL_BILNG_OFFR_TYP = org.jooq.tables.MrktLclBilngOffrTyp.MRKT_LCL_BILNG_OFFR_TYP;

	/**
	 * The table WETRN.MRKT_LCL_BILNG_OFFR_TYP_AUDIT
	 */
	public static final MrktLclBilngOffrTypAudit MRKT_LCL_BILNG_OFFR_TYP_AUDIT = org.jooq.tables.MrktLclBilngOffrTypAudit.MRKT_LCL_BILNG_OFFR_TYP_AUDIT;

	/**
	 * The table WETRN.MRKT_LCL_BUS
	 */
	public static final MrktLclBus MRKT_LCL_BUS = org.jooq.tables.MrktLclBus.MRKT_LCL_BUS;

	/**
	 * The table WETRN.MRKT_MRKTG_PROD_RSPBLTY
	 */
	public static final MrktMrktgProdRspblty MRKT_MRKTG_PROD_RSPBLTY = org.jooq.tables.MrktMrktgProdRspblty.MRKT_MRKTG_PROD_RSPBLTY;

	/**
	 * The table WETRN.MRKT_OFFR_TAX_CATGRY_LKUP
	 */
	public static final MrktOffrTaxCatgryLkup MRKT_OFFR_TAX_CATGRY_LKUP = org.jooq.tables.MrktOffrTaxCatgryLkup.MRKT_OFFR_TAX_CATGRY_LKUP;

	/**
	 * The table WETRN.MRKT_OFS_USG
	 */
	public static final MrktOfsUsg MRKT_OFS_USG = org.jooq.tables.MrktOfsUsg.MRKT_OFS_USG;

	/**
	 * The table WETRN.MRKT_PERD
	 */
	public static final MrktPerd MRKT_PERD = org.jooq.tables.MrktPerd.MRKT_PERD;

	/**
	 * The table WETRN.MRKT_PERD_CATGRY
	 */
	public static final MrktPerdCatgry MRKT_PERD_CATGRY = org.jooq.tables.MrktPerdCatgry.MRKT_PERD_CATGRY;

	/**
	 * The table WETRN.MRKT_PERD_CMPGN_MAPG
	 */
	public static final MrktPerdCmpgnMapg MRKT_PERD_CMPGN_MAPG = org.jooq.tables.MrktPerdCmpgnMapg.MRKT_PERD_CMPGN_MAPG;

	/**
	 * The table WETRN.MRKT_PERD_DSTRBTN
	 */
	public static final MrktPerdDstrbtn MRKT_PERD_DSTRBTN = org.jooq.tables.MrktPerdDstrbtn.MRKT_PERD_DSTRBTN;

	/**
	 * The table WETRN.MRKT_PERD_PRFL
	 */
	public static final MrktPerdPrfl MRKT_PERD_PRFL = org.jooq.tables.MrktPerdPrfl.MRKT_PERD_PRFL;

	/**
	 * The table WETRN.MRKT_PERD_SKU_BIAS
	 */
	public static final MrktPerdSkuBias MRKT_PERD_SKU_BIAS = org.jooq.tables.MrktPerdSkuBias.MRKT_PERD_SKU_BIAS;

	/**
	 * The table WETRN.MRKT_PERD_SKU_PRC
	 */
	public static final MrktPerdSkuPrc MRKT_PERD_SKU_PRC = org.jooq.tables.MrktPerdSkuPrc.MRKT_PERD_SKU_PRC;

	/**
	 * Market Period Selling Price Rounding Factor; used to record how the Selling Price rounding is to be done for a Market.  And the Market Campaign from which it is effective
	 */
	public static final MrktPerdSlngPrcRndngFct MRKT_PERD_SLNG_PRC_RNDNG_FCT = org.jooq.tables.MrktPerdSlngPrcRndngFct.MRKT_PERD_SLNG_PRC_RNDNG_FCT;

	/**
	 * A Spread Image for a Market Vehicle Period.  Existence of this entity confirms that a Spread Image has been Imported into the MAPS system e.g. Spread 2 for Spain, Core Brochure, Campaign 13 2008.  Note: a row here indicates Spread Image existence and not the earlier stages of Spread Offer or Plan existence.
	 */
	public static final MrktPerdVehSprd MRKT_PERD_VEH_SPRD = org.jooq.tables.MrktPerdVehSprd.MRKT_PERD_VEH_SPRD;

	/**
	 * Used to define percentage-based ranges for Price Level Types within a market over time
	 */
	public static final MrktPrcLvl MRKT_PRC_LVL = org.jooq.tables.MrktPrcLvl.MRKT_PRC_LVL;

	/**
	 * Shows which Price Level Types have been selected for a given Market
	 */
	public static final MrktPrcLvlTyp MRKT_PRC_LVL_TYP = org.jooq.tables.MrktPrcLvlTyp.MRKT_PRC_LVL_TYP;

	/**
	 * The table WETRN.MRKT_PRFL
	 */
	public static final MrktPrfl MRKT_PRFL = org.jooq.tables.MrktPrfl.MRKT_PRFL;

	/**
	 * The table WETRN.MRKT_PRFL_CHRTY
	 */
	public static final MrktPrflChrty MRKT_PRFL_CHRTY = org.jooq.tables.MrktPrflChrty.MRKT_PRFL_CHRTY;

	/**
	 * Pricing Strategy for a concept in a market/campaign
	 */
	public static final MrktPrflPrcStrtgy MRKT_PRFL_PRC_STRTGY = org.jooq.tables.MrktPrflPrcStrtgy.MRKT_PRFL_PRC_STRTGY;

	/**
	 * The table WETRN.MRKT_PRFL_ROYLT
	 */
	public static final MrktPrflRoylt MRKT_PRFL_ROYLT = org.jooq.tables.MrktPrflRoylt.MRKT_PRFL_ROYLT;

	/**
	 * The table WETRN.MRKT_PROMTN
	 */
	public static final MrktPromtn MRKT_PROMTN = org.jooq.tables.MrktPromtn.MRKT_PROMTN;

	/**
	 * The table WETRN.MRKT_PROMTN_CLM
	 */
	public static final MrktPromtnClm MRKT_PROMTN_CLM = org.jooq.tables.MrktPromtnClm.MRKT_PROMTN_CLM;

	/**
	 * The table WETRN.MRKT_PROMTN_CMPLNC
	 */
	public static final MrktPromtnCmplnc MRKT_PROMTN_CMPLNC = org.jooq.tables.MrktPromtnCmplnc.MRKT_PROMTN_CMPLNC;

	/**
	 * Market relationship.  The relationship between markets for the specified relationship type.  The relationship lasts from the start period until the end period.  A null end period means that the relationship lasts forever or until the next start period for the same market and relationship type.  There is no source market period.  The source/target campaign mapping is handled by the campaign mapping table.
	 */
	public static final MrktRltnshp MRKT_RLTNSHP = org.jooq.tables.MrktRltnshp.MRKT_RLTNSHP;

	/**
	 * Market relationship type.  The type of relationship that is being modelled by the MRKT_RLTNSHP table.  The MRKT_ prefix indicates that the relationships are for MRKT_RLTNSHP (as opposed to any other kind of relationship).  The relationships are not at MRKT level (they apply to all markets).
	 */
	public static final MrktRltnshpTyp MRKT_RLTNSHP_TYP = org.jooq.tables.MrktRltnshpTyp.MRKT_RLTNSHP_TYP;

	/**
	 * The table WETRN.MRKT_SA_GTA_OVRRD_AUDIT
	 */
	public static final MrktSaGtaOvrrdAudit MRKT_SA_GTA_OVRRD_AUDIT = org.jooq.tables.MrktSaGtaOvrrdAudit.MRKT_SA_GTA_OVRRD_AUDIT;

	/**
	 * The table WETRN.MRKT_SET_BILNG_FSC
	 */
	public static final MrktSetBilngFsc MRKT_SET_BILNG_FSC = org.jooq.tables.MrktSetBilngFsc.MRKT_SET_BILNG_FSC;

	/**
	 * Audit trail of changes made via batch assignment or MAPS screens
	 */
	public static final MrktSetBilngFscAudit MRKT_SET_BILNG_FSC_AUDIT = org.jooq.tables.MrktSetBilngFscAudit.MRKT_SET_BILNG_FSC_AUDIT;

	/**
	 * The table WETRN.MRKT_SKU
	 */
	public static final MrktSku MRKT_SKU = org.jooq.tables.MrktSku.MRKT_SKU;

	/**
	 * Market sku unit split percent.  Unit split percentage for market sku.  Rows are inserted when there is a new split percentage for items effective from a specific offer period.
	 */
	public static final MrktSkuUnitSpltPct MRKT_SKU_UNIT_SPLT_PCT = org.jooq.tables.MrktSkuUnitSpltPct.MRKT_SKU_UNIT_SPLT_PCT;

	/**
	 * The table WETRN.MRKT_SLS
	 */
	public static final MrktSls MRKT_SLS = org.jooq.tables.MrktSls.MRKT_SLS;

	/**
	 * The table WETRN.MRKT_SLS_ALOCTN_GTA_OVRRD
	 */
	public static final MrktSlsAloctnGtaOvrrd MRKT_SLS_ALOCTN_GTA_OVRRD = org.jooq.tables.MrktSlsAloctnGtaOvrrd.MRKT_SLS_ALOCTN_GTA_OVRRD;

	/**
	 * Mapping of a sales channel and offer type (e.g. Regular, Special) to an unplanned vehicle.  Used for creation of unplanned offers.
	 */
	public static final MrktSlsChnlOffrTypSlsperd MRKT_SLS_CHNL_OFFR_TYP_SLSPERD = org.jooq.tables.MrktSlsChnlOffrTypSlsperd.MRKT_SLS_CHNL_OFFR_TYP_SLSPERD;

	/**
	 * The table WETRN.MRKT_SLS_CLS_WSL
	 */
	public static final MrktSlsClsWsl MRKT_SLS_CLS_WSL = org.jooq.tables.MrktSlsClsWsl.MRKT_SLS_CLS_WSL;

	/**
	 * Market Sales Period.  Data that is required for every sales period.  This table contains only sales periods (not years and quarters as in the MRKT_PERD table).
	 */
	public static final MrktSlsPerd MRKT_SLS_PERD = org.jooq.tables.MrktSlsPerd.MRKT_SLS_PERD;

	/**
	 * The table WETRN.MRKT_TAX_CATGRY
	 */
	public static final MrktTaxCatgry MRKT_TAX_CATGRY = org.jooq.tables.MrktTaxCatgry.MRKT_TAX_CATGRY;

	/**
	 * The table WETRN.MRKT_TAX_EFF_PERD
	 */
	public static final MrktTaxEffPerd MRKT_TAX_EFF_PERD = org.jooq.tables.MrktTaxEffPerd.MRKT_TAX_EFF_PERD;

	/**
	 * The table WETRN.MRKT_TAX_TYP
	 */
	public static final MrktTaxTyp MRKT_TAX_TYP = org.jooq.tables.MrktTaxTyp.MRKT_TAX_TYP;

	/**
	 * The table WETRN.MRKT_TAX_TYP_EFF_PERD
	 */
	public static final MrktTaxTypEffPerd MRKT_TAX_TYP_EFF_PERD = org.jooq.tables.MrktTaxTypEffPerd.MRKT_TAX_TYP_EFF_PERD;

	/**
	 * The table WETRN.MRKT_TAX_TYP_GRP
	 */
	public static final MrktTaxTypGrp MRKT_TAX_TYP_GRP = org.jooq.tables.MrktTaxTypGrp.MRKT_TAX_TYP_GRP;

	/**
	 * The table WETRN.MRKT_TAX_TYP_LKUP
	 */
	public static final MrktTaxTypLkup MRKT_TAX_TYP_LKUP = org.jooq.tables.MrktTaxTypLkup.MRKT_TAX_TYP_LKUP;

	/**
	 * The table WETRN.MRKT_TRND_SLS_PERD
	 */
	public static final MrktTrndSlsPerd MRKT_TRND_SLS_PERD = org.jooq.tables.MrktTrndSlsPerd.MRKT_TRND_SLS_PERD;

	/**
	 * Unit price rules by mrkt.  First entry found ordered by seq_nr applies.
	 */
	public static final MrktUnitPrc MRKT_UNIT_PRC = org.jooq.tables.MrktUnitPrc.MRKT_UNIT_PRC;

	/**
	 * The table WETRN.MRKT_UNIT_PRC_EFF_PERD
	 */
	public static final MrktUnitPrcEffPerd MRKT_UNIT_PRC_EFF_PERD = org.jooq.tables.MrktUnitPrcEffPerd.MRKT_UNIT_PRC_EFF_PERD;

	/**
	 * The table WETRN.MRKT_VEH
	 */
	public static final MrktVeh MRKT_VEH = org.jooq.tables.MrktVeh.MRKT_VEH;

	/**
	 * This table provides an exception in the case of copying offers from a market vehicle to a specific market vehicle (Sales Centre) within a market and campaign, as follows: When copying an offer within a market and campaign from one market vehicle to another, follow the normal rule of copying the commission type except when copying into the Sales Centre market vehicle when the default commission type should be used. This table holds the copy exception default commission type.
	 */
	public static final MrktVehCopyExcptn MRKT_VEH_COPY_EXCPTN = org.jooq.tables.MrktVehCopyExcptn.MRKT_VEH_COPY_EXCPTN;

	/**
	 * The table WETRN.MRKT_VEH_OFFR_CLS
	 */
	public static final MrktVehOffrCls MRKT_VEH_OFFR_CLS = org.jooq.tables.MrktVehOffrCls.MRKT_VEH_OFFR_CLS;

	/**
	 * The table WETRN.MRKT_VEH_PERD
	 */
	public static final MrktVehPerd MRKT_VEH_PERD = org.jooq.tables.MrktVehPerd.MRKT_VEH_PERD;

	/**
	 * The table WETRN.MRKT_VEH_PERD_BRCHR_PLCMT
	 */
	public static final MrktVehPerdBrchrPlcmt MRKT_VEH_PERD_BRCHR_PLCMT = org.jooq.tables.MrktVehPerdBrchrPlcmt.MRKT_VEH_PERD_BRCHR_PLCMT;

	/**
	 * Market vehicle period category.  Attributes required at category level.  This table is not required to have all combinations of mrkt, vehicle, period and category but it may do.  Rows are added when users require values stored at this level.
	 */
	public static final MrktVehPerdCatgry MRKT_VEH_PERD_CATGRY = org.jooq.tables.MrktVehPerdCatgry.MRKT_VEH_PERD_CATGRY;

	/**
	 * The table WETRN.MRKT_VEH_PERD_LCL_CHNL
	 */
	public static final MrktVehPerdLclChnl MRKT_VEH_PERD_LCL_CHNL = org.jooq.tables.MrktVehPerdLclChnl.MRKT_VEH_PERD_LCL_CHNL;

	/**
	 * The table WETRN.MRKT_VEH_PERD_SCTN
	 */
	public static final MrktVehPerdSctn MRKT_VEH_PERD_SCTN = org.jooq.tables.MrktVehPerdSctn.MRKT_VEH_PERD_SCTN;

	/**
	 * The table WETRN.MRKT_VEH_PERD_VER
	 */
	public static final MrktVehPerdVer MRKT_VEH_PERD_VER = org.jooq.tables.MrktVehPerdVer.MRKT_VEH_PERD_VER;

	/**
	 * The table WETRN.MRKT_VEH_POSTN
	 */
	public static final MrktVehPostn MRKT_VEH_POSTN = org.jooq.tables.MrktVehPostn.MRKT_VEH_POSTN;

	/**
	 * The table WETRN.MRKT_XPORT_STUS
	 */
	public static final MrktXportStus MRKT_XPORT_STUS = org.jooq.tables.MrktXportStus.MRKT_XPORT_STUS;

	/**
	 * The table WETRN.MSG_TYP
	 */
	public static final MsgTyp MSG_TYP = org.jooq.tables.MsgTyp.MSG_TYP;

	/**
	 * The table WETRN.MSTR_FSC_ASGNMT
	 */
	public static final MstrFscAsgnmt MSTR_FSC_ASGNMT = org.jooq.tables.MstrFscAsgnmt.MSTR_FSC_ASGNMT;

	/**
	 * The table WETRN.MV_REP_COST_HLPR
	 */
	public static final MvRepCostHlpr MV_REP_COST_HLPR = org.jooq.tables.MvRepCostHlpr.MV_REP_COST_HLPR;

	/**
	 * The table WETRN.OBJCTV
	 */
	public static final Objctv OBJCTV = org.jooq.tables.Objctv.OBJCTV;

	/**
	 * The table WETRN.OBJCTV_CMPNT
	 */
	public static final ObjctvCmpnt OBJCTV_CMPNT = org.jooq.tables.ObjctvCmpnt.OBJCTV_CMPNT;

	/**
	 * The table WETRN.OBJCTV_TYP
	 */
	public static final ObjctvTyp OBJCTV_TYP = org.jooq.tables.ObjctvTyp.OBJCTV_TYP;

	/**
	 * Object display message.  Object display messages for application objects.  E.g. Screens and reports.  There are none one or many messages for a MAPS object.
	 */
	public static final ObjDsplyMsg OBJ_DSPLY_MSG = org.jooq.tables.ObjDsplyMsg.OBJ_DSPLY_MSG;

	/**
	 * Display message type.  The type of a display message.  Used to determine the severity of the display message.  E.g. 'Warning.'.
	 */
	public static final ObjDsplyMsgTyp OBJ_DSPLY_MSG_TYP = org.jooq.tables.ObjDsplyMsgTyp.OBJ_DSPLY_MSG_TYP;

	/**
	 * The table WETRN.ODS_MRKT_FSC_COST
	 */
	public static final OdsMrktFscCost ODS_MRKT_FSC_COST = org.jooq.tables.OdsMrktFscCost.ODS_MRKT_FSC_COST;

	/**
	 * The table WETRN.ODS_MRKT_PRFL_COST
	 */
	public static final OdsMrktPrflCost ODS_MRKT_PRFL_COST = org.jooq.tables.OdsMrktPrflCost.ODS_MRKT_PRFL_COST;

	/**
	 * The table WETRN.OFFR
	 */
	public static final Offr OFFR = org.jooq.tables.Offr.OFFR;

	/**
	 * The table WETRN.OFFR_CLS
	 */
	public static final OffrCls OFFR_CLS = org.jooq.tables.OffrCls.OFFR_CLS;

	/**
	 * The table WETRN.OFFR_LOCK
	 */
	public static final OffrLock OFFR_LOCK = org.jooq.tables.OffrLock.OFFR_LOCK;

	/**
	 * The table WETRN.OFFR_PRFL_PRC_POINT
	 */
	public static final OffrPrflPrcPoint OFFR_PRFL_PRC_POINT = org.jooq.tables.OffrPrflPrcPoint.OFFR_PRFL_PRC_POINT;

	/**
	 * The table WETRN.OFFR_PRFL_SLS_CLS_PLCMT
	 */
	public static final OffrPrflSlsClsPlcmt OFFR_PRFL_SLS_CLS_PLCMT = org.jooq.tables.OffrPrflSlsClsPlcmt.OFFR_PRFL_SLS_CLS_PLCMT;

	/**
	 * The table WETRN.OFFR_PRSNTN_STRNTH
	 */
	public static final OffrPrsntnStrnth OFFR_PRSNTN_STRNTH = org.jooq.tables.OffrPrsntnStrnth.OFFR_PRSNTN_STRNTH;

	/**
	 * The table WETRN.OFFR_SKU_LINE
	 */
	public static final OffrSkuLine OFFR_SKU_LINE = org.jooq.tables.OffrSkuLine.OFFR_SKU_LINE;

	/**
	 * The table WETRN.OFFR_SKU_SET
	 */
	public static final OffrSkuSet OFFR_SKU_SET = org.jooq.tables.OffrSkuSet.OFFR_SKU_SET;

	/**
	 * The table WETRN.OFFR_SLS_CLS_SKU
	 */
	public static final OffrSlsClsSku OFFR_SLS_CLS_SKU = org.jooq.tables.OffrSlsClsSku.OFFR_SLS_CLS_SKU;

	/**
	 * The table WETRN.OFFR_STUS
	 */
	public static final OffrStus OFFR_STUS = org.jooq.tables.OffrStus.OFFR_STUS;

	/**
	 * The table WETRN.OFFR_TRAN
	 */
	public static final OffrTran OFFR_TRAN = org.jooq.tables.OffrTran.OFFR_TRAN;

	/**
	 * The table WETRN.OFFR_TRGT
	 */
	public static final OffrTrgt OFFR_TRGT = org.jooq.tables.OffrTrgt.OFFR_TRGT;

	/**
	 * The table WETRN.OFFR_TYP
	 */
	public static final OffrTyp OFFR_TYP = org.jooq.tables.OffrTyp.OFFR_TYP;

	/**
	 * The table WETRN.OFS_DSTRBTN_PCT
	 */
	public static final OfsDstrbtnPct OFS_DSTRBTN_PCT = org.jooq.tables.OfsDstrbtnPct.OFS_DSTRBTN_PCT;

	/**
	 * The table WETRN.PATRN_TYP
	 */
	public static final PatrnTyp PATRN_TYP = org.jooq.tables.PatrnTyp.PATRN_TYP;

	/**
	 * The table WETRN.PERD_OFS_NR
	 */
	public static final PerdOfsNr PERD_OFS_NR = org.jooq.tables.PerdOfsNr.PERD_OFS_NR;

	/**
	 * The table WETRN.PG_TYP
	 */
	public static final PgTyp PG_TYP = org.jooq.tables.PgTyp.PG_TYP;

	/**
	 * The table WETRN.PG_WGHT
	 */
	public static final PgWght PG_WGHT = org.jooq.tables.PgWght.PG_WGHT;

	/**
	 * The table WETRN.PLSQL_PROFILER_DATA
	 */
	public static final PlsqlProfilerData PLSQL_PROFILER_DATA = org.jooq.tables.PlsqlProfilerData.PLSQL_PROFILER_DATA;

	/**
	 * The table WETRN.PLSQL_PROFILER_RUNS
	 */
	public static final PlsqlProfilerRuns PLSQL_PROFILER_RUNS = org.jooq.tables.PlsqlProfilerRuns.PLSQL_PROFILER_RUNS;

	/**
	 * The table WETRN.PLSQL_PROFILER_UNITS
	 */
	public static final PlsqlProfilerUnits PLSQL_PROFILER_UNITS = org.jooq.tables.PlsqlProfilerUnits.PLSQL_PROFILER_UNITS;

	/**
	 * The table WETRN.PLUG
	 */
	public static final Plug PLUG = org.jooq.tables.Plug.PLUG;

	/**
	 * The table WETRN.PLUG_GRP
	 */
	public static final PlugGrp PLUG_GRP = org.jooq.tables.PlugGrp.PLUG_GRP;

	/**
	 * The table WETRN.PLUG_SLS
	 */
	public static final PlugSls PLUG_SLS = org.jooq.tables.PlugSls.PLUG_SLS;

	/**
	 * The table WETRN.PLUG_TYPE
	 */
	public static final PlugType PLUG_TYPE = org.jooq.tables.PlugType.PLUG_TYPE;

	/**
	 * The table WETRN.PRCS_STUS
	 */
	public static final PrcsStus PRCS_STUS = org.jooq.tables.PrcsStus.PRCS_STUS;

	/**
	 * Holds Price Level Types for Pricing Strategies - supplied by Central Master
	 */
	public static final PrcLvlTyp PRC_LVL_TYP = org.jooq.tables.PrcLvlTyp.PRC_LVL_TYP;

	/**
	 * The table WETRN.PRC_TYP
	 */
	public static final PrcTyp PRC_TYP = org.jooq.tables.PrcTyp.PRC_TYP;

	/**
	 * The table WETRN.PRFL
	 */
	public static final Prfl PRFL = org.jooq.tables.Prfl.PRFL;

	/**
	 * The table WETRN.PROD_ENDRSMT
	 */
	public static final ProdEndrsmt PROD_ENDRSMT = org.jooq.tables.ProdEndrsmt.PROD_ENDRSMT;

	/**
	 * The table WETRN.PROD_LIFE
	 */
	public static final ProdLife PROD_LIFE = org.jooq.tables.ProdLife.PROD_LIFE;

	/**
	 * The table WETRN.PROD_TYP
	 */
	public static final ProdTyp PROD_TYP = org.jooq.tables.ProdTyp.PROD_TYP;

	/**
	 * The table WETRN.PROMTN
	 */
	public static final Promtn PROMTN = org.jooq.tables.Promtn.PROMTN;

	/**
	 * The table WETRN.PROMTN_CLM
	 */
	public static final PromtnClm PROMTN_CLM = org.jooq.tables.PromtnClm.PROMTN_CLM;

	/**
	 * The table WETRN.PRSNL_FINCL_OBJCTV
	 */
	public static final PrsnlFinclObjctv PRSNL_FINCL_OBJCTV = org.jooq.tables.PrsnlFinclObjctv.PRSNL_FINCL_OBJCTV;

	/**
	 * The table WETRN.PRSNL_SRCE_OF_SLS_FINCL_OBJCTV
	 */
	public static final PrsnlSrceOfSlsFinclObjctv PRSNL_SRCE_OF_SLS_FINCL_OBJCTV = org.jooq.tables.PrsnlSrceOfSlsFinclObjctv.PRSNL_SRCE_OF_SLS_FINCL_OBJCTV;

	/**
	 * The table WETRN.PRSNL_VER
	 */
	public static final PrsnlVer PRSNL_VER = org.jooq.tables.PrsnlVer.PRSNL_VER;

	/**
	 * The table WETRN.PYMT_TYP
	 */
	public static final PymtTyp PYMT_TYP = org.jooq.tables.PymtTyp.PYMT_TYP;

	/**
	 * The table WETRN.PYMT_TYP_GRP
	 */
	public static final PymtTypGrp PYMT_TYP_GRP = org.jooq.tables.PymtTypGrp.PYMT_TYP_GRP;

	/**
	 * The table WETRN.REP_COL
	 */
	public static final RepCol REP_COL = org.jooq.tables.RepCol.REP_COL;

	/**
	 * The table WETRN.REP_COL_TYP
	 */
	public static final RepColTyp REP_COL_TYP = org.jooq.tables.RepColTyp.REP_COL_TYP;

	/**
	 * The table WETRN.REP_FILE_TYP
	 */
	public static final RepFileTyp REP_FILE_TYP = org.jooq.tables.RepFileTyp.REP_FILE_TYP;

	/**
	 * The table WETRN.REP_GLBL_TMPLT
	 */
	public static final RepGlblTmplt REP_GLBL_TMPLT = org.jooq.tables.RepGlblTmplt.REP_GLBL_TMPLT;

	/**
	 * The table WETRN.REP_MRKT_TMPLT
	 */
	public static final RepMrktTmplt REP_MRKT_TMPLT = org.jooq.tables.RepMrktTmplt.REP_MRKT_TMPLT;

	/**
	 * The table WETRN.REP_MSTR_QRY
	 */
	public static final RepMstrQry REP_MSTR_QRY = org.jooq.tables.RepMstrQry.REP_MSTR_QRY;

	/**
	 * The table WETRN.REP_MSTR_QRY_COL
	 */
	public static final RepMstrQryCol REP_MSTR_QRY_COL = org.jooq.tables.RepMstrQryCol.REP_MSTR_QRY_COL;

	/**
	 * The table WETRN.REP_MSTR_QRY_TMPLT
	 */
	public static final RepMstrQryTmplt REP_MSTR_QRY_TMPLT = org.jooq.tables.RepMstrQryTmplt.REP_MSTR_QRY_TMPLT;

	/**
	 * The table WETRN.REP_RUN_PRGRSS
	 */
	public static final RepRunPrgrss REP_RUN_PRGRSS = org.jooq.tables.RepRunPrgrss.REP_RUN_PRGRSS;

	/**
	 * The table WETRN.REP_SLS_TYP_VER
	 */
	public static final RepSlsTypVer REP_SLS_TYP_VER = org.jooq.tables.RepSlsTypVer.REP_SLS_TYP_VER;

	/**
	 * The table WETRN.REP_TMPLT_COL
	 */
	public static final RepTmpltCol REP_TMPLT_COL = org.jooq.tables.RepTmpltCol.REP_TMPLT_COL;

	/**
	 * The table WETRN.REP_TMPLT_FILE_TYP
	 */
	public static final RepTmpltFileTyp REP_TMPLT_FILE_TYP = org.jooq.tables.RepTmpltFileTyp.REP_TMPLT_FILE_TYP;

	/**
	 * The table WETRN.REP_TMPLT_SLS_TYP_VER
	 */
	public static final RepTmpltSlsTypVer REP_TMPLT_SLS_TYP_VER = org.jooq.tables.RepTmpltSlsTypVer.REP_TMPLT_SLS_TYP_VER;

	/**
	 * The table WETRN.REP_TMPLT_TYP
	 */
	public static final RepTmpltTyp REP_TMPLT_TYP = org.jooq.tables.RepTmpltTyp.REP_TMPLT_TYP;

	/**
	 * The table WETRN.RETL_TYP
	 */
	public static final RetlTyp RETL_TYP = org.jooq.tables.RetlTyp.RETL_TYP;

	/**
	 * Rounding Method to be used on the Selling Price i.e. Normal or Half method
	 */
	public static final RndngMthd RNDNG_MTHD = org.jooq.tables.RndngMthd.RNDNG_MTHD;

	/**
	 * The table WETRN.RPT
	 */
	public static final Rpt RPT = org.jooq.tables.Rpt.RPT;

	/**
	 * The table WETRN.RPT_FLTR
	 */
	public static final RptFltr RPT_FLTR = org.jooq.tables.RptFltr.RPT_FLTR;

	/**
	 * The table WETRN.RPT_LOG
	 */
	public static final RptLog RPT_LOG = org.jooq.tables.RptLog.RPT_LOG;

	/**
	 * The table WETRN.RPT_PARM_LOG
	 */
	public static final RptParmLog RPT_PARM_LOG = org.jooq.tables.RptParmLog.RPT_PARM_LOG;

	/**
	 * The table WETRN.RPT_SBTL_TYP
	 */
	public static final RptSbtlTyp RPT_SBTL_TYP = org.jooq.tables.RptSbtlTyp.RPT_SBTL_TYP;

	/**
	 * The table WETRN.RPT_STUS
	 */
	public static final RptStus RPT_STUS = org.jooq.tables.RptStus.RPT_STUS;

	/**
	 * The table WETRN.RTURN_SLS
	 */
	public static final RturnSls RTURN_SLS = org.jooq.tables.RturnSls.RTURN_SLS;

	/**
	 * The table WETRN.SA_AUTO_PRCS_OVRRD_AUDIT
	 */
	public static final SaAutoPrcsOvrrdAudit SA_AUTO_PRCS_OVRRD_AUDIT = org.jooq.tables.SaAutoPrcsOvrrdAudit.SA_AUTO_PRCS_OVRRD_AUDIT;

	/**
	 * The table WETRN.SCR_CSS
	 */
	public static final ScrCss SCR_CSS = org.jooq.tables.ScrCss.SCR_CSS;

	/**
	 * The table WETRN.SCR_JS
	 */
	public static final ScrJs SCR_JS = org.jooq.tables.ScrJs.SCR_JS;

	/**
	 * The table WETRN.SCR_OBJ_CONFIG
	 */
	public static final ScrObjConfig SCR_OBJ_CONFIG = org.jooq.tables.ScrObjConfig.SCR_OBJ_CONFIG;

	/**
	 * The table WETRN.SCR_OBJ_ERROR_MSG
	 */
	public static final ScrObjErrorMsg SCR_OBJ_ERROR_MSG = org.jooq.tables.ScrObjErrorMsg.SCR_OBJ_ERROR_MSG;

	/**
	 * The table WETRN.SET_PRC_TYP
	 */
	public static final SetPrcTyp SET_PRC_TYP = org.jooq.tables.SetPrcTyp.SET_PRC_TYP;

	/**
	 * The table WETRN.SGMT
	 */
	public static final Sgmt SGMT = org.jooq.tables.Sgmt.SGMT;

	/**
	 * The table WETRN.SKU
	 */
	public static final Sku SKU = org.jooq.tables.Sku.SKU;

	/**
	 * The table WETRN.SKU_COST
	 */
	public static final SkuCost SKU_COST = org.jooq.tables.SkuCost.SKU_COST;

	/**
	 * Describes methods available for identifying an appropriate sku_id for dly_bilng records during the Sales Allocation process
	 */
	public static final SkuMtchMthd SKU_MTCH_MTHD = org.jooq.tables.SkuMtchMthd.SKU_MTCH_MTHD;

	/**
	 * The table WETRN.SKU_REG_PRC
	 */
	public static final SkuRegPrc SKU_REG_PRC = org.jooq.tables.SkuRegPrc.SKU_REG_PRC;

	/**
	 * Sales allocation auto process override.  Sales channel and offer type combinations that are not to be auto matched.  The auto and manual status codes are set to the values in this table.  Initially specified for China to force Special billing offers to unplanned offers.
	 */
	public static final SlsAloctnAutoPrcsOvrrd SLS_ALOCTN_AUTO_PRCS_OVRRD = org.jooq.tables.SlsAloctnAutoPrcsOvrrd.SLS_ALOCTN_AUTO_PRCS_OVRRD;

	/**
	 * Sales allocation auto status codes.
	 */
	public static final SlsAloctnAutoStus SLS_ALOCTN_AUTO_STUS = org.jooq.tables.SlsAloctnAutoStus.SLS_ALOCTN_AUTO_STUS;

	/**
	 * Sales allocation data exclusion.  Data exclusion rules for specific sales channel, billing offer type and data exclusion type.  Some screens and reports need to exclude data that would otherwise be shown if the default rules were used.
	 */
	public static final SlsAloctnDataXclusn SLS_ALOCTN_DATA_XCLUSN = org.jooq.tables.SlsAloctnDataXclusn.SLS_ALOCTN_DATA_XCLUSN;

	/**
	 * Sales allocation manual status codes.
	 */
	public static final SlsAloctnManulStus SLS_ALOCTN_MANUL_STUS = org.jooq.tables.SlsAloctnManulStus.SLS_ALOCTN_MANUL_STUS;

	/**
	 * Audit Trail table populated when a user resets Sales Allocation via MAPS
	 */
	public static final SlsAloctnResetAudit SLS_ALOCTN_RESET_AUDIT = org.jooq.tables.SlsAloctnResetAudit.SLS_ALOCTN_RESET_AUDIT;

	/**
	 * The table WETRN.SLS_CLS
	 */
	public static final SlsCls SLS_CLS = org.jooq.tables.SlsCls.SLS_CLS;

	/**
	 * The table WETRN.SLS_PERD_RNG
	 */
	public static final SlsPerdRng SLS_PERD_RNG = org.jooq.tables.SlsPerdRng.SLS_PERD_RNG;

	/**
	 * The table WETRN.SLS_SRCE
	 */
	public static final SlsSrce SLS_SRCE = org.jooq.tables.SlsSrce.SLS_SRCE;

	/**
	 * The table WETRN.SLS_STUS
	 */
	public static final SlsStus SLS_STUS = org.jooq.tables.SlsStus.SLS_STUS;

	/**
	 * The table WETRN.SLS_TYP
	 */
	public static final SlsTyp SLS_TYP = org.jooq.tables.SlsTyp.SLS_TYP;

	/**
	 * The table WETRN.SLS_TYP_GRP
	 */
	public static final SlsTypGrp SLS_TYP_GRP = org.jooq.tables.SlsTypGrp.SLS_TYP_GRP;

	/**
	 * The table WETRN.SRCE_OF_SLS_CUST_GRP
	 */
	public static final SrceOfSlsCustGrp SRCE_OF_SLS_CUST_GRP = org.jooq.tables.SrceOfSlsCustGrp.SRCE_OF_SLS_CUST_GRP;

	/**
	 * The table WETRN.SRCE_OF_SLS_ELMNT
	 */
	public static final SrceOfSlsElmnt SRCE_OF_SLS_ELMNT = org.jooq.tables.SrceOfSlsElmnt.SRCE_OF_SLS_ELMNT;

	/**
	 * The table WETRN.SRCE_OF_SLS_FINCL_OBJCTV
	 */
	public static final SrceOfSlsFinclObjctv SRCE_OF_SLS_FINCL_OBJCTV = org.jooq.tables.SrceOfSlsFinclObjctv.SRCE_OF_SLS_FINCL_OBJCTV;

	/**
	 * The table WETRN.SRCE_OF_SLS_PROD_TYP
	 */
	public static final SrceOfSlsProdTyp SRCE_OF_SLS_PROD_TYP = org.jooq.tables.SrceOfSlsProdTyp.SRCE_OF_SLS_PROD_TYP;

	/**
	 * The table WETRN.SRCE_OF_SLS_SLS_CLS
	 */
	public static final SrceOfSlsSlsCls SRCE_OF_SLS_SLS_CLS = org.jooq.tables.SrceOfSlsSlsCls.SRCE_OF_SLS_SLS_CLS;

	/**
	 * The table WETRN.SRCE_OF_SLS_VEH_TYP
	 */
	public static final SrceOfSlsVehTyp SRCE_OF_SLS_VEH_TYP = org.jooq.tables.SrceOfSlsVehTyp.SRCE_OF_SLS_VEH_TYP;

	/**
	 * The table WETRN.SSNL_EVNT
	 */
	public static final SsnlEvnt SSNL_EVNT = org.jooq.tables.SsnlEvnt.SSNL_EVNT;

	/**
	 * The table WETRN.STD_OFFR
	 */
	public static final StdOffr STD_OFFR = org.jooq.tables.StdOffr.STD_OFFR;

	/**
	 * The table WETRN.STD_OFFR_PRFL_PLCMT
	 */
	public static final StdOffrPrflPlcmt STD_OFFR_PRFL_PLCMT = org.jooq.tables.StdOffrPrflPlcmt.STD_OFFR_PRFL_PLCMT;

	/**
	 * The table WETRN.STD_OFFR_PRFL_PRCPT
	 */
	public static final StdOffrPrflPrcpt STD_OFFR_PRFL_PRCPT = org.jooq.tables.StdOffrPrflPrcpt.STD_OFFR_PRFL_PRCPT;

	/**
	 * The table WETRN.STD_OFFR_PRFL_PRC_POINT
	 */
	public static final StdOffrPrflPrcPoint STD_OFFR_PRFL_PRC_POINT = org.jooq.tables.StdOffrPrflPrcPoint.STD_OFFR_PRFL_PRC_POINT;

	/**
	 * The table WETRN.STD_OFFR_PRFL_SLS_CLS
	 */
	public static final StdOffrPrflSlsCls STD_OFFR_PRFL_SLS_CLS = org.jooq.tables.StdOffrPrflSlsCls.STD_OFFR_PRFL_SLS_CLS;

	/**
	 * The table WETRN.STG_DSTRBTD_MRKT_SLS
	 */
	public static final StgDstrbtdMrktSls STG_DSTRBTD_MRKT_SLS = org.jooq.tables.StgDstrbtdMrktSls.STG_DSTRBTD_MRKT_SLS;

	/**
	 * The table WETRN.SUPLR
	 */
	public static final Suplr SUPLR = org.jooq.tables.Suplr.SUPLR;

	/**
	 * The table WETRN.SYS_PARM
	 */
	public static final SysParm SYS_PARM = org.jooq.tables.SysParm.SYS_PARM;

	/**
	 * The table WETRN.TEMP_OFFER_COPY
	 */
	public static final TempOfferCopy TEMP_OFFER_COPY = org.jooq.tables.TempOfferCopy.TEMP_OFFER_COPY;

	/**
	 * The table WETRN.TEMP_OFFR_PRFL_PRC_POINT
	 */
	public static final TempOffrPrflPrcPoint TEMP_OFFR_PRFL_PRC_POINT = org.jooq.tables.TempOffrPrflPrcPoint.TEMP_OFFR_PRFL_PRC_POINT;

	/**
	 * The table WETRN.TPC
	 */
	public static final Tpc TPC = org.jooq.tables.Tpc.TPC;

	/**
	 * The table WETRN.TPC_XPORT_STUS
	 */
	public static final TpcXportStus TPC_XPORT_STUS = org.jooq.tables.TpcXportStus.TPC_XPORT_STUS;

	/**
	 * The table WETRN.TRAN_TYP
	 */
	public static final TranTyp TRAN_TYP = org.jooq.tables.TranTyp.TRAN_TYP;

	/**
	 * The table WETRN.TRGT_CNSMR_GRP
	 */
	public static final TrgtCnsmrGrp TRGT_CNSMR_GRP = org.jooq.tables.TrgtCnsmrGrp.TRGT_CNSMR_GRP;

	/**
	 * The table WETRN.TRND_ALOCTN_AUTO_PRCS_OVRRD
	 */
	public static final TrndAloctnAutoPrcsOvrrd TRND_ALOCTN_AUTO_PRCS_OVRRD = org.jooq.tables.TrndAloctnAutoPrcsOvrrd.TRND_ALOCTN_AUTO_PRCS_OVRRD;

	/**
	 * The table WETRN.TRND_BILNG_DAYS
	 */
	public static final TrndBilngDays TRND_BILNG_DAYS = org.jooq.tables.TrndBilngDays.TRND_BILNG_DAYS;

	/**
	 * The table WETRN.TRND_CTGRY_SLS_JOB
	 */
	public static final TrndCtgrySlsJob TRND_CTGRY_SLS_JOB = org.jooq.tables.TrndCtgrySlsJob.TRND_CTGRY_SLS_JOB;

	/**
	 * The table WETRN.TRND_CTGRY_SLS_NEW
	 */
	public static final TrndCtgrySlsNew TRND_CTGRY_SLS_NEW = org.jooq.tables.TrndCtgrySlsNew.TRND_CTGRY_SLS_NEW;

	/**
	 * The table WETRN.TRND_CTGRY_SLS_PCT_OVR
	 */
	public static final TrndCtgrySlsPctOvr TRND_CTGRY_SLS_PCT_OVR = org.jooq.tables.TrndCtgrySlsPctOvr.TRND_CTGRY_SLS_PCT_OVR;

	/**
	 * The table WETRN.TRND_CTGRY_SLS_ST
	 */
	public static final TrndCtgrySlsSt TRND_CTGRY_SLS_ST = org.jooq.tables.TrndCtgrySlsSt.TRND_CTGRY_SLS_ST;

	/**
	 * The table WETRN.TRND_EXCPTN
	 */
	public static final TrndExcptn TRND_EXCPTN = org.jooq.tables.TrndExcptn.TRND_EXCPTN;

	/**
	 * The table WETRN.TRND_SLS_PCT_OVR
	 */
	public static final TrndSlsPctOvr TRND_SLS_PCT_OVR = org.jooq.tables.TrndSlsPctOvr.TRND_SLS_PCT_OVR;

	/**
	 * The table WETRN.TRND_SLS_ST
	 */
	public static final TrndSlsSt TRND_SLS_ST = org.jooq.tables.TrndSlsSt.TRND_SLS_ST;

	/**
	 * The table WETRN.TRNSFRM_PREV_YR_MRKT_PERD
	 */
	public static final TrnsfrmPrevYrMrktPerd TRNSFRM_PREV_YR_MRKT_PERD = org.jooq.tables.TrnsfrmPrevYrMrktPerd.TRNSFRM_PREV_YR_MRKT_PERD;

	/**
	 * The table WETRN.T_LOG_ERRORS
	 */
	public static final TLogErrors T_LOG_ERRORS = org.jooq.tables.TLogErrors.T_LOG_ERRORS;

	/**
	 * The table WETRN.UNIT_RPTG_LVL
	 */
	public static final UnitRptgLvl UNIT_RPTG_LVL = org.jooq.tables.UnitRptgLvl.UNIT_RPTG_LVL;

	/**
	 * Conversion factors for any uom to the unit value of that uom_typ.
	 */
	public static final UomCnvrsn UOM_CNVRSN = org.jooq.tables.UomCnvrsn.UOM_CNVRSN;

	/**
	 * Valid measure types for units of measure (e.g. Length, Mass, Volume).
	 */
	public static final UomTyp UOM_TYP = org.jooq.tables.UomTyp.UOM_TYP;

	/**
	 * The table WETRN.VEH
	 */
	public static final Veh VEH = org.jooq.tables.Veh.VEH;

	/**
	 * The table WETRN.VEH_TYP
	 */
	public static final VehTyp VEH_TYP = org.jooq.tables.VehTyp.VEH_TYP;

	/**
	 * The table WETRN.VER
	 */
	public static final Ver VER = org.jooq.tables.Ver.VER;

	/**
	 * The table WETRN.VER_GRP
	 */
	public static final VerGrp VER_GRP = org.jooq.tables.VerGrp.VER_GRP;

	/**
	 * The table WETRN.VER_SLS_TYP
	 */
	public static final VerSlsTyp VER_SLS_TYP = org.jooq.tables.VerSlsTyp.VER_SLS_TYP;

	/**
	 * The table WETRN.VER_TYP
	 */
	public static final VerTyp VER_TYP = org.jooq.tables.VerTyp.VER_TYP;

	/**
	 * The table WETRN.VW_BEST_SKU_COST
	 */
	public static final VwBestSkuCost VW_BEST_SKU_COST = org.jooq.tables.VwBestSkuCost.VW_BEST_SKU_COST;

	/**
	 * The table WETRN.V_BEST_COST
	 */
	public static final VBestCost V_BEST_COST = org.jooq.tables.VBestCost.V_BEST_COST;

	/**
	 * snapshot table for snapshot V_BRND
	 */
	public static final VBrnd V_BRND = org.jooq.tables.VBrnd.V_BRND;

	/**
	 * The table WETRN.V_OFFR
	 */
	public static final VOffr V_OFFR = org.jooq.tables.VOffr.V_OFFR;

	/**
	 * The table WETRN.V_OFFR_ALL
	 */
	public static final VOffrAll V_OFFR_ALL = org.jooq.tables.VOffrAll.V_OFFR_ALL;

	/**
	 * The table WETRN.V_OFFR_ALL_WITH_BEST_COST
	 */
	public static final VOffrAllWithBestCost V_OFFR_ALL_WITH_BEST_COST = org.jooq.tables.VOffrAllWithBestCost.V_OFFR_ALL_WITH_BEST_COST;

	/**
	 * The table WETRN.V_OFFR_SLS_ALL
	 */
	public static final VOffrSlsAll V_OFFR_SLS_ALL = org.jooq.tables.VOffrSlsAll.V_OFFR_SLS_ALL;

	/**
	 * The table WETRN.V_OFFR_SLS_MS_GIFT
	 */
	public static final VOffrSlsMsGift V_OFFR_SLS_MS_GIFT = org.jooq.tables.VOffrSlsMsGift.V_OFFR_SLS_MS_GIFT;

	/**
	 * The table WETRN.V_OFFR_WITHOUT_SLS_PERD
	 */
	public static final VOffrWithoutSlsPerd V_OFFR_WITHOUT_SLS_PERD = org.jooq.tables.VOffrWithoutSlsPerd.V_OFFR_WITHOUT_SLS_PERD;

	/**
	 * The table WETRN.V_OFFR_WITH_MS_GIFT
	 */
	public static final VOffrWithMsGift V_OFFR_WITH_MS_GIFT = org.jooq.tables.VOffrWithMsGift.V_OFFR_WITH_MS_GIFT;

	/**
	 * The table WETRN.WHAT_IF_SCNRIO
	 */
	public static final WhatIfScnrio WHAT_IF_SCNRIO = org.jooq.tables.WhatIfScnrio.WHAT_IF_SCNRIO;

	/**
	 * The table WETRN.WHAT_IF_TRAN
	 */
	public static final WhatIfTran WHAT_IF_TRAN = org.jooq.tables.WhatIfTran.WHAT_IF_TRAN;

	/**
	 * The table WETRN.XCHNG_RTE
	 */
	public static final XchngRte XCHNG_RTE = org.jooq.tables.XchngRte.XCHNG_RTE;

	/**
	 * The table WETRN.XPORT_STUS
	 */
	public static final XportStus XPORT_STUS = org.jooq.tables.XportStus.XPORT_STUS;

	/**
	 * The table WETRN.XPORT_STUS_TRAN
	 */
	public static final XportStusTran XPORT_STUS_TRAN = org.jooq.tables.XportStusTran.XPORT_STUS_TRAN;

	/**
	 * The table WETRN.XPORT_STUS_TYP
	 */
	public static final XportStusTyp XPORT_STUS_TYP = org.jooq.tables.XportStusTyp.XPORT_STUS_TYP;

	/**
	 * Data Pump Master Table IMPORT                         SCHEMA                        
	 */
	public static final ImpdpMapsWetrn IMPDP_MAPS_WETRN = org.jooq.tables.ImpdpMapsWetrn.IMPDP_MAPS_WETRN;
}
