/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.pa_maps_copy;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.PaMapsCopy;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreateOffsetsForCampaign extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1809217329;

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.CREATE_OFFSETS_FOR_CAMPAIGN.PAR_MRKTID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_MRKTID = createParameter("PAR_MRKTID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.CREATE_OFFSETS_FOR_CAMPAIGN.PAR_VEHID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_VEHID = createParameter("PAR_VEHID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.CREATE_OFFSETS_FOR_CAMPAIGN.PAR_OFFRPERD</code>.
	 */
	public static final Parameter<BigDecimal> PAR_OFFRPERD = createParameter("PAR_OFFRPERD", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.CREATE_OFFSETS_FOR_CAMPAIGN.PAR_USER</code>.
	 */
	public static final Parameter<String> PAR_USER = createParameter("PAR_USER", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public CreateOffsetsForCampaign() {
		super("CREATE_OFFSETS_FOR_CAMPAIGN", Wetrn.WETRN, PaMapsCopy.PA_MAPS_COPY);

		addInParameter(PAR_MRKTID);
		addInParameter(PAR_VEHID);
		addInParameter(PAR_OFFRPERD);
		addInParameter(PAR_USER);
	}

	/**
	 * Set the <code>PAR_MRKTID</code> parameter IN value to the routine
	 */
	public void setParMrktid(Number value) {
		setNumber(PAR_MRKTID, value);
	}

	/**
	 * Set the <code>PAR_VEHID</code> parameter IN value to the routine
	 */
	public void setParVehid(Number value) {
		setNumber(PAR_VEHID, value);
	}

	/**
	 * Set the <code>PAR_OFFRPERD</code> parameter IN value to the routine
	 */
	public void setParOffrperd(Number value) {
		setNumber(PAR_OFFRPERD, value);
	}

	/**
	 * Set the <code>PAR_USER</code> parameter IN value to the routine
	 */
	public void setParUser(String value) {
		setValue(PAR_USER, value);
	}
}
