/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.pa_maps_copy;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.PaMapsCopy;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdateRegPrcAmt extends AbstractRoutine<BigDecimal> {

	private static final long serialVersionUID = -630305116;

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.UPDATE_REG_PRC_AMT.RETURN_VALUE</code>.
	 */
	public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.UPDATE_REG_PRC_AMT.PAR_OFFRID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_OFFRID = createParameter("PAR_OFFRID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.UPDATE_REG_PRC_AMT.PAR_NEWMRKTID</code>.
	 */
	public static final Parameter<BigDecimal> PAR_NEWMRKTID = createParameter("PAR_NEWMRKTID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>WETRN.PA_MAPS_COPY.UPDATE_REG_PRC_AMT.PAR_NEWOFFRPERD</code>.
	 */
	public static final Parameter<BigDecimal> PAR_NEWOFFRPERD = createParameter("PAR_NEWOFFRPERD", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public UpdateRegPrcAmt() {
		super("UPDATE_REG_PRC_AMT", Wetrn.WETRN, PaMapsCopy.PA_MAPS_COPY, org.jooq.impl.SQLDataType.NUMERIC);

		setReturnParameter(RETURN_VALUE);
		addInParameter(PAR_OFFRID);
		addInParameter(PAR_NEWMRKTID);
		addInParameter(PAR_NEWOFFRPERD);
	}

	/**
	 * Set the <code>PAR_OFFRID</code> parameter IN value to the routine
	 */
	public void setParOffrid(Number value) {
		setNumber(PAR_OFFRID, value);
	}

	/**
	 * Set the <code>PAR_OFFRID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParOffrid(Field<? extends Number> field) {
		setNumber(PAR_OFFRID, field);
	}

	/**
	 * Set the <code>PAR_NEWMRKTID</code> parameter IN value to the routine
	 */
	public void setParNewmrktid(Number value) {
		setNumber(PAR_NEWMRKTID, value);
	}

	/**
	 * Set the <code>PAR_NEWMRKTID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParNewmrktid(Field<? extends Number> field) {
		setNumber(PAR_NEWMRKTID, field);
	}

	/**
	 * Set the <code>PAR_NEWOFFRPERD</code> parameter IN value to the routine
	 */
	public void setParNewoffrperd(Number value) {
		setNumber(PAR_NEWOFFRPERD, value);
	}

	/**
	 * Set the <code>PAR_NEWOFFRPERD</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setParNewoffrperd(Field<? extends Number> field) {
		setNumber(PAR_NEWOFFRPERD, field);
	}
}
