/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.app_pagination_export;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.AppPaginationExport;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getprofilelevelrecords extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 475622022;

	/**
	 * The parameter <code>WETRN.APP_PAGINATION_EXPORT.GETPROFILELEVELRECORDS.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"), false);

	/**
	 * The parameter <code>WETRN.APP_PAGINATION_EXPORT.GETPROFILELEVELRECORDS.POFFR_ID</code>.
	 */
	public static final Parameter<BigDecimal> POFFR_ID = createParameter("POFFR_ID", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public Getprofilelevelrecords() {
		super("GETPROFILELEVELRECORDS", Wetrn.WETRN, AppPaginationExport.APP_PAGINATION_EXPORT, org.jooq.impl.DefaultDataType.getDefaultDataType("TABLE"));

		setReturnParameter(RETURN_VALUE);
		addInParameter(POFFR_ID);
	}

	/**
	 * Set the <code>POFFR_ID</code> parameter IN value to the routine
	 */
	public void setPoffrId(Number value) {
		setNumber(POFFR_ID, value);
	}

	/**
	 * Set the <code>POFFR_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPoffrId(Field<? extends Number> field) {
		setNumber(POFFR_ID, field);
	}
}
