/**
 * This class is generated by jOOQ
 */
package org.jooq.packages.app_plsql_output;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.Wetrn;
import org.jooq.impl.AbstractRoutine;
import org.jooq.packages.AppPlsqlOutput;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddMsg extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -1067077323;

	/**
	 * The parameter <code>WETRN.APP_PLSQL_OUTPUT.ADD_MSG.P_MSG_TYPE</code>.
	 */
	public static final Parameter<String> P_MSG_TYPE = createParameter("P_MSG_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(20), false);

	/**
	 * The parameter <code>WETRN.APP_PLSQL_OUTPUT.ADD_MSG.P_MSG_VALUE</code>.
	 */
	public static final Parameter<String> P_MSG_VALUE = createParameter("P_MSG_VALUE", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public AddMsg() {
		super("ADD_MSG", Wetrn.WETRN, AppPlsqlOutput.APP_PLSQL_OUTPUT);

		addInParameter(P_MSG_TYPE);
		addInParameter(P_MSG_VALUE);
	}

	/**
	 * Set the <code>P_MSG_TYPE</code> parameter IN value to the routine
	 */
	public void setPMsgType(String value) {
		setValue(P_MSG_TYPE, value);
	}

	/**
	 * Set the <code>P_MSG_VALUE</code> parameter IN value to the routine
	 */
	public void setPMsgValue(String value) {
		setValue(P_MSG_VALUE, value);
	}
}
